In [1]:
from neo4j import GraphDatabase
from dotenv import load_dotenv
import json
import os
import sys
import numpy as np
import pandas as pd
import re
from py2neo import Graph
from IPython import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [2]:
uri='neo4j://127.0.0.1:7687'
username='neo4j'
password='eKx2r34567'

In [3]:
def connect_to_neo4j():
    try:
        return Graph("bolt://localhost:7687", auth=("neo4j", "eKx2r34567"))
    except Exception as e:
        return None

graph = connect_to_neo4j()
graph.run("MATCH (n) RETURN n.name AS name, n.label AS label")

 name | label
------|------------
 null | Monitoring
 null | Monitoring
 null | Monitoring

In [4]:
def load_data():
    query = """
        MATCH (n1)-[r1]-(c:Communication)-[r2]-(n2) WHERE r1.type="sent" AND r2.type="received"  
        RETURN n1.name as source_entity,r1.type as source_entity_action,c.content as content,c.timestamp as timestamp,r2.type as target_entity_action,n2.name as target_entity ORDER BY c.timestamp
    """
    df = graph.run(query).to_data_frame()
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['date'] = df['timestamp'].dt.date
    df['hour'] = df['timestamp'].dt.hour
    df['minute'] = df['timestamp'].dt.minute
    df['time'] = df['timestamp'].dt.time
    return df

df = load_data()

In [5]:
df['date']=df['timestamp'].dt.date
df['hour']=df['timestamp'].dt.hour
df['minute']=df['timestamp'].dt.minute
df['time']=df['timestamp'].dt.time
df['minutes_from_day_start']=df['timestamp'].dt.hour*60+df['timestamp'].dt.minute
df['minutes_from_day_start']=df['minutes_from_day_start'].astype(int)
df['minutes_from_day_start']=df['minutes_from_day_start'].astype(str)
df['minutes_from_day_start']=df['minutes_from_day_start'].astype(int)

In [6]:
df

,source_entity,source_entity_action,content,timestamp,target_entity_action,target_entity,date,hour,minute,time,minutes_from_day_start
0,The Lookout,sent,"Hey The Intern, it's The Lookout! Just spotted...",2040-10-01 08:09:00,received,The Intern,2040-10-01,8,9,08:09:00,489
1,The Intern,sent,"Hey The Lookout, The Intern here! I'd absolute...",2040-10-01 08:10:00,received,The Lookout,2040-10-01,8,10,08:10:00,490
2,Kelly,sent,"Sam, it's Kelly! Let's meet at Sunrise Point a...",2040-10-01 08:13:00,received,Sam,2040-10-01,8,13,08:13:00,493
3,The Intern,sent,"Mrs. Money, it's The Intern. Just checking in ...",2040-10-01 08:16:00,received,Mrs. Money,2040-10-01,8,16,08:16:00,496
4,Mrs. Money,sent,"Boss, it's Mrs. Money. I've reviewed our opera...",2040-10-01 08:19:00,received,Boss,2040-10-01,8,19,08:19:00,499
...,...,...,...,...,...,...,...,...,...,...,...
579,Oceanus City Council,sent,"Green Guardians, Oceanus City Council here. Yo...",2040-10-14 12:50:00,received,Green Guardians,2040-10-14,12,50,12:50:00,770
580,Green Guardians,sent,"EcoVigil, Green Guardians HQ here. Your video ...",2040-10-14 12:51:00,received,EcoVigil,2040-10-14,12,51,12:51:00,771
581,Defender,sent,Defender to Mako. Be advised that conservation...,2040-10-14 13:31:00,received,Mako,2040-10-14,13,31,13:31:00,811
582,Knowles,sent,"Knowles, Mako here. Proceed to southern dock a...",2040-10-14 13:34:00,received,Davis,2040-10-14,13,34,13:34:00,814
583,Knowles,sent,"Davis, this is Knowles. Approaching southern d...",2040-10-14 13:35:00,received,Davis,2040-10-14,13,35,13:35:00,815

In [7]:
# Function to create dynamic time groups
def create_time_groups(timestamp, interval_minutes=15):
    """Convert timestamp to time group with specified interval"""
    hour = timestamp.hour
    minute = timestamp.minute
    
    # Find the start of the interval block
    start_minute = (minute // interval_minutes) * interval_minutes
    
    # Create the time group string with leading zero for single digits
    start_minute_str = f"{start_minute:02d}"
    
    # Calculate end minute
    end_minute = ((minute // interval_minutes) * interval_minutes) + interval_minutes
    if end_minute == 60:
        end_minute = 0
        hour += 1
    
    end_minute_str = f"{end_minute:02d}"
    
    # Format time with AM/PM
    ampm = 'am' if hour < 12 else 'pm'
    if hour > 12:
        hour -= 12
    elif hour == 0:
        hour = 12
    
    start_time = f"{hour}.{start_minute_str}{ampm}"
    
    # Handle end time AM/PM
    end_hour = timestamp.hour
    end_hour += ((minute // interval_minutes) * interval_minutes + interval_minutes) // 60
    end_ampm = 'am' if end_hour < 12 else 'pm'
    if end_hour > 12:
        end_hour -= 12
    elif end_hour == 0:
        end_hour = 12
    
    end_time = f"{end_hour}.{end_minute_str}{end_ampm}"
    
    return f"{start_time}-{end_time}"

# Apply the function to create time groups (default 15-minute intervals)
df['time_group'] = df['timestamp'].apply(lambda x: create_time_groups(x, 15))

# Also create a sortable version for chronological ordering
def create_sortable_time_group(timestamp, interval_minutes=15):
    """Create a sortable time group for chronological ordering"""
    hour = timestamp.hour
    minute = timestamp.minute
    start_minute = (minute // interval_minutes) * interval_minutes
    return hour * 60 + start_minute

df['time_group_sortable'] = df['timestamp'].apply(lambda x: create_sortable_time_group(x, 15))

In [8]:
df

,source_entity,source_entity_action,content,timestamp,target_entity_action,target_entity,date,hour,minute,time,minutes_from_day_start,time_group,time_group_sortable
0,The Lookout,sent,"Hey The Intern, it's The Lookout! Just spotted...",2040-10-01 08:09:00,received,The Intern,2040-10-01,8,9,08:09:00,489,8.00am-8.15am,480
1,The Intern,sent,"Hey The Lookout, The Intern here! I'd absolute...",2040-10-01 08:10:00,received,The Lookout,2040-10-01,8,10,08:10:00,490,8.00am-8.15am,480
2,Kelly,sent,"Sam, it's Kelly! Let's meet at Sunrise Point a...",2040-10-01 08:13:00,received,Sam,2040-10-01,8,13,08:13:00,493,8.00am-8.15am,480
3,The Intern,sent,"Mrs. Money, it's The Intern. Just checking in ...",2040-10-01 08:16:00,received,Mrs. Money,2040-10-01,8,16,08:16:00,496,8.15am-8.30am,495
4,Mrs. Money,sent,"Boss, it's Mrs. Money. I've reviewed our opera...",2040-10-01 08:19:00,received,Boss,2040-10-01,8,19,08:19:00,499,8.15am-8.30am,495
...,...,...,...,...,...,...,...,...,...,...,...,...,...
579,Oceanus City Council,sent,"Green Guardians, Oceanus City Council here. Yo...",2040-10-14 12:50:00,received,Green Guardians,2040-10-14,12,50,12:50:00,770,1.45pm-1.00pm,765
580,Green Guardians,sent,"EcoVigil, Green Guardians HQ here. Your video ...",2040-10-14 12:51:00,received,EcoVigil,2040-10-14,12,51,12:51:00,771,1.45pm-1.00pm,765
581,Defender,sent,Defender to Mako. Be advised that conservation...,2040-10-14 13:31:00,received,Mako,2040-10-14,13,31,13:31:00,811,1.30pm-1.45pm,810
582,Knowles,sent,"Knowles, Mako here. Proceed to southern dock a...",2040-10-14 13:34:00,received,Davis,2040-10-14,13,34,13:34:00,814,1.30pm-1.45pm,810
583,Knowles,sent,"Davis, this is Knowles. Approaching southern d...",2040-10-14 13:35:00,received,Davis,2040-10-14,13,35,13:35:00,815,1.30pm-1.45pm,810

In [10]:
df['timestamp'].min(),df['timestamp'].max()

(Timestamp('2040-10-01 08:09:00'), Timestamp('2040-10-14 13:35:00'))

In [11]:
df.groupby('date')['hour'].agg(['min','max']).reset_index()

          date  min  max
0   2040-10-01    8   12
1   2040-10-02    8   13
2   2040-10-03    8   11
3   2040-10-04    8   13
4   2040-10-05    8   12
5   2040-10-06    9   13
6   2040-10-07    8   12
7   2040-10-08    8   11
8   2040-10-09    8   13
9   2040-10-10    8   14
10  2040-10-11    8   10
11  2040-10-12    8   12
12  2040-10-13    8   13
13  2040-10-14    8   13

In [12]:
df.to_csv("commsdata.csv",index=False)

In [13]:
df['source_entity'].value_counts(ascending=False)
df['target_entity'].value_counts(ascending=False)

source_entity
Green Guardians         44
Oceanus City Council    37
Mako                    35
Neptune                 34
Reef Guardian           34
The Lookout             33
Himark Harbor           27
Davis                   25
Remora                  25
The Intern              24
Clepper Jensen          20
Mrs. Money              19
Miranda Jordan          18
Sentinel                18
Paackland Harbor        16
V. Miesel Shipping      15
Rodriguez               14
Horizon                 14
EcoVigil                14
The Middleman           13
Liam Thorne             11
Boss                     9
Samantha Blake           9
Nadia Conti              8
Serenity                 8
Haacklee Harbor          7
Marlin                   7
Small Fry                7
Osprey                   6
Elise                    5
Defender                 5
Northern Light           4
Glitters Team            4
Knowles                  4
Seawatch                 3
The Accountant           3
Sailor Shifts Team       2
Kelly                    2
Sam                      1
Name: count, dtype: int64

target_entity
Mako                    58
Oceanus City Council    45
Remora                  37
Reef Guardian           28
Green Guardians         27
Neptune                 26
Mrs. Money              24
Sentinel                23
Horizon                 22
Boss                    21
Miranda Jordan          20
Nadia Conti             18
V. Miesel Shipping      18
Clepper Jensen          18
The Intern              18
Himark Harbor           18
Davis                   18
Liam Thorne             16
Paackland Harbor        16
EcoVigil                15
Seawatch                12
Sam                     10
Serenity                 8
Sailor Shifts Team       8
Marlin                   8
The Lookout              8
Samantha Blake           7
The Middleman            7
Rodriguez                6
Elise                    6
Northern Light           4
Osprey                   3
The Accountant           3
Defender                 2
Haacklee Harbor          2
City Officials           1
Kelly                    1
Knowles                  1
Port Security            1
Name: count, dtype: int64

In [ ]:
df['date']=pd.to_datetime(df['date'])
df.loc[df['date']=='2040-10-01']

,source_entity,source_entity_action,content,timestamp,target_entity_action,target_entity,date,hour,minute,time,minutes_from_day_start,time_group,time_group_sortable
0,The Lookout,sent,"Hey The Intern, it's The Lookout! Just spotted...",2040-10-01 08:09:00,received,The Intern,2040-10-01,8,9,08:09:00,489,8.00am-8.15am,480
1,The Intern,sent,"Hey The Lookout, The Intern here! I'd absolute...",2040-10-01 08:10:00,received,The Lookout,2040-10-01,8,10,08:10:00,490,8.00am-8.15am,480
2,Kelly,sent,"Sam, it's Kelly! Let's meet at Sunrise Point a...",2040-10-01 08:13:00,received,Sam,2040-10-01,8,13,08:13:00,493,8.00am-8.15am,480
3,The Intern,sent,"Mrs. Money, it's The Intern. Just checking in ...",2040-10-01 08:16:00,received,Mrs. Money,2040-10-01,8,16,08:16:00,496,8.15am-8.30am,495
4,Mrs. Money,sent,"Boss, it's Mrs. Money. I've reviewed our opera...",2040-10-01 08:19:00,received,Boss,2040-10-01,8,19,08:19:00,499,8.15am-8.30am,495
5,Boss,sent,"Mrs. Money, this is Boss. I'm available tomorr...",2040-10-01 08:21:00,received,Mrs. Money,2040-10-01,8,21,08:21:00,501,8.15am-8.30am,495
6,Mrs. Money,sent,"Boss, Mrs. Money here. I'll bring the updated ...",2040-10-01 08:24:00,received,Boss,2040-10-01,8,24,08:24:00,504,8.15am-8.30am,495
7,Boss,sent,"Middleman, this is Boss. I'd like to move our ...",2040-10-01 08:26:00,received,The Middleman,2040-10-01,8,26,08:26:00,506,8.15am-8.30am,495
8,The Middleman,sent,"Boss, this is The Middleman. I can meet earlie...",2040-10-01 08:29:00,received,Boss,2040-10-01,8,29,08:29:00,509,8.15am-8.30am,495
9,Boss,sent,"Middleman, this is Boss. Let's meet tomorrow a...",2040-10-01 08:32:00,received,The Middleman,2040-10-01,8,32,08:32:00,512,8.30am-8.45am,510
10,The Middleman,sent,"Boss, this is Middleman. I'll be at the marina...",2040-10-01 08:34:00,received,Boss,2040-10-01,8,34,08:34:00,514,8.30am-8.45am,510
11,Serenity,sent,"Ahoy, this is the luxury yacht Serenity. I've ...",2040-10-01 08:50:00,received,Mako,2040-10-01,8,50,08:50:00,530,9.45am-9.00am,525
12,Mako,sent,"Serenity, this is Mako. For premium diving com...",2040-10-01 08:52:00,received,Serenity,2040-10-01,8,52,08:52:00,532,9.45am-9.00am,525
13,Serenity,sent,"Reef Guardian, this is Serenity. My owner is q...",2040-10-01 08:53:00,received,Reef Guardian,2040-10-01,8,53,08:53:00,533,9.45am-9.00am,525
14,Himark Harbor,sent,Harbor Master to Mako. Confirming your 07:00 d...,2040-10-01 08:59:00,received,Mako,2040-10-01,8,59,08:59:00,539,9.45am-9.00am,525
15,Davis,sent,"Davis, Mako here. Just completed documentation...",2040-10-01 09:02:00,received,Davis,2040-10-01,9,2,09:02:00,542,9.00am-9.15am,540
16,Boss,sent,"Mrs. Money, this is Boss. After speaking with ...",2040-10-01 09:49:00,received,Mrs. Money,2040-10-01,9,49,09:49:00,589,10.45am-10.00am,585
17,Mrs. Money,sent,"Middleman, it's Mrs. Money. I've prepared thos...",2040-10-01 09:52:00,received,The Middleman,2040-10-01,9,52,09:52:00,592,10.45am-10.00am,585
18,Reef Guardian,sent,"Serenity, Reef Guardian here. I understand you...",2040-10-01 09:55:00,received,Serenity,2040-10-01,9,55,09:55:00,595,10.45am-10.00am,585
19,Serenity,sent,"Himark Harbor, this is luxury yacht Serenity. ...",2040-10-01 09:58:00,received,Himark Harbor,2040-10-01,9,58,09:58:00,598,10.45am-10.00am,585
20,Himark Harbor,sent,Himark Harbor to Serenity. Premium berth confi...,2040-10-01 09:59:00,received,Serenity,2040-10-01,9,59,09:59:00,599,10.45am-10.00am,585
21,Paackland Harbor,sent,"Attention Remora, this is Paackland Harbor. We...",2040-10-01 10:43:00,received,Remora,2040-10-01,10,43,10:43:00,643,10.30am-10.45am,630
22,Remora,sent,"Paackland Harbor, this is Remora. Acknowledgin...",2040-10-01 10:46:00,received,Paackland Harbor,2040-10-01,10,46,10:46:00,646,11.45am-11.00am,645
23,Paackland Harbor,sent,This is Paackland Harbor to Oceanus City Counc...,2040-10-01 10:48:00,received,Oceanus City Council,2040-10-01,10,48,10:48:00,648,11.45am-11.00am,645
24,Oceanus City Council,sent,"Liam, this is Oceanus City Council. We've rece...",2040-10-01 10:51:00,received,Liam Thorne,2040-10-01,10,51,10:51:00,651,11.45am-11.00am,645
25,The Middleman,sent,"Mrs. Money, this is The Middleman. I can meet ...",2040-10-01 10:53:00,received,Mrs. Money,2040-10-01,10,53,10:53:00,653,11.45am-11.00am,645
26,The Middleman,sent,"The Middleman, it's Mrs. Money. 7PM at the caf...",2040-10-01 10:55:00,received,Mrs. Money,2040-10-01,10,55,10:55:00,655,11.45am-11.00am,645
27,Liam Thorne,sent,"Council, this is Liam Thorne. I've reviewed th...",2040-10-01 10:56:00,received,Oceanus City Council,2040-10-01,10,56,10:56:00,656,11.45am-11.00am,645
28,Oceanus City Council,sent,"Paackland Harbor, this is Oceanus City Council...",2040-10-01 10:58:00,received,Paackland Harbor,2040-10-01,10,58,10:58:00,658,11.45am-11.00am,645
29,Paackland Harbor,sent,"Reef Guardian, Paackland Harbor here. We're se...",2040-10-01 11:01:00,received,Reef Guardian,2040-10-01,11,1,11:01:00,661,11.00am-11.15am,660
30,Marlin,sent,"Himark Harbor, this is Marlin. Another day wit...",2040-10-01 11:02:00,received,Himark Harbor,2040-10-01,11,2,11:02:00,662,11.00am-11.15am,660
31,Himark Harbor,sent,Himark Harbor to Marlin. We understand your co...,2040-10-01 11:03:00,received,Marlin,2040-10-01,11,3,11:03:00,663,11.00am-11.15am,660
32,Marlin,sent,"Oceanus City Council, this is Marlin. These ne...",2040-10-01 11:06:00,received,Oceanus City Council,2040-10-01,11,6,11:06:00,666,11.00am-11.15am,660
33,Oceanus City Council,sent,"Marlin, this is Oceanus City Council. We hear ...",2040-10-01 11:09:00,received,Marlin,2040-10-01,11,9,11:09:00,669,11.00am-11.15am,660
34,Mako,sent,Mako to Remora. How's visibility in your secto...,2040-10-01 11:10:00,received,Remora,2040-10-01,11,10,11:10:00,670,11.00am-11.15am,660
35,Green Guardians,sent,"Reef Guardian, Green Guardians HQ here. We've ...",2040-10-01 11:40:00,received,Reef Guardian,2040-10-01,11,40,11:40:00,700,11.30am-11.45am,690
36,Samantha Blake,sent,"Hello Sailor Shifts Team, this is Samantha Bla...",2040-10-01 12:26:00,received,Sailor Shifts Team,2040-10-01,12,26,12:26:00,746,12.15pm-12.30pm,735
37,Glitters Team,sent,"Hi Samantha, Glitters Team here. We're confirm...",2040-10-01 12:27:00,received,Samantha Blake,2040-10-01,12,27,12:27:00,747,12.15pm-12.30pm,735
38,Samantha Blake,sent,"Hello Oceanus City Council, this is Samantha B...",2040-10-01 12:29:00,received,Oceanus City Council,2040-10-01,12,29,12:29:00,749,12.15pm-12.30pm,735
39,Sentinel,sent,"Green Guardians, this is Sentinel. While patro...",2040-10-01 12:34:00,received,Green Guardians,2040-10-01,12,34,12:34:00,754,12.30pm-12.45pm,750
40,Green Guardians,sent,"Horizon, Green Guardians HQ here. We're seeing...",2040-10-01 12:37:00,received,Horizon,2040-10-01,12,37,12:37:00,757,12.30pm-12.45pm,750
41,Horizon,sent,"Sentinel, this is Horizon. Received coordinate...",2040-10-01 12:39:00,received,Sentinel,2040-10-01,12,39,12:39:00,759,12.30pm-12.45pm,750
42,Sentinel,sent,"Horizon, this is Sentinel. Confirming western ...",2040-10-01 12:40:00,received,Horizon,2040-10-01,12,40,12:40:00,760,12.30pm-12.45pm,750
43,Green Guardians,sent,"Seawatch, Green Guardians HQ here. We need add...",2040-10-01 12:44:00,received,Seawatch,2040-10-01,12,44,12:44:00,764,12.30pm-12.45pm,750

In [29]:
df.loc[df['hour']>=14]

,source_entity,source_entity_action,content,timestamp,target_entity_action,target_entity,date,hour,minute,time,minutes_from_day_start,time_group,time_group_sortable
411,Reef Guardian,sent,"Seawatch, Reef Guardian here. Will commence ea...",2040-10-10 14:00:00,received,Seawatch,2040-10-10,14,0,14:00:00,840,2.00pm-2.15pm,840
412,The Lookout,sent,"Horizon, The Lookout here. Have started west q...",2040-10-10 14:03:00,received,Horizon,2040-10-10,14,3,14:03:00,843,2.00pm-2.15pm,840

In [25]:
df.dtypes

source_entity                     object
source_entity_action              object
content                           object
timestamp                 datetime64[ns]
target_entity_action              object
target_entity                     object
date                              object
hour                               int32
minute                             int32
time                              object
minutes_from_day_start             int64
time_group                        object
time_group_sortable                int64
dtype: object

In [16]:
df_cleaned=pd.read_csv("commsdata_cleaned.csv")

In [17]:
df_cleaned

,source_entity,source_entity_action,content,timestamp,target_entity_action,target_entity,date,hour,minute,time,minutes_from_day_start,time_group,time_group_sortable
0,The Lookout,sent,"Hey The Intern, it's The Lookout! Just spotted...",01/10/40 8:09,received,The Intern,01/10/40,8,9,8:09:00,489,8.00am-8.15am,480
1,The Intern,sent,"Hey The Lookout, The Intern here! I'd absolute...",01/10/40 8:10,received,The Lookout,01/10/40,8,10,8:10:00,490,8.00am-8.15am,480
2,Kelly,sent,"Sam, it's Kelly! Let's meet at Sunrise Point a...",01/10/40 8:13,received,Sam,01/10/40,8,13,8:13:00,493,8.00am-8.15am,480
3,The Intern,sent,"Mrs. Money, it's The Intern. Just checking in ...",01/10/40 8:16,received,Mrs. Money,01/10/40,8,16,8:16:00,496,8.15am-8.30am,495
4,Mrs. Money,sent,"Boss, it's Mrs. Money. I've reviewed our opera...",01/10/40 8:19,received,Boss,01/10/40,8,19,8:19:00,499,8.15am-8.30am,495
...,...,...,...,...,...,...,...,...,...,...,...,...,...
575,Oceanus City Council,sent,"Green Guardians, Oceanus City Council here. Yo...",14/10/40 12:50,received,Green Guardians,14/10/40,12,50,12:50:00,770,1.45pm-1.00pm,765
576,Green Guardians,sent,"EcoVigil, Green Guardians HQ here. Your video ...",14/10/40 12:51,received,EcoVigil,14/10/40,12,51,12:51:00,771,1.45pm-1.00pm,765
577,Defender,sent,Defender to Mako. Be advised that conservation...,14/10/40 13:31,received,Mako,14/10/40,13,31,13:31:00,811,1.30pm-1.45pm,810
578,Mako,sent,"Knowles, Mako here. Proceed to southern dock a...",14/10/40 13:34,received,Knowles,14/10/40,13,34,13:34:00,814,1.30pm-1.45pm,810
579,Knowles,sent,"Davis, this is Knowles. Approaching southern d...",14/10/40 13:35,received,Davis,14/10/40,13,35,13:35:00,815,1.30pm-1.45pm,810

In [3]:
def escape_cypher_identifier(identifier):
    """Escape a Cypher identifier by replacing special characters with underscores"""
    if not identifier:
        return "Node"
    # Replace spaces and special characters with underscores
    escaped = re.sub(r'[^a-zA-Z0-9_]', '_', str(identifier))
    # Ensure it starts with a letter or underscore
    if escaped and not escaped[0].isalpha() and escaped[0] != '_':
        pass
    # Ensure it's not empty
    if not escaped:
        escaped = "Node"
    return escaped

In [36]:
with open('MC3_schema.json', 'r', encoding='utf-8') as f:
    schema = json.load(f)
    schema=schema['schema']

In [37]:
with open('MC3_graph.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

In [39]:
entity_dict={}
for d in data['nodes']:
    if d['type']=='Entity':
        entity_dict[d['label']]=d['sub_type']

entity_dict

{'Sam': 'Person',
 'Kelly': 'Person',
 'Nadia Conti': 'Person',
 'Elise': 'Person',
 'Liam Thorne': 'Person',
 'Samantha Blake': 'Person',
 'Davis': 'Person',
 'Rodriguez': 'Person',
 'Sailor Shift': 'Person',
 'Clepper Jensen': 'Person',
 'Miranda Jordan': 'Person',
 'The Intern': 'Person',
 'The Lookout': 'Person',
 'The Accountant': 'Person',
 'Mrs. Money': 'Person',
 'The Middleman': 'Person',
 'Boss': 'Person',
 'Small Fry': 'Person',
 'Glitters Team': 'Organization',
 'Oceanus City Council': 'Organization',
 'Green Guardians': 'Organization',
 'V. Miesel Shipping': 'Organization',
 'Sailor Shifts Team': 'Organization',
 'Neptune': 'Vessel',
 'Marlin': 'Vessel',
 'Serenity': 'Vessel',
 'Mako': 'Vessel',
 'Reef Guardian': 'Vessel',
 'Horizon': 'Vessel',
 'Seawatch': 'Vessel',
 'EcoVigil': 'Vessel',
 'Sentinel': 'Vessel',
 'Osprey': 'Vessel',
 'Defender': 'Vessel',
 'Northern Light': 'Vessel',
 'Remora': 'Vessel',
 'Knowles': 'Vessel',
 "Mariner's Dream": 'Vessel',
 'Recreational Fishing Boats': 'Group',
 'City Officials': 'Group',
 'Diving Tour Operators': 'Group',
 'Tourists': 'Group',
 'Conservation Vessels': 'Group',
 'Paackland Harbor': 'Location',
 'Haacklee Harbor': 'Location',
 'Himark Harbor': 'Location',
 'Nemo Reef': 'Location',
 'Restricted areas': 'Location',
 'Azure Cove': 'Location',
 'Protected areas': 'Location',
 'Eastern reefs': 'Location',
 'Eastern Coastline': 'Location',
 'Southern islands': 'Location',
 'Southern coastline': 'Location',
 'Coral Point': 'Location',
 'Dolphin Bay': 'Location',
 'E7': 'Location',
 'Northern quadrant': 'Location',
 'Southern quadrant': 'Location',
 'Eastern quadrant': 'Location',
 'Western quadrant': 'Location',
 'Eastern Islands': 'Location',
 'Western Boundary': 'Location',
 'Eastern Boundary': 'Location',
 'Southern Boundary': 'Location',
 'Eastern Shoals': 'Location',
 'Restricted Zone': 'Location',
 'Route C': 'Location',
 'South Dock': 'Location',
 'Castaway Cove': 'Location',
 'Berth 14': 'Location',
 'Port Security': 'Location'}

In [41]:
df_cleaned['source_entity_type']=df_cleaned['source_entity'].map(entity_dict)
df_cleaned['target_entity_type']=df_cleaned['target_entity'].map(entity_dict)
df_cleaned['source_entity_type'].value_counts()
df_cleaned['target_entity_type'].value_counts()

source_entity_type
Vessel          247
Person          194
Organization     79
Location         60
Name: count, dtype: int64

target_entity_type
Vessel          241
Person          204
Organization     99
Location         36
Name: count, dtype: int64

In [48]:
df_cleaned.loc[:,['source_entity','source_entity_type','content','timestamp','target_entity','target_entity_type']].sample(5)

,source_entity,source_entity_type,content,timestamp,target_entity,target_entity_type
425,EcoVigil,Vessel,"Liam, this is EcoVigil. Per Council approval, ...",11/10/40 9:04,Liam Thorne,Person
472,Remora,Vessel,"Mako, Remora here. Stabilization equipment tes...",12/10/40 9:48,Mako,Vessel
447,Clepper Jensen,Person,"Miranda, Clepper here. Your discovery about fa...",11/10/40 10:16,Miranda Jordan,Person
27,Liam Thorne,Person,"Council, this is Liam Thorne. I've reviewed th...",01/10/40 10:56,Oceanus City Council,Organization
509,Remora,Vessel,"Davis, Remora here. Confirming night operation...",13/10/40 8:42,Davis,Person

In [53]:

df_cleaned['source']=df_cleaned['source_entity']
df_cleaned['target']=df_cleaned['target_entity']
df_cleaned=df_cleaned.drop(columns=['source_entity','target_entity'])
df_cleaned['timestamp'] = pd.to_datetime(df_cleaned['timestamp'])
df_cleaned['date'] = df_cleaned ['timestamp'].dt.date
df_cleaned['hour'] = df_cleaned['timestamp'].dt.hour
df_cleaned['time'] = df_cleaned['timestamp'].dt.time

# Calculate minutes since start of each day
df_cleaned['first_of_day'] = df_cleaned.groupby('date')['timestamp'].transform('min')
df_cleaned['mins_since_start_of_day'] = (df_cleaned['timestamp'] - df_cleaned['first_of_day']).dt.total_seconds() // 60
df_cleaned['mins_since_start_of_day'] = df_cleaned['mins_since_start_of_day'].astype(int)
df_cleaned = df_cleaned.drop(columns=['first_of_day'])

df_cleaned.head()

,source_entity_action,content,timestamp,target_entity_action,date,hour,minute,time,minutes_from_day_start,time_group,time_group_sortable,source_entity_type,target_entity_type,mins_since_start_of_day,source,target
0,sent,"Hey The Intern, it's The Lookout! Just spotted...",2040-01-10 08:09:00,received,2040-01-10,8,9,08:09:00,489,8.00am-8.15am,480,Person,Person,0,The Lookout,The Intern
1,sent,"Hey The Lookout, The Intern here! I'd absolute...",2040-01-10 08:10:00,received,2040-01-10,8,10,08:10:00,490,8.00am-8.15am,480,Person,Person,1,The Intern,The Lookout
2,sent,"Sam, it's Kelly! Let's meet at Sunrise Point a...",2040-01-10 08:13:00,received,2040-01-10,8,13,08:13:00,493,8.00am-8.15am,480,Person,Person,4,Kelly,Sam
3,sent,"Mrs. Money, it's The Intern. Just checking in ...",2040-01-10 08:16:00,received,2040-01-10,8,16,08:16:00,496,8.15am-8.30am,495,Person,Person,7,The Intern,Mrs. Money
4,sent,"Boss, it's Mrs. Money. I've reviewed our opera...",2040-01-10 08:19:00,received,2040-01-10,8,19,08:19:00,499,8.15am-8.30am,495,Person,Person,10,Mrs. Money,Boss

In [55]:
df_cleaned.head()

,source_entity_action,content,timestamp,target_entity_action,date,hour,minute,time,minutes_from_day_start,time_group,time_group_sortable,source_entity_type,target_entity_type,mins_since_start_of_day,source,target
0,sent,"Hey The Intern, it's The Lookout! Just spotted...",2040-01-10 08:09:00,received,2040-01-10,8,9,08:09:00,489,8.00am-8.15am,480,Person,Person,0,The Lookout,The Intern
1,sent,"Hey The Lookout, The Intern here! I'd absolute...",2040-01-10 08:10:00,received,2040-01-10,8,10,08:10:00,490,8.00am-8.15am,480,Person,Person,1,The Intern,The Lookout
2,sent,"Sam, it's Kelly! Let's meet at Sunrise Point a...",2040-01-10 08:13:00,received,2040-01-10,8,13,08:13:00,493,8.00am-8.15am,480,Person,Person,4,Kelly,Sam
3,sent,"Mrs. Money, it's The Intern. Just checking in ...",2040-01-10 08:16:00,received,2040-01-10,8,16,08:16:00,496,8.15am-8.30am,495,Person,Person,7,The Intern,Mrs. Money
4,sent,"Boss, it's Mrs. Money. I've reviewed our opera...",2040-01-10 08:19:00,received,2040-01-10,8,19,08:19:00,499,8.15am-8.30am,495,Person,Person,10,Mrs. Money,Boss

In [54]:
df_cleaned.to_csv("MC3_comms_cleaned.csv",index=False)

In [38]:
entities=[d['label'] for d in data['nodes'] if d['type']=='Entity']

relationship_values=[d['label'] for d in data['nodes'] if d['type']=='Relationship']
event_values=[d['label'] for d in data['nodes'] if d['type']=='Event']
len(entities),len(relationship_values),len(event_values)

(72, 285, 802)

In [7]:
# --- Convert nodes ---
nodes_by_label = {}
node_type_schema = schema['nodes']
nodes_by_id = {}

In [8]:
list(node_type_schema.keys())

['Entity', 'Event', 'Relationship']

In [9]:
for node_key in list(node_type_schema.keys()):
    print(node_type_schema[node_key].keys())

dict_keys(['common_attributes', 'sub_types'])
dict_keys(['common_attributes', 'sub_types'])
dict_keys(['common_attributes', 'sub_types'])

In [10]:
def enrich_with_schema(obj, common_attrs, specific_attrs, obj_type, obj_id, context):
    enriched = dict(obj)
    # Add missing common attributes
    for k, v in common_attrs.items():
        if k not in enriched:
            enriched[k] = None
            #print(f"[WARN] {context} {obj_type} {obj_id} missing common attribute '{k}', set to None", file=sys.stderr)
    # Add missing specific attributes
    for k, v in specific_attrs.items():
        if k not in enriched:
            enriched[k] = None
            #print(f"[WARN] {context} {obj_type} {obj_id} missing specific attribute '{k}', set to None", file=sys.stderr)
    return enriched

In [11]:
for node in data['nodes']:
    node_label = node.get('label')
    node_type = node.get('type')
    node_sub_type=node.get('sub_type')
    node_name=node.get("name")
    node_copy = dict(node)
    # Use escaped ID as _uid to prevent Cypher syntax errors
    node_copy['id'] = escape_cypher_identifier(node['id'])
    nodes_by_id[node['id']] = node_copy
    # Schema enrichment with common and specific attributes
    if node_type in node_type_schema:
        type_info = node_type_schema[node_type]
        common_attrs = type_info.get('common_attributes', {})
        specific_attrs = {}
        if node_sub_type and 'sub_types' in type_info and node_sub_type in type_info['sub_types']:
                specific_attrs = type_info['sub_types'][node_sub_type].get('specific_attributes', {})
        node_copy = enrich_with_schema(node_copy, common_attrs, specific_attrs, node_label, node['id'], 'Node')
    else:
        pass
        #print(f"[WARN] Node type '{node_type}' not found in schema for node id {node['id']}", file=sys.stderr)
    nodes_by_label.setdefault(node_label, []).append(node_copy)

In [12]:
len(nodes_by_label.keys())

92

In [13]:
nodes_by_label.keys()

dict_keys(['Sam', 'Kelly', 'Nadia Conti', 'Elise', 'Liam Thorne', 'Samantha Blake', 'Davis', 'Rodriguez', 'Sailor Shift', 'Clepper Jensen', 'Miranda Jordan', 'The Intern', 'The Lookout', 'The Accountant', 'Mrs. Money', 'The Middleman', 'Boss', 'Small Fry', 'Glitters Team', 'Oceanus City Council', 'Green Guardians', 'V. Miesel Shipping', 'Sailor Shifts Team', 'Neptune', 'Marlin', 'Serenity', 'Mako', 'Reef Guardian', 'Horizon', 'Seawatch', 'EcoVigil', 'Sentinel', 'Osprey', 'Defender', 'Northern Light', 'Remora', 'Knowles', "Mariner's Dream", 'Recreational Fishing Boats', 'City Officials', 'Diving Tour Operators', 'Tourists', 'Conservation Vessels', 'Paackland Harbor', 'Haacklee Harbor', 'Himark Harbor', 'Nemo Reef', 'Restricted areas', 'Azure Cove', 'Protected areas', 'Eastern reefs', 'Eastern Coastline', 'Southern islands', 'Southern coastline', 'Coral Point', 'Dolphin Bay', 'E7', 'Northern quadrant', 'Southern quadrant', 'Eastern quadrant', 'Western quadrant', 'Eastern Islands', 'Western Boundary', 'Eastern Boundary', 'Southern Boundary', 'Eastern Shoals', 'Restricted Zone', 'Route C', 'South Dock', 'Castaway Cove', 'Berth 14', 'Port Security', 'Monitoring', 'Communication', 'Assessment', 'VesselMovement', 'Enforcement', 'TourActivity', 'Fishing', 'Criticize', 'Collaborate', 'HarborReport', 'TransponderPing', 'Friends', 'Colleagues', 'AccessPermission', 'Reports', 'Jurisdiction', 'Coordinates', 'Operates', 'Suspicious', 'Unfriendly'])

In [14]:
def upload_nodes_simple(nodes_data, driver):
    """Upload nodes using simple Cypher syntax"""
    # Create node label from type and sub_type
    try:
        node_type = nodes_data.get('type', 'Node')
        sub_type = nodes_data.get('sub_type', '')
        label = nodes_data.get('label')
        escaped_label = escape_cypher_identifier(label)
        
        # Create properties dict, excluding internal fields
        properties = {}

        for key, value in nodes_data.items():
            properties[key] = value
        
        # for key, value in nodes_data.items():
        #     # Convert dict or list of dicts to JSON string
        #     if isinstance(value, dict) or (isinstance(value, list) and any(isinstance(i, dict) for i in value)):
        #         properties[key] = json.dumps(value)
        #     else:
        #         properties[key] = value
            
        # Add _uid for identification
        properties['id'] = escape_cypher_identifier(nodes_data['id'])
    
        
        # Create Cypher query
        query = f"""
        MERGE (n:{escaped_label} {{id: $uid}})
        SET n += $properties
        RETURN n
        """
        
        driver.execute_query(query, uid=properties['id'], properties=properties)

    except Exception as ex:
        print(ex)

In [15]:
def convert_nodes_fixed(nodes: dict) -> tuple[str, dict]:
    """Fixed version of convert_nodes that properly escapes identifiers"""
    query = ""
    new_nodes = {}
    
    for node_label, node_data in nodes.items():
        # Escape the node label for safe use in Cypher
        escaped_label = escape_cypher_identifier(node_label)
        # Create a safe parameter key
        param_key = f"{escaped_label}"
        query += f"""CALL apoc.create.nodes(["{escaped_label}"], ${param_key});"""
        # Update the nodes dict with the new key
        new_nodes[param_key] = node_data
    
    return query, new_nodes

In [16]:
driver = GraphDatabase.driver(uri, auth=(username, password))
driver.verify_connectivity()
print("Connected to Neo4j successfully!")

Connected to Neo4j successfully!

In [17]:
# d1=data['nodes'][:10]

In [18]:
nodes_by_id['Event_Assessment_14']

{'type': 'Event',
 'sub_type': 'Assessment',
 'label': 'Assessment',
 'timestamp': '2040-10-01 08:52:00',
 'assessment_type': 'documentation',
 'results': 'excellent conditions at Azure Cove',
 'id': 'Event_Assessment_14'}

In [19]:
# d=list(np.random.choice(data['nodes'],50,replace=False))

In [20]:
for k in (nodes_by_id.keys()):
    if nodes_by_id[k]['id']=='Event_TourActivity_137':
        nodes_data=nodes_by_id[k]
        upload_nodes_simple(nodes_data,driver)

In [21]:
edges = data.get('edges')

In [22]:
len(edges)

3226

In [23]:
if edges is None:
    for k, v in data.items():
        if k not in ('nodes', 'graph', 'directed', 'multigraph') and isinstance(v, list):
            edges = v
            break
    if edges is None:
        raise ValueError('Could not find edges/links in the JSON file.')

In [24]:
len(edges)

3226

In [25]:
rels_missing=[]
rels_missing_dict={"Event-Entity":"received","Entity-Relationship":"source","Entity-Event":"sent","Relationship-Entity":"target"}

In [26]:
def get_exact_relationship_type(edge, nodes_by_id, edge_types_schema):
    source_id = edge.get('source')
    target_id = edge.get('target')
    edge_type = edge.get('type',{})
    # Get source and target node types

    source_type = nodes_by_id.get(source_id, {}).get('type')
    target_type = nodes_by_id.get(target_id, {}).get('type')
    if edge_type=={}:
        #print(source_type,target_type,source_id,target_id)
        #rels_missing.append(source_type+"-"+target_type)
        edge_type=rels_missing_dict[source_type+"-"+target_type]
        edge['type']=edge_type

    # Try to match in schema
    for entry in edge_types_schema:
        if (
            entry.get('source') == source_type and
            entry.get('target') == target_type and
            (('type' not in entry and not edge_type) or (entry.get('type') == edge_type))
        ):
            return entry.get('type', edge_type or 'evidence_for')

In [27]:
rels_by_type = {}
rel_type_schema = schema['nodes'].get('Relationship', {}).get('sub_types', {})
edge_types_schema = schema.get('edges', {}).get('types', [])
for edge in edges:
    # Determine exact relationship type from schema
    rel_type = get_exact_relationship_type(edge, nodes_by_id, edge_types_schema)
    edge_copy = dict(edge)
    # Use escaped IDs for _from_uid and _to_uid to prevent Cypher syntax errors
    edge_copy['source'] = escape_cypher_identifier(edge['source'])
    edge_copy['target'] = escape_cypher_identifier(edge['target'])
    # Create a safe _uid for the relationship
    edge_id = edge.get('id', f"{edge['source']}_{rel_type}_{edge['target']}")
    edge_copy['id'] = escape_cypher_identifier(edge_id)
    # Schema enrichment for relationships (if type matches schema)
    if rel_type in rel_type_schema:
        common_attrs = schema['nodes']['Relationship'].get('common_attributes', {})
        specific_attrs = rel_type_schema[rel_type].get('specific_attributes', {})
        edge_copy = enrich_with_schema(edge_copy, common_attrs, specific_attrs, rel_type, edge_copy['_uid'], 'Edge')
    else:
        pass
        #print(f"[WARN] Edge type '{rel_type}' not found in schema for edge id {edge_copy['_uid']}", file=sys.stderr)
    rels_by_type.setdefault(rel_type, []).append(edge_copy)

In [30]:
# print(f"Uploading {len(rels_by_type)} relationships...")
success_count = 0
error_count = 0
for k in rels_by_type.keys():
    rel=rels_by_type[k]
    for r in rel:
        from_uid = escape_cypher_identifier(r['source'])
        to_uid = escape_cypher_identifier(r['target'])
        escaped_rel_type=r['type']
        properties = {}

        for key, value in r.items():
            properties[key] = value

            
        # for key, value in r.items():
        #     #if key not in ['source', 'target', 'type', 'id','_uid','is_inferred','_to_uid','_from_uid']:
        #     if key not in []:
        #         # Convert dict or list of dicts to JSON string
        #         if isinstance(value, dict) or (isinstance(value, list) and any(isinstance(i, dict) for i in value)):
        #             properties[key] = json.dumps(value)
        #         else:
                    #properties[key] = value
        
        query = f"""
            MATCH (a {{id: $from_uid}})
            MATCH (b {{id: $to_uid}})
            MERGE (a)-[r:{escaped_rel_type}]->(b)
            SET r += $properties
            RETURN r
            """

        driver.execute_query(query, from_uid=from_uid, to_uid=to_uid, properties=properties)
        success_count += 1

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243684' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2276' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2348' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '2', 'source': 'Sam', 'type': 'source', 'target': 'Relationship_Suspicious_217'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155181001001928932' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2276' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:940' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '3013', 'source': 'Sam', 'type': 'source', 'target': 'Relationship_Colleagues_430'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477208' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2276' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:920' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Sam_source_Relationship_Friends_272', 'source': 'Sam', 'type': 'source', 'target': 'Relationship_Friends_272'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0970>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477221' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2276' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:933' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Sam_source_Relationship_Colleagues_215', 'source': 'Sam', 'type': 'source', 'target': 'Relationship_Colleagues_215'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477229' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2276' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:941' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Sam_source_Relationship_Colleagues_431', 'source': 'Sam', 'type': 'source', 'target': 'Relationship_Colleagues_431'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f6a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243685' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2277' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:920' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Kelly_source_Relationship_Friends_272', 'source': 'Kelly', 'type': 'source', 'target': 'Relationship_Friends_272'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155181001001928933' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2277' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:933' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Kelly_source_Relationship_Colleagues_215', 'source': 'Kelly', 'type': 'source', 'target': 'Relationship_Colleagues_215'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8b80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243686' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:969' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '14', 'source': 'Nadia_Conti', 'type': 'source', 'target': 'Relationship_AccessPermission_181'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fa00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477225' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:937' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '3485', 'source': 'Nadia_Conti', 'type': 'source', 'target': 'Relationship_Colleagues_321'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477400' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1112' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '22', 'source': 'Nadia_Conti', 'type': 'source', 'target': 'Relationship_Coordinates_493'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8d90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477230' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:942' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '3604', 'source': 'Nadia_Conti', 'type': 'source', 'target': 'Relationship_Colleagues_494'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb00a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155181001001928934' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:941' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Nadia_Conti_source_Relationship_Colleagues_431', 'source': 'Nadia_Conti', 'type': 'source', 'target': 'Relationship_Colleagues_431'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71f40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477233' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:945' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Nadia_Conti_source_Relationship_Colleagues_551', 'source': 'Nadia_Conti', 'type': 'source', 'target': 'Relationship_Colleagues_551'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477226' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:938' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Nadia_Conti_source_Relationship_Colleagues_322', 'source': 'Nadia_Conti', 'type': 'source', 'target': 'Relationship_Colleagues_322'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc32b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477223' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:935' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Nadia_Conti_source_Relationship_Colleagues_319', 'source': 'Nadia_Conti', 'type': 'source', 'target': 'Relationship_Colleagues_319'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3e80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243687' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2279' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2354' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '30', 'source': 'Elise', 'type': 'source', 'target': 'Relationship_Suspicious_360'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155181001001928935' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2279' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1105' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '33', 'source': 'Elise', 'type': 'source', 'target': 'Relationship_Coordinates_428'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477228' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2279' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:940' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '3486', 'source': 'Elise', 'type': 'source', 'target': 'Relationship_Colleagues_430'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157432800815614183' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2279' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:937' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '3046', 'source': 'Elise', 'type': 'source', 'target': 'Relationship_Colleagues_321'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477224' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2279' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:936' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Elise_source_Relationship_Colleagues_320', 'source': 'Elise', 'type': 'source', 'target': 'Relationship_Colleagues_320'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f970>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243688' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1059' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '42', 'source': 'Liam_Thorne', 'type': 'source', 'target': 'Relationship_Coordinates_24'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477360' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1072' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '44', 'source': 'Liam_Thorne', 'type': 'source', 'target': 'Relationship_Coordinates_172'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf2b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477274' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:986' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '49', 'source': 'Liam_Thorne', 'type': 'source', 'target': 'Relationship_AccessPermission_313'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcff40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222478640' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2352' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '54', 'source': 'Liam_Thorne', 'type': 'source', 'target': 'Relationship_Suspicious_317'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477392' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1104' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '59', 'source': 'Liam_Thorne', 'type': 'source', 'target': 'Relationship_Coordinates_423'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222478646' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2358' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '61', 'source': 'Liam_Thorne', 'type': 'source', 'target': 'Relationship_Suspicious_436'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcfd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477395' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1107' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '63', 'source': 'Liam_Thorne', 'type': 'source', 'target': 'Relationship_Coordinates_445'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9c10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477329' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1041' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '52', 'source': 'Liam_Thorne', 'type': 'source', 'target': 'Relationship_Reports_587'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155181001001928936' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:942' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '3734', 'source': 'Liam_Thorne', 'type': 'source', 'target': 'Relationship_Colleagues_494'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477219' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:931' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Liam_Thorne_source_Relationship_Colleagues_121', 'source': 'Liam_Thorne', 'type': 'source', 'target': 'Relationship_Colleagues_121'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6d60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243689' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2281' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1061' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '74', 'source': 'Samantha_Blake', 'type': 'source', 'target': 'Relationship_Coordinates_30'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6d90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477363' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2281' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1075' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '81', 'source': 'Samantha_Blake', 'type': 'source', 'target': 'Relationship_Coordinates_226'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222478654' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2281' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2366' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '84', 'source': 'Samantha_Blake', 'type': 'source', 'target': 'Relationship_Unfriendly_229'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b2b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477285' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2281' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:997' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '87', 'source': 'Samantha_Blake', 'type': 'source', 'target': 'Relationship_AccessPermission_415'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477445' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2281' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '92', 'source': 'Samantha_Blake', 'type': 'source', 'target': 'Relationship_Operates_459'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f4f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477447' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2281' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '93', 'source': 'Samantha_Blake', 'type': 'source', 'target': 'Relationship_Operates_463'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243690' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1133' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '120', 'source': 'Davis', 'type': 'source', 'target': 'Relationship_Operates_58'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff7f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155181001001928938' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1135' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '99', 'source': 'Davis', 'type': 'source', 'target': 'Relationship_Operates_65'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddfaf0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477255' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:967' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '104', 'source': 'Davis', 'type': 'source', 'target': 'Relationship_AccessPermission_161'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddfeb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477441' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1153' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '126', 'source': 'Davis', 'type': 'source', 'target': 'Relationship_Operates_351'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc38e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477442' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1154' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '128', 'source': 'Davis', 'type': 'source', 'target': 'Relationship_Operates_352'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ffc70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477296' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1008' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '135', 'source': 'Davis', 'type': 'source', 'target': 'Relationship_AccessPermission_511'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477456' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1168' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '142', 'source': 'Davis', 'type': 'source', 'target': 'Relationship_Operates_543'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bc70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477457' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1169' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '103', 'source': 'Davis', 'type': 'source', 'target': 'Relationship_Operates_546'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477301' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1013' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '150', 'source': 'Davis', 'type': 'source', 'target': 'Relationship_AccessPermission_564'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcfcd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222478651' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2363' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '152', 'source': 'Davis', 'type': 'source', 'target': 'Relationship_Suspicious_577'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc39d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477238' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:950' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '3760', 'source': 'Davis', 'type': 'source', 'target': 'Relationship_Colleagues_619'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf4c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157432800815614186' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:945' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Davis_source_Relationship_Colleagues_551', 'source': 'Davis', 'type': 'source', 'target': 'Relationship_Colleagues_551'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477213' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:925' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Davis_source_Relationship_Colleagues_45', 'source': 'Davis', 'type': 'source', 'target': 'Relationship_Colleagues_45'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf6d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477232' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:944' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Davis_source_Relationship_Colleagues_536', 'source': 'Davis', 'type': 'source', 'target': 'Relationship_Colleagues_536'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477237' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:949' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Davis_source_Relationship_Colleagues_617', 'source': 'Davis', 'type': 'source', 'target': 'Relationship_Colleagues_617'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477214' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:926' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Davis_source_Relationship_Colleagues_66', 'source': 'Davis', 'type': 'source', 'target': 'Relationship_Colleagues_66'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddfee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477239' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:951' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Davis_source_Relationship_Colleagues_628', 'source': 'Davis', 'type': 'source', 'target': 'Relationship_Colleagues_628'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243691' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1136' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '162', 'source': 'Rodriguez', 'type': 'source', 'target': 'Relationship_Operates_75'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155181001001928939' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1181' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '170', 'source': 'Rodriguez', 'type': 'source', 'target': 'Relationship_Suspicious_113'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919788524036162690' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1154' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '178', 'source': 'Rodriguez', 'type': 'source', 'target': 'Relationship_Operates_352'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477449' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1161' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '175', 'source': 'Rodriguez', 'type': 'source', 'target': 'Relationship_Operates_476'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477450' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1162' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '187', 'source': 'Rodriguez', 'type': 'source', 'target': 'Relationship_Operates_505'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919788524036162486' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:950' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '4255', 'source': 'Rodriguez', 'type': 'source', 'target': 'Relationship_Colleagues_619'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ffd90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477218' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:930' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Rodriguez_source_Relationship_Colleagues_102', 'source': 'Rodriguez', 'type': 'source', 'target': 'Relationship_Colleagues_102'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477212' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:924' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Rodriguez_source_Relationship_Colleagues_16', 'source': 'Rodriguez', 'type': 'source', 'target': 'Relationship_Colleagues_16'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf7f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477216' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:928' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Rodriguez_source_Relationship_Colleagues_83', 'source': 'Rodriguez', 'type': 'source', 'target': 'Relationship_Colleagues_83'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243692' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2284' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:925' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Sailor_Shift_source_Relationship_Colleagues_45', 'source': 'Sailor_Shift', 'type': 'source', 'target': 'Relationship_Colleagues_45'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243693' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1174' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '194', 'source': 'Clepper_Jensen', 'type': 'source', 'target': 'Relationship_Suspicious_71'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477464' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1176' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '208', 'source': 'Clepper_Jensen', 'type': 'source', 'target': 'Relationship_Suspicious_106'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf7f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477465' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1177' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '193', 'source': 'Clepper_Jensen', 'type': 'source', 'target': 'Relationship_Suspicious_107'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f9d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477466' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1178' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '202', 'source': 'Clepper_Jensen', 'type': 'source', 'target': 'Relationship_Suspicious_108'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477317' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1029' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '214', 'source': 'Clepper_Jensen', 'type': 'source', 'target': 'Relationship_Reports_218'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222478650' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2362' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '233', 'source': 'Clepper_Jensen', 'type': 'source', 'target': 'Relationship_Suspicious_485'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc84f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477222' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:934' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Clepper_Jensen_source_Relationship_Colleagues_290', 'source': 'Clepper_Jensen', 'type': 'source', 'target': 'Relationship_Colleagues_290'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690ffa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243694' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1025' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '239', 'source': 'Miranda_Jordan', 'type': 'source', 'target': 'Relationship_Reports_69'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8dc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477314' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1026' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '242', 'source': 'Miranda_Jordan', 'type': 'source', 'target': 'Relationship_Reports_73'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd69d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477463' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1175' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '243', 'source': 'Miranda_Jordan', 'type': 'source', 'target': 'Relationship_Suspicious_74'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477467' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1179' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '245', 'source': 'Miranda_Jordan', 'type': 'source', 'target': 'Relationship_Suspicious_110'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f280>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477316' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1028' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '251', 'source': 'Miranda_Jordan', 'type': 'source', 'target': 'Relationship_Reports_205'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce94c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477318' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1030' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '258', 'source': 'Miranda_Jordan', 'type': 'source', 'target': 'Relationship_Reports_288'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3bb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222478649' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2361' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '263', 'source': 'Miranda_Jordan', 'type': 'source', 'target': 'Relationship_Suspicious_483'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcfaf0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155181001001928942' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2362' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '265', 'source': 'Miranda_Jordan', 'type': 'source', 'target': 'Relationship_Suspicious_485'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157432800815614190' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:934' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Miranda_Jordan_source_Relationship_Colleagues_290', 'source': 'Miranda_Jordan', 'type': 'source', 'target': 'Relationship_Colleagues_290'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243695' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1022' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '285', 'source': 'The_Intern', 'type': 'source', 'target': 'Relationship_Reports_41'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155181001001928943' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:929' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1956', 'source': 'The_Intern', 'type': 'source', 'target': 'Relationship_Colleagues_84'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc39a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477372' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1084' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '288', 'source': 'The_Intern', 'type': 'source', 'target': 'Relationship_Coordinates_274'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477287' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:999' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '298', 'source': 'The_Intern', 'type': 'source', 'target': 'Relationship_AccessPermission_425'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222478645' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2357' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '299', 'source': 'The_Intern', 'type': 'source', 'target': 'Relationship_Suspicious_426'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc30a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477444' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1156' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '312', 'source': 'The_Intern', 'type': 'source', 'target': 'Relationship_Operates_439'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477234' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:946' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '4089', 'source': 'The_Intern', 'type': 'source', 'target': 'Relationship_Colleagues_589'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477207' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:919' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'The_Intern_source_Relationship_Friends_0', 'source': 'The_Intern', 'type': 'source', 'target': 'Relationship_Friends_0'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcfaf0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243696' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2349' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '338', 'source': 'The_Lookout', 'type': 'source', 'target': 'Relationship_Suspicious_219'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477320' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1032' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '351', 'source': 'The_Lookout', 'type': 'source', 'target': 'Relationship_Reports_355'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919788524036162455' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:919' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'The_Lookout_source_Relationship_Friends_0', 'source': 'The_Lookout', 'type': 'source', 'target': 'Relationship_Friends_0'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157432800815614192' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:946' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '4126', 'source': 'The_Lookout', 'type': 'source', 'target': 'Relationship_Colleagues_589'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dee2e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243697' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2289' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1119' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '381', 'source': 'The_Accountant', 'type': 'source', 'target': 'Relationship_Coordinates_550'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de83d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222478652' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2289' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2364' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '379', 'source': 'The_Accountant', 'type': 'source', 'target': 'Relationship_Suspicious_600'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477236' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2289' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:948' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '4163', 'source': 'The_Accountant', 'type': 'source', 'target': 'Relationship_Colleagues_601'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0040>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155181001001928945' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2289' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:938' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'The_Accountant_source_Relationship_Colleagues_322', 'source': 'The_Accountant', 'type': 'source', 'target': 'Relationship_Colleagues_322'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477235' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2289' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:947' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'The_Accountant_source_Relationship_Colleagues_599', 'source': 'The_Accountant', 'type': 'source', 'target': 'Relationship_Colleagues_599'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243698' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:921' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1707', 'source': 'Mrs__Money', 'type': 'source', 'target': 'Relationship_Colleagues_2'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dee280>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155181001001928946' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1142' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '402', 'source': 'Mrs__Money', 'type': 'source', 'target': 'Relationship_Operates_154'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dee940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477254' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:966' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '403', 'source': 'Mrs__Money', 'type': 'source', 'target': 'Relationship_AccessPermission_156'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690ffa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477220' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:932' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '2351', 'source': 'Mrs__Money', 'type': 'source', 'target': 'Relationship_Colleagues_158'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477435' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1147' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '407', 'source': 'Mrs__Money', 'type': 'source', 'target': 'Relationship_Operates_211'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126deebb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477439' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1151' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '400', 'source': 'Mrs__Money', 'type': 'source', 'target': 'Relationship_Operates_283'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bcd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157432800815614194' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:999' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '417', 'source': 'Mrs__Money', 'type': 'source', 'target': 'Relationship_AccessPermission_425'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8cd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159684600629299442' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2357' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '418', 'source': 'Mrs__Money', 'type': 'source', 'target': 'Relationship_Suspicious_426'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919788524036162692' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1156' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '420', 'source': 'Mrs__Money', 'type': 'source', 'target': 'Relationship_Operates_439'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1161936400442984690' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:929' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '2055', 'source': 'Mrs__Money', 'type': 'source', 'target': 'Relationship_Colleagues_84'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dee940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243699' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:922' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1677', 'source': 'The_Middleman', 'type': 'source', 'target': 'Relationship_Colleagues_11'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f1f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477394' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1106' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '438', 'source': 'The_Middleman', 'type': 'source', 'target': 'Relationship_Coordinates_437'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477323' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1035' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '440', 'source': 'The_Middleman', 'type': 'source', 'target': 'Relationship_Reports_496'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff9d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155181001001928947' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:948' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '4171', 'source': 'The_Middleman', 'type': 'source', 'target': 'Relationship_Colleagues_601'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd88e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157432800815614195' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:932' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '2364', 'source': 'The_Middleman', 'type': 'source', 'target': 'Relationship_Colleagues_158'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243700' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:958' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '461', 'source': 'Boss', 'type': 'source', 'target': 'Relationship_AccessPermission_101'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477429' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1141' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '460', 'source': 'Boss', 'type': 'source', 'target': 'Relationship_Operates_153'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126deef10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477472' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1184' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '466', 'source': 'Boss', 'type': 'source', 'target': 'Relationship_Suspicious_209'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3e20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477434' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1146' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '467', 'source': 'Boss', 'type': 'source', 'target': 'Relationship_Operates_210'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3d30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477461' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1173' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '469', 'source': 'Boss', 'type': 'source', 'target': 'Relationship_Operates_602'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919788524036162480' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:944' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Boss_source_Relationship_Colleagues_536', 'source': 'Boss', 'type': 'source', 'target': 'Relationship_Colleagues_536'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff7f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157432800815614196' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:930' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Boss_source_Relationship_Colleagues_102', 'source': 'Boss', 'type': 'source', 'target': 'Relationship_Colleagues_102'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159684600629299444' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:947' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Boss_source_Relationship_Colleagues_599', 'source': 'Boss', 'type': 'source', 'target': 'Relationship_Colleagues_599'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0e50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1161936400442984692' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:921' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1672', 'source': 'Boss', 'type': 'source', 'target': 'Relationship_Colleagues_2'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dee280>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1164188200256669940' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:922' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1708', 'source': 'Boss', 'type': 'source', 'target': 'Relationship_Colleagues_11'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bc70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477231' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:943' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Boss_source_Relationship_Colleagues_535', 'source': 'Boss', 'type': 'source', 'target': 'Relationship_Colleagues_535'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc36a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243701' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2293' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:983' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '475', 'source': 'Small_Fry', 'type': 'source', 'target': 'Relationship_AccessPermission_303'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477272' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2293' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:984' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '476', 'source': 'Small_Fry', 'type': 'source', 'target': 'Relationship_AccessPermission_304'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477451' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2293' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1163' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '478', 'source': 'Small_Fry', 'type': 'source', 'target': 'Relationship_Operates_506'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce96a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477327' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2293' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1039' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '482', 'source': 'Small_Fry', 'type': 'source', 'target': 'Relationship_Reports_537'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd65b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477416' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2293' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1128' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '486', 'source': 'Small_Fry', 'type': 'source', 'target': 'Relationship_Coordinates_618'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919788524036162485' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2293' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:949' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Small_Fry_source_Relationship_Colleagues_617', 'source': 'Small_Fry', 'type': 'source', 'target': 'Relationship_Colleagues_617'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dee940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919788524036162479' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2293' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:943' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Small_Fry_source_Relationship_Colleagues_535', 'source': 'Small_Fry', 'type': 'source', 'target': 'Relationship_Colleagues_535'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477215' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2293' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:927' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Small_Fry_source_Relationship_Colleagues_80', 'source': 'Small_Fry', 'type': 'source', 'target': 'Relationship_Colleagues_80'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243702' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2294' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1069' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '491', 'source': 'Glitters_Team', 'type': 'source', 'target': 'Relationship_Coordinates_77'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf1f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477242' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2294' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:954' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '489', 'source': 'Glitters_Team', 'type': 'source', 'target': 'Relationship_AccessPermission_81'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126deec40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477365' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2294' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1077' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '495', 'source': 'Glitters_Team', 'type': 'source', 'target': 'Relationship_Coordinates_236'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8eb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477459' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2294' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1171' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '497', 'source': 'Glitters_Team', 'type': 'source', 'target': 'Relationship_Operates_592'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243703' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1058' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '499', 'source': 'Oceanus_City_Council', 'type': 'source', 'target': 'Relationship_Coordinates_20'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477334' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1046' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '500', 'source': 'Oceanus_City_Council', 'type': 'source', 'target': 'Relationship_Jurisdiction_21'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477348' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1060' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '585', 'source': 'Oceanus_City_Council', 'type': 'source', 'target': 'Relationship_Coordinates_27'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477359' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1071' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '526', 'source': 'Oceanus_City_Council', 'type': 'source', 'target': 'Relationship_Coordinates_120'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477361' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1073' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '539', 'source': 'Oceanus_City_Council', 'type': 'source', 'target': 'Relationship_Coordinates_185'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x103476c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477260' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:972' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '511', 'source': 'Oceanus_City_Council', 'type': 'source', 'target': 'Relationship_AccessPermission_196'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf4c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477433' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1145' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '548', 'source': 'Oceanus_City_Council', 'type': 'source', 'target': 'Relationship_Operates_202'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd63d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477440' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '562', 'source': 'Oceanus_City_Council', 'type': 'source', 'target': 'Relationship_Operates_327'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddfb80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477338' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1050' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '513', 'source': 'Oceanus_City_Council', 'type': 'source', 'target': 'Relationship_Jurisdiction_390'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10345ae80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477339' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '515', 'source': 'Oceanus_City_Council', 'type': 'source', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b5b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477396' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1108' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '583', 'source': 'Oceanus_City_Council', 'type': 'source', 'target': 'Relationship_Coordinates_448'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf0a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477340' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1052' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '587', 'source': 'Oceanus_City_Council', 'type': 'source', 'target': 'Relationship_Jurisdiction_454'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1035572b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477454' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1166' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '593', 'source': 'Oceanus_City_Council', 'type': 'source', 'target': 'Relationship_Operates_521'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10345ae80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477342' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1054' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '599', 'source': 'Oceanus_City_Council', 'type': 'source', 'target': 'Relationship_Jurisdiction_583'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477343' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1055' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '588', 'source': 'Oceanus_City_Council', 'type': 'source', 'target': 'Relationship_Jurisdiction_586'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6e80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222478657' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2369' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '595', 'source': 'Oceanus_City_Council', 'type': 'source', 'target': 'Relationship_Unfriendly_625'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155181001001928951' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:931' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Oceanus_City_Council_source_Relationship_Colleagues_121', 'source': 'Oceanus_City_Council', 'type': 'source', 'target': 'Relationship_Colleagues_121'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bd90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243704' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1047' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '608', 'source': 'Green_Guardians', 'type': 'source', 'target': 'Relationship_Jurisdiction_29'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477351' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1063' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '635', 'source': 'Green_Guardians', 'type': 'source', 'target': 'Relationship_Coordinates_35'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477420' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1132' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '735', 'source': 'Green_Guardians', 'type': 'source', 'target': 'Relationship_Operates_36'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd81f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477352' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1064' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '615', 'source': 'Green_Guardians', 'type': 'source', 'target': 'Relationship_Coordinates_37'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477355' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1067' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '709', 'source': 'Green_Guardians', 'type': 'source', 'target': 'Relationship_Coordinates_53'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6c10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477358' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1070' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '624', 'source': 'Green_Guardians', 'type': 'source', 'target': 'Relationship_Coordinates_116'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71f10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477336' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1048' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '654', 'source': 'Green_Guardians', 'type': 'source', 'target': 'Relationship_Jurisdiction_131'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc88b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477432' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1144' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '743', 'source': 'Green_Guardians', 'type': 'source', 'target': 'Relationship_Operates_176'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477362' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1074' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '669', 'source': 'Green_Guardians', 'type': 'source', 'target': 'Relationship_Coordinates_201'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf2b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477269' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:981' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '663', 'source': 'Green_Guardians', 'type': 'source', 'target': 'Relationship_AccessPermission_266'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71f10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477438' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1150' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '685', 'source': 'Green_Guardians', 'type': 'source', 'target': 'Relationship_Operates_271'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc36d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477375' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1087' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '688', 'source': 'Green_Guardians', 'type': 'source', 'target': 'Relationship_Coordinates_289'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cb0e50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222478641' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2353' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '691', 'source': 'Green_Guardians', 'type': 'source', 'target': 'Relationship_Suspicious_341'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b712e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477443' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '700', 'source': 'Green_Guardians', 'type': 'source', 'target': 'Relationship_Operates_367'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71f10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222478643' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2355' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '730', 'source': 'Green_Guardians', 'type': 'source', 'target': 'Relationship_Suspicious_368'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477292' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1004' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '717', 'source': 'Green_Guardians', 'type': 'source', 'target': 'Relationship_AccessPermission_479'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477399' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1111' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '724', 'source': 'Green_Guardians', 'type': 'source', 'target': 'Relationship_Coordinates_492'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477326' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1038' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '706', 'source': 'Green_Guardians', 'type': 'source', 'target': 'Relationship_Reports_529'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f5b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477458' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1170' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '713', 'source': 'Green_Guardians', 'type': 'source', 'target': 'Relationship_Operates_566'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf7c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222478656' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2368' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '741', 'source': 'Green_Guardians', 'type': 'source', 'target': 'Relationship_Unfriendly_567'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddfa90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477413' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1125' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '693', 'source': 'Green_Guardians', 'type': 'source', 'target': 'Relationship_Coordinates_609'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc84f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243705' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1139' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '750', 'source': 'V__Miesel_Shipping', 'type': 'source', 'target': 'Relationship_Operates_103'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc85e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477468' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1180' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '751', 'source': 'V__Miesel_Shipping', 'type': 'source', 'target': 'Relationship_Suspicious_112'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690ff10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477249' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:961' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '753', 'source': 'V__Miesel_Shipping', 'type': 'source', 'target': 'Relationship_AccessPermission_125'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0af0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477261' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:973' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '800', 'source': 'V__Miesel_Shipping', 'type': 'source', 'target': 'Relationship_AccessPermission_214'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd87c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477436' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1148' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '755', 'source': 'V__Miesel_Shipping', 'type': 'source', 'target': 'Relationship_Operates_255'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477437' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1149' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '764', 'source': 'V__Miesel_Shipping', 'type': 'source', 'target': 'Relationship_Operates_256'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3280>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477268' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:980' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '767', 'source': 'V__Miesel_Shipping', 'type': 'source', 'target': 'Relationship_AccessPermission_262'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034711c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477273' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:985' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '769', 'source': 'V__Miesel_Shipping', 'type': 'source', 'target': 'Relationship_AccessPermission_306'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f040>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222478655' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2367' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '771', 'source': 'V__Miesel_Shipping', 'type': 'source', 'target': 'Relationship_Unfriendly_312'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477397' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1109' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '761', 'source': 'V__Miesel_Shipping', 'type': 'source', 'target': 'Relationship_Coordinates_471'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb08b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477398' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1110' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '783', 'source': 'V__Miesel_Shipping', 'type': 'source', 'target': 'Relationship_Coordinates_473'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8a90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477448' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1160' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '778', 'source': 'V__Miesel_Shipping', 'type': 'source', 'target': 'Relationship_Operates_474'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477401' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1113' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '794', 'source': 'V__Miesel_Shipping', 'type': 'source', 'target': 'Relationship_Coordinates_499'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477452' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1164' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '773', 'source': 'V__Miesel_Shipping', 'type': 'source', 'target': 'Relationship_Operates_514'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243706' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2298' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1134' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '807', 'source': 'Sailor_Shifts_Team', 'type': 'source', 'target': 'Relationship_Operates_59'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477241' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2298' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:953' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '808', 'source': 'Sailor_Shifts_Team', 'type': 'source', 'target': 'Relationship_AccessPermission_68'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb07f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477426' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2298' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1138' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '809', 'source': 'Sailor_Shifts_Team', 'type': 'source', 'target': 'Relationship_Operates_97'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de81c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477379' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2298' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1091' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '811', 'source': 'Sailor_Shifts_Team', 'type': 'source', 'target': 'Relationship_Coordinates_302'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477460' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2298' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1172' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '814', 'source': 'Sailor_Shifts_Team', 'type': 'source', 'target': 'Relationship_Operates_593'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8eb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477306' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2298' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1018' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '813', 'source': 'Sailor_Shifts_Team', 'type': 'source', 'target': 'Relationship_AccessPermission_594'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb03a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919788524036162460' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2298' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:924' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Sailor_Shifts_Team_source_Relationship_Colleagues_16', 'source': 'Sailor_Shifts_Team', 'type': 'source', 'target': 'Relationship_Colleagues_16'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f8b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243707' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:978' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '906', 'source': 'Neptune', 'type': 'source', 'target': 'Relationship_AccessPermission_244'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce94c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477366' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1078' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '821', 'source': 'Neptune', 'type': 'source', 'target': 'Relationship_Coordinates_247'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0d90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477267' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:979' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '829', 'source': 'Neptune', 'type': 'source', 'target': 'Relationship_AccessPermission_259'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477270' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:982' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '855', 'source': 'Neptune', 'type': 'source', 'target': 'Relationship_AccessPermission_281'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fe80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477378' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1090' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '873', 'source': 'Neptune', 'type': 'source', 'target': 'Relationship_Coordinates_298'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477380' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1092' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '903', 'source': 'Neptune', 'type': 'source', 'target': 'Relationship_Coordinates_305'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477275' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:987' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '870', 'source': 'Neptune', 'type': 'source', 'target': 'Relationship_AccessPermission_328'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477284' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:996' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '872', 'source': 'Neptune', 'type': 'source', 'target': 'Relationship_AccessPermission_405'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x103471910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477324' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1036' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '882', 'source': 'Neptune', 'type': 'source', 'target': 'Relationship_Reports_513'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034710a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477405' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1117' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '900', 'source': 'Neptune', 'type': 'source', 'target': 'Relationship_Coordinates_518'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x102dc1c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155181001001928955' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:935' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Neptune_source_Relationship_Colleagues_319', 'source': 'Neptune', 'type': 'source', 'target': 'Relationship_Colleagues_319'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919788524036162472' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:936' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Neptune_source_Relationship_Colleagues_320', 'source': 'Neptune', 'type': 'source', 'target': 'Relationship_Colleagues_320'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243708' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2300' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1023' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '914', 'source': 'Marlin', 'type': 'source', 'target': 'Relationship_Reports_46'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8b80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155181001001928956' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2300' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:990' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '923', 'source': 'Marlin', 'type': 'source', 'target': 'Relationship_AccessPermission_349'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243709' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:952' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '944', 'source': 'Serenity', 'type': 'source', 'target': 'Relationship_AccessPermission_7'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cb0e50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477250' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:962' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '941', 'source': 'Serenity', 'type': 'source', 'target': 'Relationship_AccessPermission_127'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8eb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477251' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:963' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '942', 'source': 'Serenity', 'type': 'source', 'target': 'Relationship_AccessPermission_128'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cb0b50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477264' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:976' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '939', 'source': 'Serenity', 'type': 'source', 'target': 'Relationship_AccessPermission_238'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd80d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919788524036162614' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1078' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '948', 'source': 'Serenity', 'type': 'source', 'target': 'Relationship_Coordinates_247'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243710' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:965' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '957', 'source': 'Mako', 'type': 'source', 'target': 'Relationship_AccessPermission_148'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd66a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477315' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1027' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '997', 'source': 'Mako', 'type': 'source', 'target': 'Relationship_Reports_170'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd65b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477258' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:970' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1043', 'source': 'Mako', 'type': 'source', 'target': 'Relationship_AccessPermission_190'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8d60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477259' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:971' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1010', 'source': 'Mako', 'type': 'source', 'target': 'Relationship_AccessPermission_192'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477263' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:975' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1024', 'source': 'Mako', 'type': 'source', 'target': 'Relationship_AccessPermission_233'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff9d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477265' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:977' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1016', 'source': 'Mako', 'type': 'source', 'target': 'Relationship_AccessPermission_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cb0700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477367' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1079' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1038', 'source': 'Mako', 'type': 'source', 'target': 'Relationship_Coordinates_248'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71d60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155181001001928958' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:979' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1039', 'source': 'Mako', 'type': 'source', 'target': 'Relationship_AccessPermission_259'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f7c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477276' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:988' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1070', 'source': 'Mako', 'type': 'source', 'target': 'Relationship_AccessPermission_332'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b2b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477383' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1095' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1045', 'source': 'Mako', 'type': 'source', 'target': 'Relationship_Coordinates_336'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fb50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477387' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1099' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1063', 'source': 'Mako', 'type': 'source', 'target': 'Relationship_Coordinates_387'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71e20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477297' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1009' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1096', 'source': 'Mako', 'type': 'source', 'target': 'Relationship_AccessPermission_512'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff5b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477410' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1122' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1097', 'source': 'Mako', 'type': 'source', 'target': 'Relationship_Coordinates_565'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf3d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477332' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1044' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1105', 'source': 'Mako', 'type': 'source', 'target': 'Relationship_Reports_622'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ffb50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477419' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1131' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1109', 'source': 'Mako', 'type': 'source', 'target': 'Relationship_Coordinates_629'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0040>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919788524036162462' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:926' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Mako_source_Relationship_Colleagues_66', 'source': 'Mako', 'type': 'source', 'target': 'Relationship_Colleagues_66'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8b50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243711' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1088' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1137', 'source': 'Reef_Guardian', 'type': 'source', 'target': 'Relationship_Coordinates_292'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222478639' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2351' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1142', 'source': 'Reef_Guardian', 'type': 'source', 'target': 'Relationship_Suspicious_294'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8040>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477319' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1031' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1218', 'source': 'Reef_Guardian', 'type': 'source', 'target': 'Relationship_Reports_344'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd82b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477279' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:991' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1153', 'source': 'Reef_Guardian', 'type': 'source', 'target': 'Relationship_AccessPermission_370'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477385' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1097' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1185', 'source': 'Reef_Guardian', 'type': 'source', 'target': 'Relationship_Coordinates_378'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477386' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1098' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1170', 'source': 'Reef_Guardian', 'type': 'source', 'target': 'Relationship_Coordinates_380'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf1c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477294' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1006' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1154', 'source': 'Reef_Guardian', 'type': 'source', 'target': 'Relationship_AccessPermission_497'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce95b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477325' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1037' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1118', 'source': 'Reef_Guardian', 'type': 'source', 'target': 'Relationship_Reports_526'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477406' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1118' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1182', 'source': 'Reef_Guardian', 'type': 'source', 'target': 'Relationship_Coordinates_548'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477408' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1120' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1135', 'source': 'Reef_Guardian', 'type': 'source', 'target': 'Relationship_Coordinates_555'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc31f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477412' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1124' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1208', 'source': 'Reef_Guardian', 'type': 'source', 'target': 'Relationship_Coordinates_578'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcffa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477345' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1057' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1221', 'source': 'Reef_Guardian', 'type': 'source', 'target': 'Relationship_Jurisdiction_613'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x103476c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477414' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1126' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1225', 'source': 'Reef_Guardian', 'type': 'source', 'target': 'Relationship_Coordinates_614'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477307' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1019' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1226', 'source': 'Reef_Guardian', 'type': 'source', 'target': 'Relationship_AccessPermission_615'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bf70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243712' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1062' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1229', 'source': 'Horizon', 'type': 'source', 'target': 'Relationship_Coordinates_33'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155181001001928960' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1064' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1233', 'source': 'Horizon', 'type': 'source', 'target': 'Relationship_Coordinates_37'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf040>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477309' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1021' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1234', 'source': 'Horizon', 'type': 'source', 'target': 'Relationship_Reports_38'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477356' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1068' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1256', 'source': 'Horizon', 'type': 'source', 'target': 'Relationship_Coordinates_54'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6e80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477390' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1102' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1252', 'source': 'Horizon', 'type': 'source', 'target': 'Relationship_Coordinates_413'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcfcd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477409' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1121' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1261', 'source': 'Horizon', 'type': 'source', 'target': 'Relationship_Coordinates_556'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcff10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243713' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1101' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1272', 'source': 'Seawatch', 'type': 'source', 'target': 'Relationship_Coordinates_411'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd67c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155181001001928961' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1005' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1280', 'source': 'Seawatch', 'type': 'source', 'target': 'Relationship_AccessPermission_489'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff2b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243714' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1024' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1356', 'source': 'EcoVigil', 'type': 'source', 'target': 'Relationship_Reports_51'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155181001001928962' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1080' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1287', 'source': 'EcoVigil', 'type': 'source', 'target': 'Relationship_Coordinates_251'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf0a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477388' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1100' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1300', 'source': 'EcoVigil', 'type': 'source', 'target': 'Relationship_Coordinates_401'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd86d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477288' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1000' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1308', 'source': 'EcoVigil', 'type': 'source', 'target': 'Relationship_AccessPermission_441'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3af0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477289' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1001' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1305', 'source': 'EcoVigil', 'type': 'source', 'target': 'Relationship_AccessPermission_444'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477322' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1034' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1321', 'source': 'EcoVigil', 'type': 'source', 'target': 'Relationship_Reports_447'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x103476c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477290' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1002' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1327', 'source': 'EcoVigil', 'type': 'source', 'target': 'Relationship_AccessPermission_455'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fb80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222478647' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2359' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1330', 'source': 'EcoVigil', 'type': 'source', 'target': 'Relationship_Suspicious_457'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8b80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477303' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1015' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1335', 'source': 'EcoVigil', 'type': 'source', 'target': 'Relationship_AccessPermission_585'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddfdc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477304' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1016' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1332', 'source': 'EcoVigil', 'type': 'source', 'target': 'Relationship_AccessPermission_588'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd60a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477331' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1043' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1343', 'source': 'EcoVigil', 'type': 'source', 'target': 'Relationship_Reports_604'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fb80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157432800815614210' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1126' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1347', 'source': 'EcoVigil', 'type': 'source', 'target': 'Relationship_Coordinates_614'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159684600629299458' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1019' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1348', 'source': 'EcoVigil', 'type': 'source', 'target': 'Relationship_AccessPermission_615'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477415' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1127' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1352', 'source': 'EcoVigil', 'type': 'source', 'target': 'Relationship_Coordinates_616'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff7c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243715' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1183' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1398', 'source': 'Sentinel', 'type': 'source', 'target': 'Relationship_Suspicious_145'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71d60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155181001001928963' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1081' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1380', 'source': 'Sentinel', 'type': 'source', 'target': 'Relationship_Coordinates_252'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477371' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1083' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1372', 'source': 'Sentinel', 'type': 'source', 'target': 'Relationship_Coordinates_269'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222478638' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2350' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1396', 'source': 'Sentinel', 'type': 'source', 'target': 'Relationship_Suspicious_293'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6f40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477321' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1033' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1401', 'source': 'Sentinel', 'type': 'source', 'target': 'Relationship_Reports_408'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71d60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222478644' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2356' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1403', 'source': 'Sentinel', 'type': 'source', 'target': 'Relationship_Suspicious_410'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477286' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:998' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1422', 'source': 'Sentinel', 'type': 'source', 'target': 'Relationship_AccessPermission_421'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x103476c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477302' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1014' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1415', 'source': 'Sentinel', 'type': 'source', 'target': 'Relationship_AccessPermission_569'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ffac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477328' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1040' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1418', 'source': 'Sentinel', 'type': 'source', 'target': 'Relationship_Reports_572'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb06a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243716' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2308' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1007' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1440', 'source': 'Osprey', 'type': 'source', 'target': 'Relationship_AccessPermission_502'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477403' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2308' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1115' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1429', 'source': 'Osprey', 'type': 'source', 'target': 'Relationship_Coordinates_509'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243717' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2309' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1103' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1451', 'source': 'Defender', 'type': 'source', 'target': 'Relationship_Coordinates_418'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc85e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243718' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2310' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2365' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1459', 'source': 'Northern_Light', 'type': 'source', 'target': 'Relationship_Unfriendly_130'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8f40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477281' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2310' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:993' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1463', 'source': 'Northern_Light', 'type': 'source', 'target': 'Relationship_AccessPermission_392'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc88b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477282' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2310' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:994' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1464', 'source': 'Northern_Light', 'type': 'source', 'target': 'Relationship_AccessPermission_393'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ffac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243719' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:957' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1474', 'source': 'Remora', 'type': 'source', 'target': 'Relationship_AccessPermission_100'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f9a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477248' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:960' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1477', 'source': 'Remora', 'type': 'source', 'target': 'Relationship_AccessPermission_122'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de87f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155181001001928967' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:967' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1478', 'source': 'Remora', 'type': 'source', 'target': 'Relationship_AccessPermission_161'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5970>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477256' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:968' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1479', 'source': 'Remora', 'type': 'source', 'target': 'Relationship_AccessPermission_163'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd88e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157432800815614215' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:971' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1485', 'source': 'Remora', 'type': 'source', 'target': 'Relationship_AccessPermission_192'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc31c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159684600629299463' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:979' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1488', 'source': 'Remora', 'type': 'source', 'target': 'Relationship_AccessPermission_259'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5d30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477377' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1089' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1490', 'source': 'Remora', 'type': 'source', 'target': 'Relationship_Coordinates_297'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc59a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477382' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1094' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1521', 'source': 'Remora', 'type': 'source', 'target': 'Relationship_Coordinates_334'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477277' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:989' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1465', 'source': 'Remora', 'type': 'source', 'target': 'Relationship_AccessPermission_338'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x103476c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222478648' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2360' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1524', 'source': 'Remora', 'type': 'source', 'target': 'Relationship_Suspicious_470'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de87f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477404' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1116' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1523', 'source': 'Remora', 'type': 'source', 'target': 'Relationship_Coordinates_516'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8280>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477298' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1010' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1534', 'source': 'Remora', 'type': 'source', 'target': 'Relationship_AccessPermission_553'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71f10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477305' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1017' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1541', 'source': 'Remora', 'type': 'source', 'target': 'Relationship_AccessPermission_591'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477330' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1042' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1548', 'source': 'Remora', 'type': 'source', 'target': 'Relationship_Reports_603'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de87f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919788524036162464' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:928' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Remora_source_Relationship_Colleagues_83', 'source': 'Remora', 'type': 'source', 'target': 'Relationship_Colleagues_83'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc57c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919788524036162463' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:927' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Remora_source_Relationship_Colleagues_80', 'source': 'Remora', 'type': 'source', 'target': 'Relationship_Colleagues_80'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8e20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243720' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2312' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1140' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1552', 'source': 'Knowles', 'type': 'source', 'target': 'Relationship_Operates_109'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce96a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155181001001928968' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2312' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1011' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1556', 'source': 'Knowles', 'type': 'source', 'target': 'Relationship_AccessPermission_560'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fe20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477300' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2312' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1012' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1559', 'source': 'Knowles', 'type': 'source', 'target': 'Relationship_AccessPermission_562'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477417' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2312' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1129' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1560', 'source': 'Knowles', 'type': 'source', 'target': 'Relationship_Coordinates_621'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71d30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919788524036162487' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2312' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:951' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': 'Knowles_source_Relationship_Colleagues_628', 'source': 'Knowles', 'type': 'source', 'target': 'Relationship_Colleagues_628'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce96a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243721' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2313' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:955' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1567', 'source': 'Mariner_s_Dream', 'type': 'source', 'target': 'Relationship_AccessPermission_96'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8e20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477244' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2313' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:956' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1568', 'source': 'Mariner_s_Dream', 'type': 'source', 'target': 'Relationship_AccessPermission_98'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243722' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2314' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:964' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1570', 'source': 'Recreational_Fishing_Boats', 'type': 'source', 'target': 'Relationship_AccessPermission_129'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71d60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477262' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2314' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:974' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1573', 'source': 'Recreational_Fishing_Boats', 'type': 'source', 'target': 'Relationship_AccessPermission_232'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243724' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2316' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:959' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1574', 'source': 'Diving_Tour_Operators', 'type': 'source', 'target': 'Relationship_AccessPermission_118'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd62b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243725' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2317' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:995' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1580', 'source': 'Tourists', 'type': 'source', 'target': 'Relationship_AccessPermission_397'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243726' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2318' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1003' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1588', 'source': 'Conservation_Vessels', 'type': 'source', 'target': 'Relationship_AccessPermission_477'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243727' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1020' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1596', 'source': 'Paackland_Harbor', 'type': 'source', 'target': 'Relationship_Reports_18'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5b50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477470' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1182' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1603', 'source': 'Paackland_Harbor', 'type': 'source', 'target': 'Relationship_Suspicious_123'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477337' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1049' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1606', 'source': 'Paackland_Harbor', 'type': 'source', 'target': 'Relationship_Jurisdiction_162'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8f40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477341' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1053' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1615', 'source': 'Paackland_Harbor', 'type': 'source', 'target': 'Relationship_Jurisdiction_575'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b712e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243728' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2320' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1066' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1616', 'source': 'Haacklee_Harbor', 'type': 'source', 'target': 'Relationship_Coordinates_43'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243729' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:992' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1636', 'source': 'Himark_Harbor', 'type': 'source', 'target': 'Relationship_AccessPermission_382'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6a90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917536724222477418' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1130' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1656', 'source': 'Himark_Harbor', 'type': 'source', 'target': 'Relationship_Coordinates_623'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc86a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152929201188243755' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2347' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1056' labels=frozenset() properties={}>) type='source' properties={'is_inferred': True, 'id': '1659', 'source': 'Port_Security', 'type': 'source', 'target': 'Relationship_Jurisdiction_611'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc59d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710016' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2276' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:384' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '3', 'source': 'Sam', 'type': 'sent', 'target': 'Event_Communication_370'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710411' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2276' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:779' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '5', 'source': 'Sam', 'type': 'sent', 'target': 'Event_Assessment_600'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709801' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2277' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:169' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '8', 'source': 'Kelly', 'type': 'sent', 'target': 'Event_Communication_3'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351baf0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710063' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2277' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:431' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '10', 'source': 'Kelly', 'type': 'sent', 'target': 'Event_Communication_443'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8b50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709987' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:355' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '13', 'source': 'Nadia_Conti', 'type': 'sent', 'target': 'Event_Communication_331'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709990' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:358' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '15', 'source': 'Nadia_Conti', 'type': 'sent', 'target': 'Event_Communication_334'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd86d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710106' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:474' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '16', 'source': 'Nadia_Conti', 'type': 'sent', 'target': 'Event_Communication_529'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6b50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710110' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:478' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '17', 'source': 'Nadia_Conti', 'type': 'sent', 'target': 'Event_Communication_536'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5b50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710112' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:480' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '20', 'source': 'Nadia_Conti', 'type': 'sent', 'target': 'Event_Communication_538'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710140' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:508' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '21', 'source': 'Nadia_Conti', 'type': 'sent', 'target': 'Event_Communication_584'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc32b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710265' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:633' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '24', 'source': 'Nadia_Conti', 'type': 'sent', 'target': 'Event_Communication_795'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710299' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:667' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '25', 'source': 'Nadia_Conti', 'type': 'sent', 'target': 'Event_Communication_847'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710544' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:912' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '26', 'source': 'Nadia_Conti', 'type': 'sent', 'target': 'Event_Collaborate_868'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6af0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710105' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2279' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:473' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '29', 'source': 'Elise', 'type': 'sent', 'target': 'Event_Communication_528'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710151' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2279' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:519' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '31', 'source': 'Elise', 'type': 'sent', 'target': 'Event_Communication_601'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710180' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2279' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:548' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '32', 'source': 'Elise', 'type': 'sent', 'target': 'Event_Communication_647'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de82e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710212' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2279' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:580' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '35', 'source': 'Elise', 'type': 'sent', 'target': 'Event_Communication_708'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6af0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710222' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2279' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:590' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '36', 'source': 'Elise', 'type': 'sent', 'target': 'Event_Communication_727'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd17c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710393' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:761' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '46', 'source': 'Liam_Thorne', 'type': 'sent', 'target': 'Event_Assessment_41'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd16a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710476' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:844' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '38', 'source': 'Liam_Thorne', 'type': 'sent', 'target': 'Event_Enforcement_42'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709827' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:195' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '41', 'source': 'Liam_Thorne', 'type': 'sent', 'target': 'Event_Communication_43'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf1f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709992' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:360' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '48', 'source': 'Liam_Thorne', 'type': 'sent', 'target': 'Event_Communication_338'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bf10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710107' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:475' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '51', 'source': 'Liam_Thorne', 'type': 'sent', 'target': 'Event_Communication_531'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034710a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709665' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:33' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '53', 'source': 'Liam_Thorne', 'type': 'sent', 'target': 'Event_Monitoring_534'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710109' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:477' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '56', 'source': 'Liam_Thorne', 'type': 'sent', 'target': 'Event_Communication_535'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3a90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710539' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:907' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '57', 'source': 'Liam_Thorne', 'type': 'sent', 'target': 'Event_Collaborate_697'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x103557340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710541' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:909' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '58', 'source': 'Liam_Thorne', 'type': 'sent', 'target': 'Event_Collaborate_723'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10347cd60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710220' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:588' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '62', 'source': 'Liam_Thorne', 'type': 'sent', 'target': 'Event_Communication_724'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710229' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:597' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '64', 'source': 'Liam_Thorne', 'type': 'sent', 'target': 'Event_Communication_739'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ffb50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710234' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:602' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '65', 'source': 'Liam_Thorne', 'type': 'sent', 'target': 'Event_Communication_749'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710236' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:604' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '67', 'source': 'Liam_Thorne', 'type': 'sent', 'target': 'Event_Communication_753'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710319' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:687' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '69', 'source': 'Liam_Thorne', 'type': 'sent', 'target': 'Event_Communication_881'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3550>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710350' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:718' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '72', 'source': 'Liam_Thorne', 'type': 'sent', 'target': 'Event_Communication_933'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ffb50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710361' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:729' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '73', 'source': 'Liam_Thorne', 'type': 'sent', 'target': 'Event_Communication_953'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc53a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709836' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2281' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:204' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '75', 'source': 'Samantha_Blake', 'type': 'sent', 'target': 'Event_Communication_64'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709838' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2281' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:206' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '77', 'source': 'Samantha_Blake', 'type': 'sent', 'target': 'Event_Communication_67'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1dc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709855' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2281' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:223' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '79', 'source': 'Samantha_Blake', 'type': 'sent', 'target': 'Event_Communication_103'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709861' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2281' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:229' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '80', 'source': 'Samantha_Blake', 'type': 'sent', 'target': 'Event_Communication_113'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd85e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710025' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2281' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:393' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '83', 'source': 'Samantha_Blake', 'type': 'sent', 'target': 'Event_Communication_381'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf4c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710116' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2281' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:484' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '86', 'source': 'Samantha_Blake', 'type': 'sent', 'target': 'Event_Communication_544'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc35b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710175' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2281' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:543' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '88', 'source': 'Samantha_Blake', 'type': 'sent', 'target': 'Event_Communication_640'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710202' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2281' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:570' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '89', 'source': 'Samantha_Blake', 'type': 'sent', 'target': 'Event_Communication_685'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710204' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2281' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:572' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '91', 'source': 'Samantha_Blake', 'type': 'sent', 'target': 'Event_Communication_687'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709815' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:183' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '94', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Communication_20'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709862' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:230' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '97', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Communication_115'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034710a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709946' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:314' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '102', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Communication_260'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce92b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709958' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:326' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '105', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Communication_281'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf1c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709959' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:327' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '107', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Communication_282'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709964' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:332' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '110', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Communication_291'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709966' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:334' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '112', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Communication_295'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71d30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709996' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:364' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '114', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Communication_343'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710102' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:470' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '116', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Communication_521'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710119' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:487' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '118', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Communication_548'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710535' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:903' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '119', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Collaborate_550'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb08b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710120' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:488' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '121', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Communication_551'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b1c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710138' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:506' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '122', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Communication_581'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6970>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710139' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:507' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '124', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Communication_582'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fe20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710410' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:778' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '125', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Assessment_583'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb08b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710141' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:509' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '127', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Communication_585'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710174' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:542' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '130', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Communication_639'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc36d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710269' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:637' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '132', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Communication_802'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ffb50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710543' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:911' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '133', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Collaborate_818'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b5e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710279' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:647' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '136', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Communication_819'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0dc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710296' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:664' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '139', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Communication_844'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710297' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:665' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '140', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Communication_845'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fe20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710304' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:672' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '145', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Communication_853'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966395792' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:912' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '146', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Collaborate_868'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710313' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:681' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '148', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Communication_869'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0a90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710339' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:707' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '153', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Communication_916'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710366' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:734' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '155', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Communication_963'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10347cdc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710368' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:736' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '157', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Communication_964'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce97c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710381' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:749' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '160', 'source': 'Davis', 'type': 'sent', 'target': 'Event_Communication_986'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709880' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:248' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '163', 'source': 'Rodriguez', 'type': 'sent', 'target': 'Event_Communication_142'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710400' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:768' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '165', 'source': 'Rodriguez', 'type': 'sent', 'target': 'Event_Assessment_198'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10347cdc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709909' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:277' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '167', 'source': 'Rodriguez', 'type': 'sent', 'target': 'Event_Communication_199'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71d60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710518' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:886' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '169', 'source': 'Rodriguez', 'type': 'sent', 'target': 'Event_Collaborate_200'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709936' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:304' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '171', 'source': 'Rodriguez', 'type': 'sent', 'target': 'Event_Communication_240'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10346cfa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709985' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:353' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '172', 'source': 'Rodriguez', 'type': 'sent', 'target': 'Event_Communication_328'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710037' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:405' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '174', 'source': 'Rodriguez', 'type': 'sent', 'target': 'Event_Communication_401'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10347cdc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710096' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:464' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '176', 'source': 'Rodriguez', 'type': 'sent', 'target': 'Event_Communication_511'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1035572b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710127' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:495' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '177', 'source': 'Rodriguez', 'type': 'sent', 'target': 'Event_Communication_562'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce98b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710142' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:510' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '180', 'source': 'Rodriguez', 'type': 'sent', 'target': 'Event_Communication_588'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8a90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710246' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:614' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '182', 'source': 'Rodriguez', 'type': 'sent', 'target': 'Event_Communication_764'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710270' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:638' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '184', 'source': 'Rodriguez', 'type': 'sent', 'target': 'Event_Communication_804'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71d60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710271' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:639' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '185', 'source': 'Rodriguez', 'type': 'sent', 'target': 'Event_Communication_805'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce91f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710274' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:642' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '188', 'source': 'Rodriguez', 'type': 'sent', 'target': 'Event_Communication_810'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710326' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:694' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '189', 'source': 'Rodriguez', 'type': 'sent', 'target': 'Event_Communication_893'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710379' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:747' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '190', 'source': 'Rodriguez', 'type': 'sent', 'target': 'Event_Communication_982'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8eb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709871' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:239' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '192', 'source': 'Clepper_Jensen', 'type': 'sent', 'target': 'Event_Communication_128'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690ffd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709873' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:241' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '195', 'source': 'Clepper_Jensen', 'type': 'sent', 'target': 'Event_Communication_131'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034fff70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709874' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:242' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '197', 'source': 'Clepper_Jensen', 'type': 'sent', 'target': 'Event_Communication_132'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fb20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709876' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:244' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '198', 'source': 'Clepper_Jensen', 'type': 'sent', 'target': 'Event_Communication_135'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8b50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709911' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:279' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '203', 'source': 'Clepper_Jensen', 'type': 'sent', 'target': 'Event_Communication_203'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709913' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:281' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '205', 'source': 'Clepper_Jensen', 'type': 'sent', 'target': 'Event_Communication_205'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f0a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709915' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:283' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '207', 'source': 'Clepper_Jensen', 'type': 'sent', 'target': 'Event_Communication_207'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710006' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:374' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '210', 'source': 'Clepper_Jensen', 'type': 'sent', 'target': 'Event_Communication_357'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710008' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:376' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '212', 'source': 'Clepper_Jensen', 'type': 'sent', 'target': 'Event_Communication_360'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71b80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710010' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:378' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '213', 'source': 'Clepper_Jensen', 'type': 'sent', 'target': 'Event_Communication_362'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf9a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710022' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:390' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '216', 'source': 'Clepper_Jensen', 'type': 'sent', 'target': 'Event_Communication_377'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710074' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:442' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '218', 'source': 'Clepper_Jensen', 'type': 'sent', 'target': 'Event_Communication_468'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710076' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:444' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '220', 'source': 'Clepper_Jensen', 'type': 'sent', 'target': 'Event_Communication_470'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710078' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:446' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '221', 'source': 'Clepper_Jensen', 'type': 'sent', 'target': 'Event_Communication_474'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710080' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:448' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '223', 'source': 'Clepper_Jensen', 'type': 'sent', 'target': 'Event_Communication_476'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd61c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710082' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:450' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '225', 'source': 'Clepper_Jensen', 'type': 'sent', 'target': 'Event_Communication_479'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710248' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:616' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '227', 'source': 'Clepper_Jensen', 'type': 'sent', 'target': 'Event_Communication_768'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710250' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:618' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '229', 'source': 'Clepper_Jensen', 'type': 'sent', 'target': 'Event_Communication_771'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710252' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:620' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '231', 'source': 'Clepper_Jensen', 'type': 'sent', 'target': 'Event_Communication_773'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcfe20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710254' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:622' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '234', 'source': 'Clepper_Jensen', 'type': 'sent', 'target': 'Event_Communication_775'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x103471910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709870' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:238' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '236', 'source': 'Miranda_Jordan', 'type': 'sent', 'target': 'Event_Communication_126'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6b50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709643' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:11' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '237', 'source': 'Miranda_Jordan', 'type': 'sent', 'target': 'Event_Monitoring_129'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf4f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709872' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:240' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '240', 'source': 'Miranda_Jordan', 'type': 'sent', 'target': 'Event_Communication_130'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709644' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:12' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '241', 'source': 'Miranda_Jordan', 'type': 'sent', 'target': 'Event_Monitoring_133'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8e20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709875' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:243' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '244', 'source': 'Miranda_Jordan', 'type': 'sent', 'target': 'Event_Communication_134'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6b50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709910' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:278' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '246', 'source': 'Miranda_Jordan', 'type': 'sent', 'target': 'Event_Communication_201'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709912' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:280' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '248', 'source': 'Miranda_Jordan', 'type': 'sent', 'target': 'Event_Communication_204'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709914' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:282' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '249', 'source': 'Miranda_Jordan', 'type': 'sent', 'target': 'Event_Communication_206'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709657' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:25' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '250', 'source': 'Miranda_Jordan', 'type': 'sent', 'target': 'Event_Monitoring_358'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710007' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:375' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '252', 'source': 'Miranda_Jordan', 'type': 'sent', 'target': 'Event_Communication_359'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710009' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:377' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '253', 'source': 'Miranda_Jordan', 'type': 'sent', 'target': 'Event_Communication_361'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710021' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:389' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '254', 'source': 'Miranda_Jordan', 'type': 'sent', 'target': 'Event_Communication_376'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddfb80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710075' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:443' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '255', 'source': 'Miranda_Jordan', 'type': 'sent', 'target': 'Event_Communication_469'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710077' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:445' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '256', 'source': 'Miranda_Jordan', 'type': 'sent', 'target': 'Event_Communication_473'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd68b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710079' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:447' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '257', 'source': 'Miranda_Jordan', 'type': 'sent', 'target': 'Event_Communication_475'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6af0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710081' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:449' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '259', 'source': 'Miranda_Jordan', 'type': 'sent', 'target': 'Event_Communication_478'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710247' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:615' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '260', 'source': 'Miranda_Jordan', 'type': 'sent', 'target': 'Event_Communication_767'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3e20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710249' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:617' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '261', 'source': 'Miranda_Jordan', 'type': 'sent', 'target': 'Event_Communication_770'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710251' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:619' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '262', 'source': 'Miranda_Jordan', 'type': 'sent', 'target': 'Event_Communication_772'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc37f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710253' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:621' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '264', 'source': 'Miranda_Jordan', 'type': 'sent', 'target': 'Event_Communication_774'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1c10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710255' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:623' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '266', 'source': 'Miranda_Jordan', 'type': 'sent', 'target': 'Event_Communication_776'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709798' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:166' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '268', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Communication_2'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8d30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709803' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:171' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '271', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Communication_5'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709845' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:213' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '273', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Communication_89'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709848' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:216' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '276', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Communication_92'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc37f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709891' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:259' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '279', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Communication_160'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709893' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:261' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '280', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Communication_162'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ffb50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709939' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:307' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '281', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Communication_246'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1e50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709979' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:347' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '284', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Communication_318'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc37f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710018' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:386' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '286', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Communication_372'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b7c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710062' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:430' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '287', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Communication_442'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710064' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:432' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '289', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Communication_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcfbe0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710104' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:472' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '290', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Communication_525'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710147' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:515' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '292', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Communication_596'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9df0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710150' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:518' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '294', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Communication_599'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb04c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710415' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:783' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '295', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Assessment_650'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf2e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710182' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:550' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '297', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Communication_651'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8cd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710210' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:578' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '300', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Communication_702'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710418' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:786' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '301', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Assessment_703'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709674' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:42' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '302', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Monitoring_704'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710211' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:579' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '304', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Communication_705'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8cd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710216' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:584' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '306', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Communication_715'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710540' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:908' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '269', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Collaborate_719'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710218' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:586' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '310', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Communication_720'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf1c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710419' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:787' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '311', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Assessment_729'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x103471910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710308' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:676' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '313', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Communication_860'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710310' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:678' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '315', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Communication_864'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710342' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:710' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '317', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Communication_921'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf4c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710344' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:712' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '320', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Communication_925'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x103471910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710352' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:720' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '322', 'source': 'The_Intern', 'type': 'sent', 'target': 'Event_Communication_936'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc81f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709632' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:0' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '323', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Monitoring_0'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fc40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709789' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:157' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '324', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_1'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709844' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:212' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '326', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_87'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709849' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:217' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '329', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_94'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709890' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:258' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '330', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_159'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71dc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709898' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:266' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '332', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_171'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8040>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709905' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:273' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '334', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_189'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5bb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709937' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:305' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '335', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_244'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bf10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709967' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:335' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '336', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_297'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce93d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709978' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:346' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '337', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_317'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710017' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:385' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '339', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_371'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5bb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710061' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:429' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '340', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_441'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bf10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709661' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:29' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '341', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Monitoring_444'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de76a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710404' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:772' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '342', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Assessment_445'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710103' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:471' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '343', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_523'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710143' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:511' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '345', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_590'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710145' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:513' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '347', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_593'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710146' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:514' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '349', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_594'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709666' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:34' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '377', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Monitoring_595'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f8b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710163' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:531' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '352', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_619'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8e20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710181' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:549' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '354', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_649'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034fff70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710183' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:551' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '355', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_652'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710200' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:568' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '356', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_683'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710214' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:582' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '357', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_712'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8e20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710215' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:583' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '358', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_714'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9df0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710217' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:585' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '359', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_717'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710422' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:790' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '361', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Assessment_791'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034fffa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710262' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:630' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '363', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_792'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8e20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710264' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:632' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '364', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_794'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10347c0a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709683' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:51' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '365', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Monitoring_797'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71f40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710462' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:830' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '366', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_VesselMovement_798'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5bb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710267' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:635' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '367', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_799'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710307' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:675' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '368', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_859'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710309' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:677' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '369', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_862'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710337' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:705' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '370', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_912'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b712e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710343' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:711' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '372', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_923'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710345' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:713' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '374', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_926'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710351' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:719' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '375', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_935'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710353' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:721' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '376', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_937'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710384' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:752' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '378', 'source': 'The_Lookout', 'type': 'sent', 'target': 'Event_Communication_991'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3a90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710221' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2289' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:589' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '380', 'source': 'The_Accountant', 'type': 'sent', 'target': 'Event_Communication_726'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0dc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710311' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2289' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:679' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '382', 'source': 'The_Accountant', 'type': 'sent', 'target': 'Event_Communication_866'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fc70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710360' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2289' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:728' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '386', 'source': 'The_Accountant', 'type': 'sent', 'target': 'Event_Communication_951'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd62b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709804' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:172' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '388', 'source': 'Mrs__Money', 'type': 'sent', 'target': 'Event_Communication_6'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7d30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709806' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:174' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '390', 'source': 'Mrs__Money', 'type': 'sent', 'target': 'Event_Communication_8'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1c10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709817' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:185' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '391', 'source': 'Mrs__Money', 'type': 'sent', 'target': 'Event_Communication_22'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de74f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709846' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:214' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '392', 'source': 'Mrs__Money', 'type': 'sent', 'target': 'Event_Communication_90'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd62b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709847' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:215' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '393', 'source': 'Mrs__Money', 'type': 'sent', 'target': 'Event_Communication_91'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709866' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:234' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '396', 'source': 'Mrs__Money', 'type': 'sent', 'target': 'Event_Communication_120'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709892' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:260' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '397', 'source': 'Mrs__Money', 'type': 'sent', 'target': 'Event_Communication_161'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709894' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:262' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '398', 'source': 'Mrs__Money', 'type': 'sent', 'target': 'Event_Communication_163'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10347cdc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709940' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:308' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '399', 'source': 'Mrs__Money', 'type': 'sent', 'target': 'Event_Communication_248'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709942' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:310' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '401', 'source': 'Mrs__Money', 'type': 'sent', 'target': 'Event_Communication_250'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf9d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709957' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:325' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '406', 'source': 'Mrs__Money', 'type': 'sent', 'target': 'Event_Communication_280'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df72b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710013' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:381' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '408', 'source': 'Mrs__Money', 'type': 'sent', 'target': 'Event_Communication_367'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x103471700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710015' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:383' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '409', 'source': 'Mrs__Money', 'type': 'sent', 'target': 'Event_Communication_369'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710019' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:387' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '410', 'source': 'Mrs__Money', 'type': 'sent', 'target': 'Event_Communication_373'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710069' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:437' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '411', 'source': 'Mrs__Money', 'type': 'sent', 'target': 'Event_Communication_458'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf4c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710405' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:773' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '412', 'source': 'Mrs__Money', 'type': 'sent', 'target': 'Event_Assessment_463'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710072' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:440' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '414', 'source': 'Mrs__Money', 'type': 'sent', 'target': 'Event_Communication_464'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710114' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:482' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '415', 'source': 'Mrs__Money', 'type': 'sent', 'target': 'Event_Communication_541'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bcd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710148' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:516' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '416', 'source': 'Mrs__Money', 'type': 'sent', 'target': 'Event_Communication_597'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7550>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966395667' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:787' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '419', 'source': 'Mrs__Money', 'type': 'sent', 'target': 'Event_Assessment_729'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710224' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:592' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '421', 'source': 'Mrs__Money', 'type': 'sent', 'target': 'Event_Communication_730'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709808' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:176' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '422', 'source': 'The_Middleman', 'type': 'sent', 'target': 'Event_Communication_10'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3f10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709810' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:178' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '423', 'source': 'The_Middleman', 'type': 'sent', 'target': 'Event_Communication_12'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709825' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:193' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '427', 'source': 'The_Middleman', 'type': 'sent', 'target': 'Event_Communication_39'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bf10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709826' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:194' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '428', 'source': 'The_Middleman', 'type': 'sent', 'target': 'Event_Communication_40'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709885' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:253' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '429', 'source': 'The_Middleman', 'type': 'sent', 'target': 'Event_Communication_150'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709953' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:321' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '430', 'source': 'The_Middleman', 'type': 'sent', 'target': 'Event_Communication_275'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b8e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710520' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:888' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '431', 'source': 'The_Middleman', 'type': 'sent', 'target': 'Event_Collaborate_276'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709955' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:323' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '434', 'source': 'The_Middleman', 'type': 'sent', 'target': 'Event_Communication_278'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3bb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709956' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:324' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '435', 'source': 'The_Middleman', 'type': 'sent', 'target': 'Event_Communication_279'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710100' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:468' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '436', 'source': 'The_Middleman', 'type': 'sent', 'target': 'Event_Communication_519'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcfe20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710219' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:587' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '437', 'source': 'The_Middleman', 'type': 'sent', 'target': 'Event_Communication_721'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710266' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:634' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '441', 'source': 'The_Middleman', 'type': 'sent', 'target': 'Event_Communication_796'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb01f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710312' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:680' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '442', 'source': 'The_Middleman', 'type': 'sent', 'target': 'Event_Communication_867'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8be0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710359' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:727' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '445', 'source': 'The_Middleman', 'type': 'sent', 'target': 'Event_Communication_950'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7e20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709805' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:173' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '448', 'source': 'Boss', 'type': 'sent', 'target': 'Event_Communication_7'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd19a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709807' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:175' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '449', 'source': 'Boss', 'type': 'sent', 'target': 'Event_Communication_9'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9040>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709809' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:177' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '450', 'source': 'Boss', 'type': 'sent', 'target': 'Event_Communication_11'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10346cd90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709816' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:184' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '452', 'source': 'Boss', 'type': 'sent', 'target': 'Event_Communication_21'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df75b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709941' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:309' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '456', 'source': 'Boss', 'type': 'sent', 'target': 'Event_Communication_249'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966395768' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:888' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '457', 'source': 'Boss', 'type': 'sent', 'target': 'Event_Collaborate_276'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fd90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709954' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:322' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '459', 'source': 'Boss', 'type': 'sent', 'target': 'Event_Communication_277'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709975' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:343' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '463', 'source': 'Boss', 'type': 'sent', 'target': 'Event_Communication_312'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7af0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709977' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:345' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '464', 'source': 'Boss', 'type': 'sent', 'target': 'Event_Communication_316'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710012' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:380' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '468', 'source': 'Boss', 'type': 'sent', 'target': 'Event_Communication_366'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709881' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2293' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:249' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '470', 'source': 'Small_Fry', 'type': 'sent', 'target': 'Event_Communication_143'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cb03a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710429' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2293' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:797' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '471', 'source': 'Small_Fry', 'type': 'sent', 'target': 'Event_VesselMovement_154'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8e80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709888' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2293' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:256' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '473', 'source': 'Small_Fry', 'type': 'sent', 'target': 'Event_Communication_156'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710532' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2293' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:900' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '474', 'source': 'Small_Fry', 'type': 'sent', 'target': 'Event_Collaborate_512'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de85b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710097' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2293' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:465' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '477', 'source': 'Small_Fry', 'type': 'sent', 'target': 'Event_Communication_513'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710275' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2293' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:643' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '479', 'source': 'Small_Fry', 'type': 'sent', 'target': 'Event_Communication_811'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddfa00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710295' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2293' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:663' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '483', 'source': 'Small_Fry', 'type': 'sent', 'target': 'Event_Communication_842'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9eb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710362' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2293' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:730' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '484', 'source': 'Small_Fry', 'type': 'sent', 'target': 'Event_Communication_955'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de74c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710380' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2293' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:748' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '487', 'source': 'Small_Fry', 'type': 'sent', 'target': 'Event_Communication_984'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fdc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710395' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2294' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:763' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '492', 'source': 'Glitters_Team', 'type': 'sent', 'target': 'Event_Assessment_65'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bf10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709837' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2294' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:205' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '490', 'source': 'Glitters_Team', 'type': 'sent', 'target': 'Event_Communication_66'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709932' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2294' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:300' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '494', 'source': 'Glitters_Team', 'type': 'sent', 'target': 'Event_Communication_231'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de85b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710031' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2294' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:399' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '496', 'source': 'Glitters_Team', 'type': 'sent', 'target': 'Event_Communication_389'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cb0b50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710355' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2294' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:723' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '498', 'source': 'Glitters_Team', 'type': 'sent', 'target': 'Event_Communication_940'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de87f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709824' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:192' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '502', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_37'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc84f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709634' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '559', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Monitoring_38'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5d60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710477' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:845' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '504', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Enforcement_44'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709828' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:196' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '505', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_45'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x103476310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709833' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:201' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '507', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_54'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc84f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710396' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:764' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '535', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Assessment_101'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5d60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709854' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:222' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '510', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_102'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709865' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:233' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '512', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_119'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709900' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:268' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '516', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_176'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710517' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:885' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '518', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Collaborate_184'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709904' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:272' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '521', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_186'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709921' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:289' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '523', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_218'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709922' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:290' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '527', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_221'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709929' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:297' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '528', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_229'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71d30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710484' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:852' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '530', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Enforcement_292'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8e20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709965' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:333' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '532', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_293'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de76d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709970' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:338' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '533', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_302'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709974' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:342' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '534', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_311'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034710a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709982' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:350' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '537', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_323'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb01f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709989' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:357' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '538', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_333'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc87f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709991' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:359' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '540', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_336'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc81f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709993' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:361' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '542', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_339'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf6a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709998' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:366' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '543', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_347'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10347c0a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710001' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:369' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '547', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_351'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710525' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:893' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '549', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Collaborate_364'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcff10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710020' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:388' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '551', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_375'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710036' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:404' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '555', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_399'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc38e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710108' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:476' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '561', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_533'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce92b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710153' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:521' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '564', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_604'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710159' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:527' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '566', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_613'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710162' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:530' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '568', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_617'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710176' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:544' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '570', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_641'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710196' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:564' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '571', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_675'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710203' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:571' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '574', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_686'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ffac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710209' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:577' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '578', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_700'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710227' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:595' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '582', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_735'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710487' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:855' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '525', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Enforcement_745'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8f10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710233' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:601' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '586', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_746'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7bb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710258' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:626' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '592', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_783'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e080a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710320' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:688' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '596', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_882'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fa60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710333' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:701' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '598', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_903'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc32e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710547' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:915' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '600', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_HarborReport_927'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710347' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:715' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '602', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_928'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddfee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710349' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:717' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '604', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_930'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce95b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710386' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:754' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '606', 'source': 'Oceanus_City_Council', 'type': 'sent', 'target': 'Event_Communication_994'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08b50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709835' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:203' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '609', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_62'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709840' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:208' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '610', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_72'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10346cfa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710515' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:883' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '613', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Collaborate_82'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf4c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709843' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:211' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '616', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_85'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ffa60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709856' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:224' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '618', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_106'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b712e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710516' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:884' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '619', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Collaborate_108'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71d60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710398' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:766' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '621', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Assessment_172'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709648' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:16' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '622', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Monitoring_173'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1a90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710399' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:767' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '722', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Assessment_174'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf0a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709899' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:267' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '626', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_175'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd13a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709901' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:269' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '628', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_179'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff7c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709902' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:270' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '630', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_182'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709903' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:271' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '631', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_183'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf0a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709649' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:17' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '644', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Monitoring_192'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709907' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:275' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '636', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_196'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bcd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709651' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:19' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '638', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Monitoring_232'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710481' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:849' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '639', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Enforcement_233'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf0a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710482' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:850' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '656', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Enforcement_235'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8b80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710519' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:887' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '657', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Collaborate_236'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc36d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709934' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:302' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '643', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_237'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd16a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709935' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:303' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '647', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_239'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd88e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709654' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:22' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '648', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Monitoring_255'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709945' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:313' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '652', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_258'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf0d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710483' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:851' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '650', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Enforcement_261'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd14c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709947' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:315' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '655', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_262'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709981' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:349' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '662', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_321'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8cd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710003' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:371' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '667', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_354'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710004' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:372' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '668', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_355'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb05b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710005' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:373' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '670', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_356'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709658' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:26' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '671', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Monitoring_383'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb03a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710027' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:395' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '672', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_384'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709659' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:27' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '673', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Monitoring_410'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710043' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:411' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '675', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_411'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8dc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710044' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:412' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '677', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_413'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc58b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710054' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:422' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '679', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_431'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710055' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:423' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '681', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_433'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710058' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:426' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '683', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_437'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd83a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710059' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:427' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '684', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_438'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc88e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710060' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:428' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '686', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_439'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710530' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:898' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '687', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Collaborate_477'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710409' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:777' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '689', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Assessment_567'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710130' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:498' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '692', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_568'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de82e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710131' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:499' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '694', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_571'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709667' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:35' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '697', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Monitoring_608'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710412' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:780' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '698', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Assessment_609'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08f40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710157' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:525' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '701', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_610'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710158' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:526' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '704', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_612'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710164' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:532' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '707', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_621'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710194' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:562' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '710', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_672'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de84f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709672' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:40' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '711', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Monitoring_690'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cb03a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710416' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:784' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '712', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Assessment_691'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710206' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:574' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '715', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_692'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de72e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709682' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:50' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '718', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Monitoring_777'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e8e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710256' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:624' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '720', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_778'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8e50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710257' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:625' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '723', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_781'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de76d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709685' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:53' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '725', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Monitoring_829'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710288' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:656' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '728', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_831'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710289' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:657' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '731', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_833'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fd60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710290' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:658' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '733', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_834'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034710d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709686' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:54' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '734', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Monitoring_835'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710291' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:659' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '737', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_836'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709690' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:58' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '738', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Monitoring_900'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8cd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710331' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:699' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '740', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_901'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10345ae80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710332' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:700' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '742', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_902'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710335' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:703' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '744', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_908'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710336' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:704' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '745', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_910'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710424' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:792' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '746', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Assessment_966'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710370' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:738' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '748', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_968'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710387' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:755' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '749', 'source': 'Green_Guardians', 'type': 'sent', 'target': 'Event_Communication_997'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce99a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709924' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:292' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '754', 'source': 'V__Miesel_Shipping', 'type': 'sent', 'target': 'Event_Communication_224'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709976' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:344' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '756', 'source': 'V__Miesel_Shipping', 'type': 'sent', 'target': 'Event_Communication_313'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710014' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:382' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '758', 'source': 'V__Miesel_Shipping', 'type': 'sent', 'target': 'Event_Communication_368'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710049' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:417' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '765', 'source': 'V__Miesel_Shipping', 'type': 'sent', 'target': 'Event_Communication_421'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709664' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:32' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '779', 'source': 'V__Miesel_Shipping', 'type': 'sent', 'target': 'Event_Monitoring_530'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710172' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:540' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '775', 'source': 'V__Miesel_Shipping', 'type': 'sent', 'target': 'Event_Communication_637'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de83a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710173' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:541' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '777', 'source': 'V__Miesel_Shipping', 'type': 'sent', 'target': 'Event_Communication_638'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710417' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:785' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '780', 'source': 'V__Miesel_Shipping', 'type': 'sent', 'target': 'Event_Assessment_701'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710223' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:591' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '781', 'source': 'V__Miesel_Shipping', 'type': 'sent', 'target': 'Event_Communication_728'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710241' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:609' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '784', 'source': 'V__Miesel_Shipping', 'type': 'sent', 'target': 'Event_Communication_758'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f280>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710245' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:613' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '792', 'source': 'V__Miesel_Shipping', 'type': 'sent', 'target': 'Event_Communication_763'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710281' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:649' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '796', 'source': 'V__Miesel_Shipping', 'type': 'sent', 'target': 'Event_Communication_821'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710285' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:653' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '798', 'source': 'V__Miesel_Shipping', 'type': 'sent', 'target': 'Event_Communication_825'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710491' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:859' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '799', 'source': 'V__Miesel_Shipping', 'type': 'sent', 'target': 'Event_Enforcement_839'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710293' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:661' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '801', 'source': 'V__Miesel_Shipping', 'type': 'sent', 'target': 'Event_Communication_840'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710294' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:662' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '803', 'source': 'V__Miesel_Shipping', 'type': 'sent', 'target': 'Event_Communication_841'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710298' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:666' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '805', 'source': 'V__Miesel_Shipping', 'type': 'sent', 'target': 'Event_Communication_846'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc86d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710302' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:670' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '806', 'source': 'V__Miesel_Shipping', 'type': 'sent', 'target': 'Event_Communication_851'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10345ae80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709960' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2298' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:328' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '810', 'source': 'Sailor_Shifts_Team', 'type': 'sent', 'target': 'Event_Communication_283'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710101' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2298' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:469' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '812', 'source': 'Sailor_Shifts_Team', 'type': 'sent', 'target': 'Event_Communication_520'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710441' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:809' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '884', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_VesselMovement_393'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf040>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710443' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:811' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '905', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_VesselMovement_402'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f280>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710038' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:406' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '820', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_403'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb09d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710040' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:408' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '822', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_406'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e080d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710042' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:410' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '823', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_409'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710444' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:812' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '824', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_VesselMovement_418'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff6a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710047' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:415' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '825', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_419'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710048' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:416' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '826', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_420'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7970>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710526' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:894' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '827', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Collaborate_422'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710050' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:418' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '830', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_423'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710527' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:895' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '831', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Collaborate_424'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6970>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710052' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:420' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '833', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_426'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcfbb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710529' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:897' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '838', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Collaborate_455'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10346cbe0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710068' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:436' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '839', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_456'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8d90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710070' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:438' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '843', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_460'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc36d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710406' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:774' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '849', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Assessment_488'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710086' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:454' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '850', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_489'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710448' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:816' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '837', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_VesselMovement_503'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710093' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:461' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '853', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_504'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb03a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710094' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:462' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '856', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_506'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff7c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710095' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:463' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '859', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_508'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1035572b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710099' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:467' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '861', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_518'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034711c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710408' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:776' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '846', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Assessment_522'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df70d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710111' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:479' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '868', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_537'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5d30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710113' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:481' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '869', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_539'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710118' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:486' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '871', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_546'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6d30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710125' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:493' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '875', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_559'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710149' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:517' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '876', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_598'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fc40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710155' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:523' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '878', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_606'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf9d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710156' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:524' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '880', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_607'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddfa60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709668' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:36' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '863', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Monitoring_631'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710169' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:537' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '883', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_633'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710178' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:546' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '885', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_644'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710190' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:558' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '887', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_663'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cb03a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710237' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:605' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '890', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_754'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710239' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:607' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '892', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_756'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710242' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:610' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '894', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_759'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5d30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710244' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:612' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '895', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_762'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddfbe0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710280' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:648' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '897', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_820'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710282' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:650' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '899', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_822'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710284' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:652' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '901', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_824'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce93d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710303' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:671' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '904', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_852'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd87f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710325' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:693' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '907', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_891'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710471' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:839' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '908', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_VesselMovement_980'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710376' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:744' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '909', 'source': 'Neptune', 'type': 'sent', 'target': 'Event_Communication_981'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710513' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2300' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:881' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '910', 'source': 'Marlin', 'type': 'sent', 'target': 'Event_Fishing_49'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd67f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709830' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2300' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:198' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '911', 'source': 'Marlin', 'type': 'sent', 'target': 'Event_Communication_50'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b7f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710514' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2300' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:882' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '912', 'source': 'Marlin', 'type': 'sent', 'target': 'Event_Criticize_52'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0ea60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709832' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2300' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:200' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '913', 'source': 'Marlin', 'type': 'sent', 'target': 'Event_Communication_53'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709867' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2300' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:235' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '915', 'source': 'Marlin', 'type': 'sent', 'target': 'Event_Communication_121'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709869' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2300' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:237' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '916', 'source': 'Marlin', 'type': 'sent', 'target': 'Event_Communication_124'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b7f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709961' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2300' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:329' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '917', 'source': 'Marlin', 'type': 'sent', 'target': 'Event_Communication_285'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0eb80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709656' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2300' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:24' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '918', 'source': 'Marlin', 'type': 'sent', 'target': 'Event_Monitoring_286'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709963' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2300' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:331' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '919', 'source': 'Marlin', 'type': 'sent', 'target': 'Event_Communication_289'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710456' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2300' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:824' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '926', 'source': 'Marlin', 'type': 'sent', 'target': 'Event_VesselMovement_577'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710136' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2300' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:504' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '921', 'source': 'Marlin', 'type': 'sent', 'target': 'Event_Communication_578'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1ba00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710457' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2300' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:825' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '922', 'source': 'Marlin', 'type': 'sent', 'target': 'Event_VesselMovement_580'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cb03a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710459' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2300' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:827' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '925', 'source': 'Marlin', 'type': 'sent', 'target': 'Event_VesselMovement_629'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0eb20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709811' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:179' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '928', 'source': 'Serenity', 'type': 'sent', 'target': 'Event_Communication_13'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709813' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:181' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '930', 'source': 'Serenity', 'type': 'sent', 'target': 'Event_Communication_16'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bd90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710427' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:795' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '949', 'source': 'Serenity', 'type': 'sent', 'target': 'Event_VesselMovement_25'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc80d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709819' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:187' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '933', 'source': 'Serenity', 'type': 'sent', 'target': 'Event_Communication_26'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709927' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:295' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '943', 'source': 'Serenity', 'type': 'sent', 'target': 'Event_Communication_227'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710033' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:401' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '947', 'source': 'Serenity', 'type': 'sent', 'target': 'Event_Communication_392'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710041' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:409' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '950', 'source': 'Serenity', 'type': 'sent', 'target': 'Event_Communication_408'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fc10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710092' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:460' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '951', 'source': 'Serenity', 'type': 'sent', 'target': 'Event_Communication_502'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0eb50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710286' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:654' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '952', 'source': 'Serenity', 'type': 'sent', 'target': 'Event_Communication_826'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710470' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:838' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '953', 'source': 'Serenity', 'type': 'sent', 'target': 'Event_VesselMovement_944'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf2e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710391' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:759' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '959', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Assessment_14'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8e50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709812' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:180' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '955', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_15'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7e80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710394' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:762' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '960', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Assessment_56'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709834' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:202' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '962', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_59'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff6d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709852' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:220' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '964', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_99'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fb50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709863' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:231' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '966', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_117'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10346cfa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710428' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:796' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1104', 'source': 'Mako', 'type': 'sent', 'target': 'Event_VesselMovement_122'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709868' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:236' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '968', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_123'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710504' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:872' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '969', 'source': 'Mako', 'type': 'sent', 'target': 'Event_TourActivity_137'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709878' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:246' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '971', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_139'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de77c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709882' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:250' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '974', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_145'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc56d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710548' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:916' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '978', 'source': 'Mako', 'type': 'sent', 'target': 'Event_TransponderPing_251'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709653' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:21' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '981', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Monitoring_253'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b2e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709944' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:312' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '980', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_254'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709950' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:318' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '987', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_268'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb00d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710549' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:917' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '989', 'source': 'Mako', 'type': 'sent', 'target': 'Event_TransponderPing_271'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710434' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:802' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '991', 'source': 'Mako', 'type': 'sent', 'target': 'Event_VesselMovement_284'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf0d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710435' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:803' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '992', 'source': 'Mako', 'type': 'sent', 'target': 'Event_VesselMovement_288'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710436' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:804' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '996', 'source': 'Mako', 'type': 'sent', 'target': 'Event_VesselMovement_300'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b8e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710550' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:918' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1051', 'source': 'Mako', 'type': 'sent', 'target': 'Event_TransponderPing_308'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709973' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:341' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1002', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_309'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f0d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710403' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:771' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '999', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Assessment_337'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de82e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710439' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:807' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1009', 'source': 'Mako', 'type': 'sent', 'target': 'Event_VesselMovement_344'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709999' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:367' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1015', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_349'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710011' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:379' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1017', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_365'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710024' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:392' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1022', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_380'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddfee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710026' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:394' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1023', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_382'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710035' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:403' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1027', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_396'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710039' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:407' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1034', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_405'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd61f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966395692' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:812' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1037', 'source': 'Mako', 'type': 'sent', 'target': 'Event_VesselMovement_418'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1ba30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710066' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:434' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1047', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_451'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966395777' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:897' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1048', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Collaborate_455'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710071' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:439' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1050', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_462'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710073' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:441' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1054', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_467'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7f40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710447' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:815' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1069', 'source': 'Mako', 'type': 'sent', 'target': 'Event_VesselMovement_495'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df74c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710089' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:457' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1057', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_496'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1cf70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710507' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:875' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1058', 'source': 'Mako', 'type': 'sent', 'target': 'Event_TourActivity_498'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710451' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:819' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1059', 'source': 'Mako', 'type': 'sent', 'target': 'Event_VesselMovement_516'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd11f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710452' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:820' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1061', 'source': 'Mako', 'type': 'sent', 'target': 'Event_VesselMovement_540'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710534' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:902' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1062', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Collaborate_542'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710115' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:483' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1064', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_543'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710117' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:485' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1066', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_545'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710453' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:821' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '977', 'source': 'Mako', 'type': 'sent', 'target': 'Event_VesselMovement_549'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x100c23700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710121' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:489' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1071', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_553'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710134' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:502' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1074', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_575'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710185' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:553' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1079', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_655'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf8b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710187' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:555' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1082', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_657'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710192' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:560' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1084', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_665'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034711c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710201' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:569' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1085', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_684'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710238' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:606' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1088', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_755'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710240' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:608' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1089', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_757'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c4c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709684' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:52' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1036', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Monitoring_803'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710273' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:641' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1092', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_809'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710509' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:877' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1094', 'source': 'Mako', 'type': 'sent', 'target': 'Event_TourActivity_814'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710277' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:645' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1095', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_815'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd67f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710329' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:697' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1098', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_898'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709698' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:66' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1100', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Monitoring_917'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd85e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710341' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:709' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1101', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_920'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710512' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:880' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1029', 'source': 'Mako', 'type': 'sent', 'target': 'Event_TourActivity_962'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c4f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710383' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:751' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1106', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Communication_989'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710497' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:865' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1107', 'source': 'Mako', 'type': 'sent', 'target': 'Event_Enforcement_998'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710472' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:840' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '961', 'source': 'Mako', 'type': 'sent', 'target': 'Event_VesselMovement_1000'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709818' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:186' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1111', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_24'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bd30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709896' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:264' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1115', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_167'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd87f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710478' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:846' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1110', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Enforcement_177'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bcd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709925' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:293' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1122', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_225'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709926' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:294' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1123', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_226'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bd30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710433' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:801' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1124', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_VesselMovement_242'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709652' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:20' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1125', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Monitoring_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9c10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709943' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:311' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1126', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_252'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddfee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709962' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:330' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1128', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_287'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966394906' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:26' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1132', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Monitoring_383'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e089a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710028' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:396' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1134', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_386'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710053' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:421' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1136', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_428'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08f40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710083' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:451' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1138', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_482'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9d30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710085' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:453' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1140', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_487'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e089a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709663' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:31' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1141', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Monitoring_490'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710087' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:455' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1143', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_491'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8dc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710455' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:823' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1119', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_VesselMovement_569'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7e50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710132' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:500' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1147', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_572'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e089a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710135' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:503' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1149', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_576'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de83a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710152' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:520' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1151', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_603'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710160' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:528' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1155', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_614'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fd60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710161' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:529' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1158', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_616'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e089a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710165' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:533' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1163', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_623'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710458' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:826' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1164', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_VesselMovement_624'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710413' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:781' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1165', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Assessment_625'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710538' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:906' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1166', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Collaborate_626'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9c10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710414' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:782' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1159', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Assessment_628'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce93d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710167' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:535' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1169', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_630'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de73d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710188' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:556' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1171', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_660'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709669' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:37' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1172', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Monitoring_661'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710189' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:557' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1173', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_662'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709670' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:38' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1175', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Monitoring_678'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710199' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:567' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1178', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_681'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e080a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966394920' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:40' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1179', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Monitoring_690'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966395664' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:784' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1180', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Assessment_691'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709675' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:43' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1181', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Monitoring_709'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7d90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710213' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:581' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1183', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_710'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709676' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:44' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1184', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Monitoring_716'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710230' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:598' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1186', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_741'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710232' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:600' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1188', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_744'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710268' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:636' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1191', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_801'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710287' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:655' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1194', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_828'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff9d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709687' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:55' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1201', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Monitoring_856'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710306' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:674' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1200', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_857'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de71c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710317' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:685' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1203', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_877'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc89d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710327' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:695' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1204', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_895'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710330' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:698' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1205', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_899'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10346cfa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966394938' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:58' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1206', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Monitoring_900'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0ec70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710340' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:708' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1209', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_919'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff550>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709699' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:67' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1210', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Monitoring_922'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709703' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:71' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1211', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Monitoring_934'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710357' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:725' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1212', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_945'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e2b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709708' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:76' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1189', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Monitoring_946'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff550>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710358' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:726' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1216', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_949'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709737' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:105' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1217', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Monitoring_967'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710371' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:739' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1222', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Communication_970'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709755' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:123' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1223', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Monitoring_971'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb01f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710545' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:913' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1224', 'source': 'Reef_Guardian', 'type': 'sent', 'target': 'Event_Collaborate_972'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709637' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:5' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1228', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_Monitoring_71'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd63d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709638' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1230', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_Monitoring_73'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709841' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:209' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1231', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_Communication_76'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb01f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966395763' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:883' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1232', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_Collaborate_82'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1cb20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709858' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:226' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1236', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_Communication_110'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc89d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709860' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:228' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1238', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_Communication_112'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710432' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:800' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1239', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_VesselMovement_210'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709917' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:285' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1240', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_Communication_211'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709983' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:351' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1241', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_Communication_325'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710046' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:414' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1242', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_Communication_417'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df70d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710057' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:425' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1245', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_Communication_436'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10347c0a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966394911' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:31' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1246', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_Monitoring_490'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd13a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710129' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:497' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1247', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_Communication_566'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cb03a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710144' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:512' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1248', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_Communication_591'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966394915' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:35' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1249', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_Monitoring_608'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966395660' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:780' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1250', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_Assessment_609'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966394933' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:53' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1254', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_Monitoring_829'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126858ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710423' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:791' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1255', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_Assessment_837'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb04c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710292' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:660' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1257', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_Communication_838'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10346cf40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710316' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:684' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1259', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_Communication_875'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709688' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:56' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1253', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_Monitoring_878'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7c10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710318' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:686' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1262', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_Communication_879'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf4c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709693' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:61' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1263', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_Monitoring_909'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10346cf40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710365' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:733' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1265', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_Communication_961'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b8e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709776' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:144' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1244', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_Monitoring_978'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710375' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:743' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1267', 'source': 'Horizon', 'type': 'sent', 'target': 'Event_Communication_979'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1caf0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709641' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:9' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1268', 'source': 'Seawatch', 'type': 'sent', 'target': 'Event_Monitoring_83'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddfe80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966395681' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:801' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1269', 'source': 'Seawatch', 'type': 'sent', 'target': 'Event_VesselMovement_242'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b712e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966394900' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:20' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1270', 'source': 'Seawatch', 'type': 'sent', 'target': 'Event_Monitoring_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966394918' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:38' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1271', 'source': 'Seawatch', 'type': 'sent', 'target': 'Event_Monitoring_678'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c7c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710198' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:566' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1273', 'source': 'Seawatch', 'type': 'sent', 'target': 'Event_Communication_679'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf9d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710421' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:789' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1275', 'source': 'Seawatch', 'type': 'sent', 'target': 'Event_Assessment_786'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710260' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:628' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1276', 'source': 'Seawatch', 'type': 'sent', 'target': 'Event_Communication_787'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710263' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:631' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1277', 'source': 'Seawatch', 'type': 'sent', 'target': 'Event_Communication_793'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966394941' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:61' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1278', 'source': 'Seawatch', 'type': 'sent', 'target': 'Event_Monitoring_909'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8be0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966394951' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:71' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1279', 'source': 'Seawatch', 'type': 'sent', 'target': 'Event_Monitoring_934'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709642' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:10' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1281', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Monitoring_105'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966395764' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:884' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1284', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Collaborate_108'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709857' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:225' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1286', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Communication_109'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8be0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709859' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:227' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1288', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Communication_111'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709650' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:18' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1289', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Monitoring_208'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc30d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709916' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:284' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1291', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Communication_209'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf7f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157426203745847554' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:801' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1292', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_VesselMovement_242'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce97f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159678003559532802' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:20' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1293', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Monitoring_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709660' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:28' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1294', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Monitoring_414'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710045' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:413' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1296', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Communication_415'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966395706' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:826' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1297', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_VesselMovement_624'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966395661' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:781' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1298', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Assessment_625'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7f40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966395786' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:906' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1299', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Collaborate_626'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710166' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:534' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1301', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Communication_627'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710485' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:853' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1303', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Enforcement_666'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710461' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:829' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1306', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_VesselMovement_670'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966394924' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:44' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1307', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Monitoring_716'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710225' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:593' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1309', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Communication_731'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71d30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710226' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:594' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1312', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Communication_733'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf9d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710228' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:596' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1317', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Communication_737'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710231' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:599' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1322', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Communication_742'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710235' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:603' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1328', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Communication_751'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709679' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:47' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1326', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Monitoring_752'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fdf0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966394947' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:67' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1333', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Monitoring_922'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709700' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:68' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1334', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Monitoring_929'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710469' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:837' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1331', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_VesselMovement_931'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709702' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:70' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1337', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Monitoring_932'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6922033726780080199' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:71' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1339', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Monitoring_934'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710494' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:862' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1341', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Enforcement_952'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08b50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710364' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:732' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1344', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Communication_960'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7550>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966395003' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:123' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1345', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Monitoring_971'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0eb20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966395793' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:913' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1346', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Collaborate_972'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034710a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710372' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:740' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1349', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Communication_974'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710373' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:741' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1351', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Communication_976'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710374' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:742' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1353', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Communication_977'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e080a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709788' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:156' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1342', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Monitoring_995'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710426' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:794' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1315', 'source': 'EcoVigil', 'type': 'sent', 'target': 'Event_Assessment_996'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709839' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:207' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1357', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Communication_69'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709639' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:7' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1358', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Monitoring_74'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709842' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:210' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1359', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Communication_79'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966395646' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:766' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1361', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Assessment_172'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966394896' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:16' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1362', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Monitoring_173'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710480' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:848' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1363', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Enforcement_193'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709918' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:286' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1365', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Communication_213'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157426203745847555' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:801' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1367', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_VesselMovement_242'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159678003559532803' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:20' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1368', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Monitoring_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709655' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:23' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1382', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Monitoring_266'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de76d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709949' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:317' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1370', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Communication_267'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc89d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709951' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:319' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1373', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Communication_270'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709952' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:320' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1375', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Communication_272'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709968' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:336' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1377', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Communication_299'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709980' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:348' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1378', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Communication_320'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966394907' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:27' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1379', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Monitoring_410'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd61c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710056' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:424' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1383', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Communication_435'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710445' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:813' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1386', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_VesselMovement_483'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709662' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:30' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1387', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Monitoring_484'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710084' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:452' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1389', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Communication_485'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710454' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:822' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1390', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_VesselMovement_563'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08eb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710128' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:496' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1393', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Communication_565'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966395657' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:777' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1394', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Assessment_567'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd15e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710133' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:501' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1397', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Communication_574'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd84f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710195' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:563' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1400', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Communication_674'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcfe20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710197' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:565' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1404', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Communication_677'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710486' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:854' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1405', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Enforcement_693'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e261c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966394930' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:50' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1408', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Monitoring_777'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710300' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:668' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1410', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Communication_849'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710328' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:696' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1413', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Communication_897'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710468' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:836' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1414', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_VesselMovement_904'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6922033726780080189' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:61' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1419', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Monitoring_909'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709695' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:63' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1420', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Monitoring_911'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710338' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:706' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1423', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Communication_914'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6922033726780080195' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:67' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1424', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Monitoring_922'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6924285526593765447' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:71' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1425', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Monitoring_934'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e338e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710369' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:737' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1426', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Communication_965'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1cfd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710425' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:793' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1421', 'source': 'Sentinel', 'type': 'sent', 'target': 'Event_Assessment_973'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf3a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710503' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2308' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:871' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1428', 'source': 'Osprey', 'type': 'sent', 'target': 'Event_TourActivity_96'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd82b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709851' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2308' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:219' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1430', 'source': 'Osprey', 'type': 'sent', 'target': 'Event_Communication_97'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x103476310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709877' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2308' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:245' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1431', 'source': 'Osprey', 'type': 'sent', 'target': 'Event_Communication_136'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710505' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2308' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:873' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1432', 'source': 'Osprey', 'type': 'sent', 'target': 'Event_TourActivity_140'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e266a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709879' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2308' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:247' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1433', 'source': 'Osprey', 'type': 'sent', 'target': 'Event_Communication_141'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33280>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155174403932162308' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2308' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:801' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1434', 'source': 'Osprey', 'type': 'sent', 'target': 'Event_VesselMovement_242'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157426203745847556' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2308' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:20' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1435', 'source': 'Osprey', 'type': 'sent', 'target': 'Event_Monitoring_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710184' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2308' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:552' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1437', 'source': 'Osprey', 'type': 'sent', 'target': 'Event_Communication_654'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf8b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710463' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2308' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:831' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1438', 'source': 'Osprey', 'type': 'sent', 'target': 'Event_VesselMovement_806'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710508' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2308' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:876' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1436', 'source': 'Osprey', 'type': 'sent', 'target': 'Event_TourActivity_807'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710272' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2308' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:640' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1441', 'source': 'Osprey', 'type': 'sent', 'target': 'Event_Communication_808'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710510' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2308' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:878' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1442', 'source': 'Osprey', 'type': 'sent', 'target': 'Event_TourActivity_816'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf8b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710278' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2308' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:646' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1444', 'source': 'Osprey', 'type': 'sent', 'target': 'Event_Communication_817'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152922604118477061' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2309' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:263' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1445', 'source': 'Defender', 'type': 'sent', 'target': 'Event_Communication_165'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709647' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2309' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:15' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1446', 'source': 'Defender', 'type': 'sent', 'target': 'Event_Monitoring_168'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c3d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709897' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2309' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:265' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1447', 'source': 'Defender', 'type': 'sent', 'target': 'Event_Communication_169'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155174403932162309' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2309' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:801' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1448', 'source': 'Defender', 'type': 'sent', 'target': 'Event_VesselMovement_242'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df75e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157426203745847557' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2309' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:20' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1449', 'source': 'Defender', 'type': 'sent', 'target': 'Event_Monitoring_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709671' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2309' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:39' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1450', 'source': 'Defender', 'type': 'sent', 'target': 'Event_Monitoring_688'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ffa00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710205' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2309' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:573' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1452', 'source': 'Defender', 'type': 'sent', 'target': 'Event_Communication_689'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710488' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2309' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:856' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1453', 'source': 'Defender', 'type': 'sent', 'target': 'Event_Enforcement_769'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710305' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2309' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:673' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1454', 'source': 'Defender', 'type': 'sent', 'target': 'Event_Communication_855'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3a90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159678003559532805' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2309' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:71' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1455', 'source': 'Defender', 'type': 'sent', 'target': 'Event_Monitoring_934'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ffa00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710388' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2309' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:756' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1456', 'source': 'Defender', 'type': 'sent', 'target': 'Event_Communication_999'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709928' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2310' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:296' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1457', 'source': 'Northern_Light', 'type': 'sent', 'target': 'Event_Communication_228'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de72e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709930' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2310' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:298' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1458', 'source': 'Northern_Light', 'type': 'sent', 'target': 'Event_Communication_230'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709933' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2310' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:301' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1460', 'source': 'Northern_Light', 'type': 'sent', 'target': 'Event_Communication_234'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd11f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710460' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2310' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:828' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1461', 'source': 'Northern_Light', 'type': 'sent', 'target': 'Event_VesselMovement_634'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc35b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710170' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2310' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:538' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1462', 'source': 'Northern_Light', 'type': 'sent', 'target': 'Event_Communication_635'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709822' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:190' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1468', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Communication_32'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709887' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:255' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1470', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Communication_153'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fa00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709889' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:257' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1472', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Communication_158'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc35b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709919' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:287' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1475', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Communication_214'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709920' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:288' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1476', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Communication_216'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710438' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:806' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1480', 'source': 'Remora', 'type': 'sent', 'target': 'Event_VesselMovement_326'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x103476310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709995' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:363' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1483', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Communication_341'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966395687' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:807' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1484', 'source': 'Remora', 'type': 'sent', 'target': 'Event_VesselMovement_344'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710030' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:398' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1486', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Communication_388'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08d90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966395774' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:894' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1487', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Collaborate_422'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e7f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966395775' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:895' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1489', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Collaborate_424'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710051' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:419' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1491', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Communication_425'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157426203745847559' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:897' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1492', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Collaborate_455'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710407' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:775' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1466', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Assessment_492'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710088' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:456' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1495', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Communication_493'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f3d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710446' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:814' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1496', 'source': 'Remora', 'type': 'sent', 'target': 'Event_VesselMovement_494'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08eb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966395755' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:875' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1498', 'source': 'Remora', 'type': 'sent', 'target': 'Event_TourActivity_498'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3afd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710090' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:458' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1500', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Communication_499'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b8e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710449' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:817' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1516', 'source': 'Remora', 'type': 'sent', 'target': 'Event_VesselMovement_509'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f4c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710450' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:818' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1497', 'source': 'Remora', 'type': 'sent', 'target': 'Event_VesselMovement_510'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710098' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:466' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1505', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Communication_515'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966395699' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:819' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1506', 'source': 'Remora', 'type': 'sent', 'target': 'Event_VesselMovement_516'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9cd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919781926966395700' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:820' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1507', 'source': 'Remora', 'type': 'sent', 'target': 'Event_VesselMovement_540'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e7c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710536' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:904' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1508', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Collaborate_554'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0eb80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710122' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:490' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1510', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Communication_555'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e080a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710123' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:491' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1512', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Communication_556'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710537' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:905' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1513', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Collaborate_557'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710124' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:492' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1514', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Communication_558'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcfc70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710154' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:522' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1518', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Communication_605'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x100c23700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710191' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:559' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1520', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Communication_664'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bb50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710542' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:910' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1522', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Collaborate_760'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08eb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710243' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:611' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1525', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Communication_761'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710276' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:644' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1527', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Communication_812'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de87c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710283' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:651' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1529', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Communication_823'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1ba30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710464' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:832' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1530', 'source': 'Remora', 'type': 'sent', 'target': 'Event_VesselMovement_843'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc56d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710301' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:669' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1532', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Communication_850'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710314' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:682' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1535', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Communication_871'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710315' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:683' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1537', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Communication_873'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710467' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:835' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1545', 'source': 'Remora', 'type': 'sent', 'target': 'Event_VesselMovement_892'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc56d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710511' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:879' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1546', 'source': 'Remora', 'type': 'sent', 'target': 'Event_TourActivity_938'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710354' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:722' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1540', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Communication_939'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709704' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:72' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1542', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Monitoring_941'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b712e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709707' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:75' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1543', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Monitoring_942'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710356' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:724' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1544', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Communication_943'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709711' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:79' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1547', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Monitoring_957'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710363' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:731' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1549', 'source': 'Remora', 'type': 'sent', 'target': 'Event_Communication_958'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710465' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2312' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:833' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1555', 'source': 'Knowles', 'type': 'sent', 'target': 'Event_VesselMovement_883'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df76d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710322' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2312' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:690' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1557', 'source': 'Knowles', 'type': 'sent', 'target': 'Event_Communication_886'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710466' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2312' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:834' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1558', 'source': 'Knowles', 'type': 'sent', 'target': 'Event_VesselMovement_887'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710382' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2312' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:750' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1561', 'source': 'Knowles', 'type': 'sent', 'target': 'Event_Communication_987'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710389' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2312' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:757' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1563', 'source': 'Knowles', 'type': 'sent', 'target': 'Event_Communication_1001'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddfcd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710473' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2312' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:841' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1564', 'source': 'Knowles', 'type': 'sent', 'target': 'Event_VesselMovement_1002'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710390' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2312' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:758' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1565', 'source': 'Knowles', 'type': 'sent', 'target': 'Event_Communication_1003'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x100c23700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710506' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2313' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:874' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1566', 'source': 'Mariner_s_Dream', 'type': 'sent', 'target': 'Event_TourActivity_188'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08eb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710431' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2314' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:799' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1569', 'source': 'Recreational_Fishing_Boats', 'type': 'sent', 'target': 'Event_VesselMovement_190'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710500' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2317' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:868' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1575', 'source': 'Tourists', 'type': 'sent', 'target': 'Event_TourActivity_46'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709678' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2318' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:46' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1581', 'source': 'Conservation_Vessels', 'type': 'sent', 'target': 'Event_Monitoring_722'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710420' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2318' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:788' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1586', 'source': 'Conservation_Vessels', 'type': 'sent', 'target': 'Event_Assessment_765'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e280>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709681' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2318' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:49' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1587', 'source': 'Conservation_Vessels', 'type': 'sent', 'target': 'Event_Monitoring_766'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710474' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:842' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1594', 'source': 'Paackland_Harbor', 'type': 'sent', 'target': 'Event_Enforcement_29'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709821' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:189' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1595', 'source': 'Paackland_Harbor', 'type': 'sent', 'target': 'Event_Communication_30'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709823' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:191' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1597', 'source': 'Paackland_Harbor', 'type': 'sent', 'target': 'Event_Communication_35'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709829' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:197' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1598', 'source': 'Paackland_Harbor', 'type': 'sent', 'target': 'Event_Communication_48'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ffac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709645' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:13' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1599', 'source': 'Paackland_Harbor', 'type': 'sent', 'target': 'Event_Monitoring_148'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709884' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:252' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1600', 'source': 'Paackland_Harbor', 'type': 'sent', 'target': 'Event_Communication_149'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709886' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:254' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1601', 'source': 'Paackland_Harbor', 'type': 'sent', 'target': 'Event_Communication_152'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709908' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:276' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1602', 'source': 'Paackland_Harbor', 'type': 'sent', 'target': 'Event_Communication_197'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709923' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:291' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1604', 'source': 'Paackland_Harbor', 'type': 'sent', 'target': 'Event_Communication_222'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddfbe0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709948' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:316' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1605', 'source': 'Paackland_Harbor', 'type': 'sent', 'target': 'Event_Communication_264'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6dc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710000' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:368' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1607', 'source': 'Paackland_Harbor', 'type': 'sent', 'target': 'Event_Communication_350'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710002' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:370' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1608', 'source': 'Paackland_Harbor', 'type': 'sent', 'target': 'Event_Communication_353'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33970>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710023' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:391' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1609', 'source': 'Paackland_Harbor', 'type': 'sent', 'target': 'Event_Communication_378'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710029' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:397' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1610', 'source': 'Paackland_Harbor', 'type': 'sent', 'target': 'Event_Communication_387'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710126' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:494' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1611', 'source': 'Paackland_Harbor', 'type': 'sent', 'target': 'Event_Communication_560'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1cd30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710186' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:554' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1612', 'source': 'Paackland_Harbor', 'type': 'sent', 'target': 'Event_Communication_656'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd64c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710207' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:575' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1613', 'source': 'Paackland_Harbor', 'type': 'sent', 'target': 'Event_Communication_694'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x103471700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710334' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:702' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1614', 'source': 'Paackland_Harbor', 'type': 'sent', 'target': 'Event_Communication_905'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf0d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709850' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2320' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:218' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1617', 'source': 'Haacklee_Harbor', 'type': 'sent', 'target': 'Event_Communication_95'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff2b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709972' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2320' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:340' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1618', 'source': 'Haacklee_Harbor', 'type': 'sent', 'target': 'Event_Communication_305'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26d90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710402' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2320' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:770' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1619', 'source': 'Haacklee_Harbor', 'type': 'sent', 'target': 'Event_Assessment_329'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf9a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709986' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2320' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:354' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1620', 'source': 'Haacklee_Harbor', 'type': 'sent', 'target': 'Event_Communication_330'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb04c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709988' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2320' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:356' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1621', 'source': 'Haacklee_Harbor', 'type': 'sent', 'target': 'Event_Communication_332'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e269a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710193' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2320' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:561' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1622', 'source': 'Haacklee_Harbor', 'type': 'sent', 'target': 'Event_Communication_668'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26d90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710321' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2320' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:689' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1623', 'source': 'Haacklee_Harbor', 'type': 'sent', 'target': 'Event_Communication_884'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08eb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710323' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2320' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:691' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1624', 'source': 'Haacklee_Harbor', 'type': 'sent', 'target': 'Event_Communication_888'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8cd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709814' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:182' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1625', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_17'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd83a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709820' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:188' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1626', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_28'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709831' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:199' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1627', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_51'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33040>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709853' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:221' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1628', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_100'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcfe20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709864' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:232' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1629', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_118'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709883' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:251' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1630', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_147'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709906' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:274' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1631', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_191'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e080a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709969' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:337' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1632', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_301'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709971' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:339' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1633', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_304'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8bb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709984' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:352' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1634', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_327'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3cd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709994' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:362' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1635', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_340'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce91f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152709997' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:365' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1637', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_345'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc53a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710032' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:400' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1638', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_390'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710034' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:402' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1639', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_394'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08f10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710065' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:433' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1640', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_449'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a1f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710067' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:435' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1641', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_453'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b280>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710091' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:459' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1642', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_501'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710137' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:505' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1643', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_579'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710168' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:536' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1644', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_632'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710171' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:539' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1646', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_636'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710177' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:545' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1647', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_642'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd88e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710179' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:547' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1648', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_645'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08a90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710208' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:576' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1650', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_696'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710489' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:857' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1649', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Enforcement_784'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710259' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:627' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1652', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_785'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710261' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:629' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1653', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_789'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de73a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710324' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:692' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1654', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_890'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e8b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710495' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:863' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1655', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Enforcement_992'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x103471700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710385' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:753' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': False, 'id': '1657', 'source': 'Himark_Harbor', 'type': 'sent', 'target': 'Event_Communication_993'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917530127152710493' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2347' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:861' labels=frozenset() properties={}>) type='sent' properties={'is_inferred': True, 'id': '1658', 'source': 'Port_Security', 'type': 'sent', 'target': 'Event_Enforcement_947'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102528' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:0' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2327' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1660', 'source': 'Event_Monitoring_0', 'type': 'received', 'target': 'Eastern_Coastline'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e8b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102529' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1740', 'source': 'Event_Monitoring_33', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fc70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155175503443787777' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2325' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1741', 'source': 'Event_Monitoring_33', 'type': 'received', 'target': 'Protected_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7f40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919783026478024978' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3029', 'source': 'Event_Monitoring_38', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102531' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:3' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1805', 'source': 'Event_Monitoring_60', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e8b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155175503443787779' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:3' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2325' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1806', 'source': 'Event_Monitoring_60', 'type': 'received', 'target': 'Protected_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102532' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:4' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2338' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1828', 'source': 'Event_Monitoring_68', 'type': 'received', 'target': 'Western_Boundary'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3ae50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155175503443787780' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:4' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2325' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1829', 'source': 'Event_Monitoring_68', 'type': 'received', 'target': 'Protected_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb04f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102533' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:5' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2338' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1834', 'source': 'Event_Monitoring_71', 'type': 'received', 'target': 'Western_Boundary'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf2e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102534' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2339' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1840', 'source': 'Event_Monitoring_73', 'type': 'received', 'target': 'Eastern_Boundary'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc57c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102535' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:7' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2338' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1841', 'source': 'Event_Monitoring_74', 'type': 'received', 'target': 'Western_Boundary'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102536' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:8' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2338' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1851', 'source': 'Event_Monitoring_77', 'type': 'received', 'target': 'Western_Boundary'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0ec40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155175503443787784' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:8' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1852', 'source': 'Event_Monitoring_77', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102537' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:9' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1859', 'source': 'Event_Monitoring_83', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102538' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:10' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2339' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1912', 'source': 'Event_Monitoring_105', 'type': 'received', 'target': 'Eastern_Boundary'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102539' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:11' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1974', 'source': 'Event_Monitoring_129', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a4c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102540' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:12' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2325' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1994', 'source': 'Event_Monitoring_133', 'type': 'received', 'target': 'Protected_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8e20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102541' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:13' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2029', 'source': 'Event_Monitoring_148', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102542' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:14' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2063', 'source': 'Event_Monitoring_164', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f3d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155175503443787790' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:14' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2342' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2064', 'source': 'Event_Monitoring_164', 'type': 'received', 'target': 'Restricted_Zone'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf3a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102543' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:15' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2070', 'source': 'Event_Monitoring_168', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8e20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102545' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:17' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2258', 'source': 'Event_Monitoring_192', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102546' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:18' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2323' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2180', 'source': 'Event_Monitoring_208', 'type': 'received', 'target': 'Restricted_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb04f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102547' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:19' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2342' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2244', 'source': 'Event_Monitoring_232', 'type': 'received', 'target': 'Restricted_Zone'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf3a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102549' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:21' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2332' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2296', 'source': 'Event_Monitoring_253', 'type': 'received', 'target': 'E7'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1e80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102550' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:22' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2332' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2295', 'source': 'Event_Monitoring_255', 'type': 'received', 'target': 'E7'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8040>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102551' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:23' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2791', 'source': 'Event_Monitoring_266', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce91f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102552' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:24' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2391', 'source': 'Event_Monitoring_286', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf9d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102553' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:25' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2344' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2567', 'source': 'Event_Monitoring_358', 'type': 'received', 'target': 'South_Dock'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c5b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102556' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:28' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2325' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2730', 'source': 'Event_Monitoring_414', 'type': 'received', 'target': 'Protected_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8af0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102557' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:29' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2320' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2813', 'source': 'Event_Monitoring_444', 'type': 'received', 'target': 'Haacklee_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd64c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102558' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:30' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2340' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2911', 'source': 'Event_Monitoring_484', 'type': 'received', 'target': 'Southern_Boundary'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102560' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:32' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3335', 'source': 'Event_Monitoring_530', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff7c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102561' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:33' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3036', 'source': 'Event_Monitoring_534', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102562' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:34' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4269', 'source': 'Event_Monitoring_595', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102564' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:36' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3003', 'source': 'Event_Monitoring_631', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102565' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:37' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2336' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3368', 'source': 'Event_Monitoring_661', 'type': 'received', 'target': 'Western_quadrant'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c7f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102567' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:39' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2339' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3437', 'source': 'Event_Monitoring_688', 'type': 'received', 'target': 'Eastern_Boundary'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102570' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:42' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3476', 'source': 'Event_Monitoring_704', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26f10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102571' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:43' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2335' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3495', 'source': 'Event_Monitoring_709', 'type': 'received', 'target': 'Eastern_quadrant'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102574' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:46' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2276', 'source': 'Event_Monitoring_722', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102575' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:47' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2333' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3598', 'source': 'Event_Monitoring_752', 'type': 'received', 'target': 'Northern_quadrant'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc35b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102577' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:49' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2323' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3662', 'source': 'Event_Monitoring_766', 'type': 'received', 'target': 'Restricted_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102579' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:51' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2335' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3743', 'source': 'Event_Monitoring_797', 'type': 'received', 'target': 'Eastern_quadrant'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc88e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102580' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:52' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2735', 'source': 'Event_Monitoring_803', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4ed00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102582' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:54' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2323' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3861', 'source': 'Event_Monitoring_835', 'type': 'received', 'target': 'Restricted_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102583' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:55' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2334' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3975', 'source': 'Event_Monitoring_856', 'type': 'received', 'target': 'Southern_quadrant'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102584' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:56' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2336' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3500', 'source': 'Event_Monitoring_878', 'type': 'received', 'target': 'Western_quadrant'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8df0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102591' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:63' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2336' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4061', 'source': 'Event_Monitoring_911', 'type': 'received', 'target': 'Western_quadrant'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd83a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102594' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:66' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2338' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4078', 'source': 'Event_Monitoring_917', 'type': 'received', 'target': 'Western_Boundary'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc81f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102596' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:68' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2342' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4106', 'source': 'Event_Monitoring_929', 'type': 'received', 'target': 'Restricted_Zone'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1cee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102598' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:70' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2336' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4116', 'source': 'Event_Monitoring_932', 'type': 'received', 'target': 'Western_quadrant'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102600' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:72' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2318' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4140', 'source': 'Event_Monitoring_941', 'type': 'received', 'target': 'Conservation_Vessels'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf3a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102603' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:75' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4141', 'source': 'Event_Monitoring_942', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33eb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102604' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:76' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3748', 'source': 'Event_Monitoring_946', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102607' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:79' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2342' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4182', 'source': 'Event_Monitoring_957', 'type': 'received', 'target': 'Restricted_Zone'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102633' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:105' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2325' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4210', 'source': 'Event_Monitoring_967', 'type': 'received', 'target': 'Protected_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf3a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102672' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:144' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2777', 'source': 'Event_Monitoring_978', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102684' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:156' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4190', 'source': 'Event_Monitoring_995', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3e80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102685' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:157' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1661', 'source': 'Event_Communication_1', 'type': 'received', 'target': 'The_Intern'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102694' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:166' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1664', 'source': 'Event_Communication_2', 'type': 'received', 'target': 'The_Lookout'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102697' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:169' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2276' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1666', 'source': 'Event_Communication_3', 'type': 'received', 'target': 'Sam'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102699' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:171' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1669', 'source': 'Event_Communication_5', 'type': 'received', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102700' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:172' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1673', 'source': 'Event_Communication_6', 'type': 'received', 'target': 'Boss'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102701' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:173' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1678', 'source': 'Event_Communication_7', 'type': 'received', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102702' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:174' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1682', 'source': 'Event_Communication_8', 'type': 'received', 'target': 'Boss'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcfc70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102703' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:175' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1683', 'source': 'Event_Communication_9', 'type': 'received', 'target': 'The_Middleman'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3280>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102704' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:176' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1684', 'source': 'Event_Communication_10', 'type': 'received', 'target': 'Boss'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102705' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:177' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1685', 'source': 'Event_Communication_11', 'type': 'received', 'target': 'The_Middleman'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102706' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:178' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1686', 'source': 'Event_Communication_12', 'type': 'received', 'target': 'Boss'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351be20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102707' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:179' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1688', 'source': 'Event_Communication_13', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102708' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:180' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1691', 'source': 'Event_Communication_15', 'type': 'received', 'target': 'Serenity'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcfc70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102709' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:181' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1694', 'source': 'Event_Communication_16', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3aee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102710' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:182' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1698', 'source': 'Event_Communication_17', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd60d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102711' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:183' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1704', 'source': 'Event_Communication_20', 'type': 'received', 'target': 'Davis'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e338e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102712' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:184' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1710', 'source': 'Event_Communication_21', 'type': 'received', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102713' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:185' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1714', 'source': 'Event_Communication_22', 'type': 'received', 'target': 'The_Middleman'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7a90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102714' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:186' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1717', 'source': 'Event_Communication_24', 'type': 'received', 'target': 'Serenity'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bbb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102715' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:187' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1721', 'source': 'Event_Communication_26', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd14c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102716' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:188' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1725', 'source': 'Event_Communication_28', 'type': 'received', 'target': 'Serenity'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e083d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102717' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:189' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1730', 'source': 'Event_Communication_30', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102718' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:190' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1736', 'source': 'Event_Communication_32', 'type': 'received', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9c10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917531226664339703' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:191' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1747', 'source': 'Event_Communication_35', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102720' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:192' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1756', 'source': 'Event_Communication_37', 'type': 'received', 'target': 'Liam_Thorne'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102721' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:193' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1763', 'source': 'Event_Communication_39', 'type': 'received', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e2b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102722' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:194' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1766', 'source': 'Event_Communication_40', 'type': 'received', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102723' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:195' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1771', 'source': 'Event_Communication_43', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0b50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102724' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:196' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1778', 'source': 'Event_Communication_45', 'type': 'received', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9d90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102725' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:197' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1784', 'source': 'Event_Communication_48', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102726' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:198' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1789', 'source': 'Event_Communication_50', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102727' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:199' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2300' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1791', 'source': 'Event_Communication_51', 'type': 'received', 'target': 'Marlin'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a6a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102728' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:200' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1793', 'source': 'Event_Communication_53', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9d90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102729' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:201' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2300' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1795', 'source': 'Event_Communication_54', 'type': 'received', 'target': 'Marlin'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102730' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:202' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1800', 'source': 'Event_Communication_59', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4ecd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102731' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:203' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1811', 'source': 'Event_Communication_62', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102732' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:204' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2298' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1818', 'source': 'Event_Communication_64', 'type': 'received', 'target': 'Sailor_Shifts_Team'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bf70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102733' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:205' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2281' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1822', 'source': 'Event_Communication_66', 'type': 'received', 'target': 'Samantha_Blake'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb05b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102734' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:206' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1826', 'source': 'Event_Communication_67', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102735' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:207' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1830', 'source': 'Event_Communication_69', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102736' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:208' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1836', 'source': 'Event_Communication_72', 'type': 'received', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102737' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:209' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1845', 'source': 'Event_Communication_76', 'type': 'received', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e086a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102738' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:210' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1854', 'source': 'Event_Communication_79', 'type': 'received', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102739' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:211' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1863', 'source': 'Event_Communication_85', 'type': 'received', 'target': 'Seawatch'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102740' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:212' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2276' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1868', 'source': 'Event_Communication_87', 'type': 'received', 'target': 'Sam'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b9d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102741' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:213' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1872', 'source': 'Event_Communication_89', 'type': 'received', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f3d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102742' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:214' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1875', 'source': 'Event_Communication_90', 'type': 'received', 'target': 'The_Intern'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102743' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:215' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1876', 'source': 'Event_Communication_91', 'type': 'received', 'target': 'The_Intern'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102744' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:216' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1879', 'source': 'Event_Communication_92', 'type': 'received', 'target': 'The_Lookout'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e1c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102745' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:217' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2276' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1883', 'source': 'Event_Communication_94', 'type': 'received', 'target': 'Sam'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc81f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102746' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:218' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2308' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1886', 'source': 'Event_Communication_95', 'type': 'received', 'target': 'Osprey'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc58b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102747' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:219' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1890', 'source': 'Event_Communication_97', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7a90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102748' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:220' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1895', 'source': 'Event_Communication_99', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce91f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102749' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:221' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1899', 'source': 'Event_Communication_100', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102750' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:222' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2281' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1904', 'source': 'Event_Communication_102', 'type': 'received', 'target': 'Samantha_Blake'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102751' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:223' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2298' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1909', 'source': 'Event_Communication_103', 'type': 'received', 'target': 'Sailor_Shifts_Team'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48bb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102752' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:224' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1915', 'source': 'Event_Communication_106', 'type': 'received', 'target': 'EcoVigil'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc53a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102753' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:225' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1922', 'source': 'Event_Communication_109', 'type': 'received', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1a90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102754' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:226' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1927', 'source': 'Event_Communication_110', 'type': 'received', 'target': 'EcoVigil'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102755' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:227' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1930', 'source': 'Event_Communication_111', 'type': 'received', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102756' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:228' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1933', 'source': 'Event_Communication_112', 'type': 'received', 'target': 'EcoVigil'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034710a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102757' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:229' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2298' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1935', 'source': 'Event_Communication_113', 'type': 'received', 'target': 'Sailor_Shifts_Team'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102758' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:230' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1939', 'source': 'Event_Communication_115', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf3d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102759' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:231' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2298' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1945', 'source': 'Event_Communication_117', 'type': 'received', 'target': 'Sailor_Shifts_Team'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce91f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102760' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:232' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1950', 'source': 'Event_Communication_118', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3acd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102761' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:233' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1953', 'source': 'Event_Communication_119', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3cd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102762' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:234' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1958', 'source': 'Event_Communication_120', 'type': 'received', 'target': 'Boss'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc57c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102763' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:235' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1962', 'source': 'Event_Communication_121', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102764' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:236' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2300' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1966', 'source': 'Event_Communication_123', 'type': 'received', 'target': 'Marlin'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf9d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102765' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:237' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1970', 'source': 'Event_Communication_124', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102766' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:238' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1972', 'source': 'Event_Communication_126', 'type': 'received', 'target': 'Clepper_Jensen'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd80a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102767' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:239' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1976', 'source': 'Event_Communication_128', 'type': 'received', 'target': 'Miranda_Jordan'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102768' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:240' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1982', 'source': 'Event_Communication_130', 'type': 'received', 'target': 'Clepper_Jensen'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc36a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102769' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:241' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1988', 'source': 'Event_Communication_131', 'type': 'received', 'target': 'Miranda_Jordan'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102770' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:242' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1992', 'source': 'Event_Communication_132', 'type': 'received', 'target': 'Miranda_Jordan'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102771' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:243' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '1997', 'source': 'Event_Communication_134', 'type': 'received', 'target': 'Clepper_Jensen'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102772' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:244' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2001', 'source': 'Event_Communication_135', 'type': 'received', 'target': 'Miranda_Jordan'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3acd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102773' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:245' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2002', 'source': 'Event_Communication_136', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff9d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102774' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:246' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2308' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2005', 'source': 'Event_Communication_139', 'type': 'received', 'target': 'Osprey'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd80a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102775' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:247' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2009', 'source': 'Event_Communication_141', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102776' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:248' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2013', 'source': 'Event_Communication_142', 'type': 'received', 'target': 'Rodriguez'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102777' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:249' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2017', 'source': 'Event_Communication_143', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53f40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102778' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:250' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2020', 'source': 'Event_Communication_145', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034fffa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102779' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:251' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2025', 'source': 'Event_Communication_147', 'type': 'received', 'target': 'Serenity'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102780' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:252' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2030', 'source': 'Event_Communication_149', 'type': 'received', 'target': 'Liam_Thorne'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102781' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:253' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2032', 'source': 'Event_Communication_150', 'type': 'received', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf0d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102782' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:254' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2034', 'source': 'Event_Communication_152', 'type': 'received', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3e80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102783' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:255' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2036', 'source': 'Event_Communication_153', 'type': 'received', 'target': 'Rodriguez'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33d60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102784' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:256' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2041', 'source': 'Event_Communication_156', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102785' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:257' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2050', 'source': 'Event_Communication_158', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7d60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102786' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:258' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2054', 'source': 'Event_Communication_159', 'type': 'received', 'target': 'The_Intern'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102787' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:259' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2057', 'source': 'Event_Communication_160', 'type': 'received', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102788' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:260' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2060', 'source': 'Event_Communication_161', 'type': 'received', 'target': 'The_Intern'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102789' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:261' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2061', 'source': 'Event_Communication_162', 'type': 'received', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102790' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:262' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2062', 'source': 'Event_Communication_163', 'type': 'received', 'target': 'The_Middleman'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8280>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102791' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:263' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2065', 'source': 'Event_Communication_165', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102792' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:264' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2309' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2068', 'source': 'Event_Communication_167', 'type': 'received', 'target': 'Defender'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc81f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102793' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:265' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2071', 'source': 'Event_Communication_169', 'type': 'received', 'target': 'Seawatch'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb09d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102794' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:266' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2074', 'source': 'Event_Communication_171', 'type': 'received', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102795' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:267' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2080', 'source': 'Event_Communication_175', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102796' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:268' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2084', 'source': 'Event_Communication_176', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd82b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102797' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:269' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2091', 'source': 'Event_Communication_179', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102798' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:270' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2101', 'source': 'Event_Communication_182', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102799' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:271' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2106', 'source': 'Event_Communication_183', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8eb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102800' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:272' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2110', 'source': 'Event_Communication_186', 'type': 'received', 'target': 'Liam_Thorne'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102801' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:273' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2117', 'source': 'Event_Communication_189', 'type': 'received', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08f10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102802' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:274' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2123', 'source': 'Event_Communication_191', 'type': 'received', 'target': 'Seawatch'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102803' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:275' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2132', 'source': 'Event_Communication_196', 'type': 'received', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102804' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:276' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2137', 'source': 'Event_Communication_197', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf4f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102805' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:277' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2142', 'source': 'Event_Communication_199', 'type': 'received', 'target': 'Boss'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a6a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102806' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:278' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2149', 'source': 'Event_Communication_201', 'type': 'received', 'target': 'Clepper_Jensen'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf9a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102807' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:279' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2158', 'source': 'Event_Communication_203', 'type': 'received', 'target': 'Miranda_Jordan'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de83a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102808' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2166', 'source': 'Event_Communication_204', 'type': 'received', 'target': 'Clepper_Jensen'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b3a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102809' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:281' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2171', 'source': 'Event_Communication_205', 'type': 'received', 'target': 'Miranda_Jordan'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fe20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102810' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2175', 'source': 'Event_Communication_206', 'type': 'received', 'target': 'Clepper_Jensen'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102811' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2178', 'source': 'Event_Communication_207', 'type': 'received', 'target': 'Miranda_Jordan'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33c10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102812' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:284' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2182', 'source': 'Event_Communication_209', 'type': 'received', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3aca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102813' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2187', 'source': 'Event_Communication_211', 'type': 'received', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fe20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102814' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2191', 'source': 'Event_Communication_213', 'type': 'received', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48a90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102815' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2194', 'source': 'Event_Communication_214', 'type': 'received', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102816' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2199', 'source': 'Event_Communication_216', 'type': 'received', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102817' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:289' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2204', 'source': 'Event_Communication_218', 'type': 'received', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4eaf0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102818' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2211', 'source': 'Event_Communication_221', 'type': 'received', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102819' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:291' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2218', 'source': 'Event_Communication_222', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd61f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102820' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:292' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2225', 'source': 'Event_Communication_224', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8eb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102821' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:293' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2230', 'source': 'Event_Communication_225', 'type': 'received', 'target': 'Serenity'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102822' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:294' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2234', 'source': 'Event_Communication_226', 'type': 'received', 'target': 'Serenity'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102823' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:295' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2237', 'source': 'Event_Communication_227', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddfa00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102824' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:296' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2238', 'source': 'Event_Communication_228', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b8e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102825' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:297' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2310' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2239', 'source': 'Event_Communication_229', 'type': 'received', 'target': 'Northern_Light'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e2e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102826' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:298' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2298' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2241', 'source': 'Event_Communication_230', 'type': 'received', 'target': 'Sailor_Shifts_Team'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102828' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:300' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2310' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2243', 'source': 'Event_Communication_231', 'type': 'received', 'target': 'Northern_Light'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de75b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102829' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:301' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2247', 'source': 'Event_Communication_234', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102830' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2310' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2254', 'source': 'Event_Communication_237', 'type': 'received', 'target': 'Northern_Light'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102831' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2261', 'source': 'Event_Communication_239', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb05b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102832' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:304' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2265', 'source': 'Event_Communication_240', 'type': 'received', 'target': 'Davis'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bdf0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102833' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:305' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2276' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2268', 'source': 'Event_Communication_244', 'type': 'received', 'target': 'Sam'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102835' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2274', 'source': 'Event_Communication_246', 'type': 'received', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102836' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:308' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2278', 'source': 'Event_Communication_248', 'type': 'received', 'target': 'Boss'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102837' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:309' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2284', 'source': 'Event_Communication_249', 'type': 'received', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102838' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:310' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2288', 'source': 'Event_Communication_250', 'type': 'received', 'target': 'The_Middleman'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102839' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2290', 'source': 'Event_Communication_252', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3e80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102840' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:312' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2293', 'source': 'Event_Communication_254', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b5b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102841' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:313' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2301', 'source': 'Event_Communication_258', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102842' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:314' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2307', 'source': 'Event_Communication_260', 'type': 'received', 'target': 'Davis'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102843' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:315' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2313', 'source': 'Event_Communication_262', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x103471700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102844' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:316' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2318', 'source': 'Event_Communication_264', 'type': 'received', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102845' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:317' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2322', 'source': 'Event_Communication_267', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bbb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102846' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:318' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2325', 'source': 'Event_Communication_268', 'type': 'received', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102847' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2329', 'source': 'Event_Communication_270', 'type': 'received', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de83a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102848' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:320' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2336', 'source': 'Event_Communication_272', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102849' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2343', 'source': 'Event_Communication_275', 'type': 'received', 'target': 'Boss'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102850' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:322' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2348', 'source': 'Event_Communication_277', 'type': 'received', 'target': 'The_Middleman'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f4c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102851' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:323' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2353', 'source': 'Event_Communication_278', 'type': 'received', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd64c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102852' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:324' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2356', 'source': 'Event_Communication_279', 'type': 'received', 'target': 'Boss'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102853' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:325' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2366', 'source': 'Event_Communication_280', 'type': 'received', 'target': 'Boss'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48cd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102854' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:326' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2376', 'source': 'Event_Communication_281', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102855' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:327' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2382', 'source': 'Event_Communication_282', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102856' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:328' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2386', 'source': 'Event_Communication_283', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102857' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:329' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2389', 'source': 'Event_Communication_285', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df76d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102858' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:330' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2300' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2393', 'source': 'Event_Communication_287', 'type': 'received', 'target': 'Marlin'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102859' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:331' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2397', 'source': 'Event_Communication_289', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102860' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:332' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2401', 'source': 'Event_Communication_291', 'type': 'received', 'target': 'Davis'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f4c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102861' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:333' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2406', 'source': 'Event_Communication_293', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102862' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:334' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2411', 'source': 'Event_Communication_295', 'type': 'received', 'target': 'Davis'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf9d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102863' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:335' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2415', 'source': 'Event_Communication_297', 'type': 'received', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33040>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102864' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:336' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2418', 'source': 'Event_Communication_299', 'type': 'received', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8c10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102865' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:337' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2422', 'source': 'Event_Communication_301', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1ca90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102866' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:338' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2425', 'source': 'Event_Communication_302', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8040>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102867' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:339' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2428', 'source': 'Event_Communication_304', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102868' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:340' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2430', 'source': 'Event_Communication_305', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102869' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:341' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2435', 'source': 'Event_Communication_309', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53af0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102870' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:342' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2443', 'source': 'Event_Communication_311', 'type': 'received', 'target': 'Liam_Thorne'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf4f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102871' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:343' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2447', 'source': 'Event_Communication_312', 'type': 'received', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102872' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:344' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2449', 'source': 'Event_Communication_313', 'type': 'received', 'target': 'Boss'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102873' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:345' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2453', 'source': 'Event_Communication_316', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102874' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:346' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2456', 'source': 'Event_Communication_317', 'type': 'received', 'target': 'The_Intern'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33e20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102875' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:347' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2458', 'source': 'Event_Communication_318', 'type': 'received', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102876' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:348' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2462', 'source': 'Event_Communication_320', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102877' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:349' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2466', 'source': 'Event_Communication_321', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e534f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102878' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:350' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2471', 'source': 'Event_Communication_323', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102879' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:351' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2477', 'source': 'Event_Communication_325', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102880' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:352' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2481', 'source': 'Event_Communication_327', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x103471700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102881' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:353' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2483', 'source': 'Event_Communication_328', 'type': 'received', 'target': 'Boss'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10347cdc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102882' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:354' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2486', 'source': 'Event_Communication_330', 'type': 'received', 'target': 'Nadia_Conti'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102883' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:355' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2320' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2490', 'source': 'Event_Communication_331', 'type': 'received', 'target': 'Haacklee_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102884' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:356' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2493', 'source': 'Event_Communication_332', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc88e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102885' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:357' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2495', 'source': 'Event_Communication_333', 'type': 'received', 'target': 'Nadia_Conti'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102886' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:358' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2496', 'source': 'Event_Communication_334', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102887' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:359' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2500', 'source': 'Event_Communication_336', 'type': 'received', 'target': 'Liam_Thorne'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102888' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:360' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2505', 'source': 'Event_Communication_338', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a9d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102889' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:361' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2508', 'source': 'Event_Communication_339', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33c10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102890' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:362' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2511', 'source': 'Event_Communication_340', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102891' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:363' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2514', 'source': 'Event_Communication_341', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bf70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102892' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:364' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2519', 'source': 'Event_Communication_343', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc87f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102893' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:365' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2524', 'source': 'Event_Communication_345', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e335e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102894' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:366' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2530', 'source': 'Event_Communication_347', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102895' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:367' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2535', 'source': 'Event_Communication_349', 'type': 'received', 'target': 'Davis'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102896' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:368' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2539', 'source': 'Event_Communication_350', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5aca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102897' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:369' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2543', 'source': 'Event_Communication_351', 'type': 'received', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b712e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102898' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:370' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2548', 'source': 'Event_Communication_353', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1e80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102899' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:371' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2553', 'source': 'Event_Communication_354', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102900' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:372' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2556', 'source': 'Event_Communication_355', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102901' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:373' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2558', 'source': 'Event_Communication_356', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102902' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:374' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2563', 'source': 'Event_Communication_357', 'type': 'received', 'target': 'Miranda_Jordan'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df76d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102903' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:375' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2569', 'source': 'Event_Communication_359', 'type': 'received', 'target': 'Clepper_Jensen'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102904' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:376' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2573', 'source': 'Event_Communication_360', 'type': 'received', 'target': 'Miranda_Jordan'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102905' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:377' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2575', 'source': 'Event_Communication_361', 'type': 'received', 'target': 'Clepper_Jensen'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e7c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102906' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:378' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2576', 'source': 'Event_Communication_362', 'type': 'received', 'target': 'Miranda_Jordan'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102907' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:379' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2581', 'source': 'Event_Communication_365', 'type': 'received', 'target': 'Boss'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102908' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:380' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2589', 'source': 'Event_Communication_366', 'type': 'received', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102909' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:381' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2594', 'source': 'Event_Communication_367', 'type': 'received', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcfcd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102910' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:382' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2596', 'source': 'Event_Communication_368', 'type': 'received', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0b50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102911' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:383' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2599', 'source': 'Event_Communication_369', 'type': 'received', 'target': 'The_Intern'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48a90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102912' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:384' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2277' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2604', 'source': 'Event_Communication_370', 'type': 'received', 'target': 'Kelly'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x103476310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102913' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:385' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2610', 'source': 'Event_Communication_371', 'type': 'received', 'target': 'The_Intern'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e339d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102914' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:386' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2615', 'source': 'Event_Communication_372', 'type': 'received', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3afa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102915' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:387' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2620', 'source': 'Event_Communication_373', 'type': 'received', 'target': 'Boss'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102916' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:388' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2624', 'source': 'Event_Communication_375', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x103476310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102917' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:389' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2626', 'source': 'Event_Communication_376', 'type': 'received', 'target': 'Clepper_Jensen'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034710a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102918' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:390' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2628', 'source': 'Event_Communication_377', 'type': 'received', 'target': 'Miranda_Jordan'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102919' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:391' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2631', 'source': 'Event_Communication_378', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102920' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:392' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2281' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2635', 'source': 'Event_Communication_380', 'type': 'received', 'target': 'Samantha_Blake'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102921' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:393' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2640', 'source': 'Event_Communication_381', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7bb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102922' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:394' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2645', 'source': 'Event_Communication_382', 'type': 'received', 'target': 'Boss'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a550>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102923' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:395' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2650', 'source': 'Event_Communication_384', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102924' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:396' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2655', 'source': 'Event_Communication_386', 'type': 'received', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bcd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102925' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:397' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2660', 'source': 'Event_Communication_387', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102926' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:398' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2298' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2664', 'source': 'Event_Communication_388', 'type': 'received', 'target': 'Sailor_Shifts_Team'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc57c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102927' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:399' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2667', 'source': 'Event_Communication_389', 'type': 'received', 'target': 'Boss'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102928' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:400' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2670', 'source': 'Event_Communication_390', 'type': 'received', 'target': 'Serenity'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc53a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102929' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:401' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2674', 'source': 'Event_Communication_392', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3ab80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102930' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:402' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2679', 'source': 'Event_Communication_394', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102931' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:403' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2684', 'source': 'Event_Communication_396', 'type': 'received', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102932' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:404' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2690', 'source': 'Event_Communication_399', 'type': 'received', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce92b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102933' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:405' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2697', 'source': 'Event_Communication_401', 'type': 'received', 'target': 'Davis'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e489d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102934' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:406' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2704', 'source': 'Event_Communication_403', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de77f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102935' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:407' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2709', 'source': 'Event_Communication_405', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcfe20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102936' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:408' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2712', 'source': 'Event_Communication_406', 'type': 'received', 'target': 'Serenity'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de75b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102937' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:409' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2716', 'source': 'Event_Communication_408', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102938' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:410' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2719', 'source': 'Event_Communication_409', 'type': 'received', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102939' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:411' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2722', 'source': 'Event_Communication_411', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f3d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102940' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:412' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2727', 'source': 'Event_Communication_413', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce92b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102941' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:413' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2732', 'source': 'Event_Communication_415', 'type': 'received', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b5b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102942' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:414' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2737', 'source': 'Event_Communication_417', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fc40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102943' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:415' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2315' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2740', 'source': 'Event_Communication_419', 'type': 'received', 'target': 'City_Officials'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bfd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102944' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:416' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2745', 'source': 'Event_Communication_420', 'type': 'received', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102945' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:417' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2750', 'source': 'Event_Communication_421', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08040>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102946' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:418' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2756', 'source': 'Event_Communication_423', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce92b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102947' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:419' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2762', 'source': 'Event_Communication_425', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e335e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102948' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:420' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2767', 'source': 'Event_Communication_426', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102949' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:421' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2773', 'source': 'Event_Communication_428', 'type': 'received', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102950' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:422' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2780', 'source': 'Event_Communication_431', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102951' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:423' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2787', 'source': 'Event_Communication_433', 'type': 'received', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c8e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102952' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:424' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2792', 'source': 'Event_Communication_435', 'type': 'received', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102953' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:425' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2794', 'source': 'Event_Communication_436', 'type': 'received', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102954' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:426' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2797', 'source': 'Event_Communication_437', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9d90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102955' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:427' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2800', 'source': 'Event_Communication_438', 'type': 'received', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33d90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102956' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:428' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2803', 'source': 'Event_Communication_439', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102957' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:429' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2276' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2807', 'source': 'Event_Communication_441', 'type': 'received', 'target': 'Sam'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7be0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102958' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:430' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2809', 'source': 'Event_Communication_442', 'type': 'received', 'target': 'The_Lookout'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102959' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:431' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2276' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2811', 'source': 'Event_Communication_443', 'type': 'received', 'target': 'Sam'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5ae80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102960' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:432' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2817', 'source': 'Event_Communication_446', 'type': 'received', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102961' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:433' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2825', 'source': 'Event_Communication_449', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a7c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102962' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:434' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2832', 'source': 'Event_Communication_451', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102963' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:435' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2838', 'source': 'Event_Communication_453', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102964' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:436' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2279' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2844', 'source': 'Event_Communication_456', 'type': 'received', 'target': 'Elise'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102965' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:437' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2852', 'source': 'Event_Communication_458', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102966' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:438' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2857', 'source': 'Event_Communication_460', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd80a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102967' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:439' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2279' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2861', 'source': 'Event_Communication_462', 'type': 'received', 'target': 'Elise'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102968' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:440' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2866', 'source': 'Event_Communication_464', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102969' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:441' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2872', 'source': 'Event_Communication_467', 'type': 'received', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e0d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102970' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:442' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2877', 'source': 'Event_Communication_468', 'type': 'received', 'target': 'Miranda_Jordan'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33a90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102971' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:443' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2879', 'source': 'Event_Communication_469', 'type': 'received', 'target': 'Clepper_Jensen'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e650d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102972' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:444' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2881', 'source': 'Event_Communication_470', 'type': 'received', 'target': 'Miranda_Jordan'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102973' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:445' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2885', 'source': 'Event_Communication_473', 'type': 'received', 'target': 'Clepper_Jensen'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53df0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102974' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:446' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2888', 'source': 'Event_Communication_474', 'type': 'received', 'target': 'Miranda_Jordan'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102975' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:447' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2889', 'source': 'Event_Communication_475', 'type': 'received', 'target': 'Clepper_Jensen'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102976' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:448' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2891', 'source': 'Event_Communication_476', 'type': 'received', 'target': 'Miranda_Jordan'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034710d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102977' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:449' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2896', 'source': 'Event_Communication_478', 'type': 'received', 'target': 'Clepper_Jensen'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1ccd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102978' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:450' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2901', 'source': 'Event_Communication_479', 'type': 'received', 'target': 'Miranda_Jordan'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e533a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102979' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:451' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2906', 'source': 'Event_Communication_482', 'type': 'received', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102980' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:452' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2914', 'source': 'Event_Communication_485', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33c10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102981' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:453' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2920', 'source': 'Event_Communication_487', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102982' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:454' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2923', 'source': 'Event_Communication_489', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8c10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102983' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:455' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2926', 'source': 'Event_Communication_491', 'type': 'received', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102984' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:456' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2931', 'source': 'Event_Communication_493', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102985' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:457' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2937', 'source': 'Event_Communication_496', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102986' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:458' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2943', 'source': 'Event_Communication_499', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e652e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102987' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:459' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2948', 'source': 'Event_Communication_501', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7e80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102988' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:460' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2950', 'source': 'Event_Communication_502', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102989' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:461' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2953', 'source': 'Event_Communication_504', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53d90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102990' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:462' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2958', 'source': 'Event_Communication_506', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102991' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:463' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2963', 'source': 'Event_Communication_508', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102992' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:464' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2298' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2970', 'source': 'Event_Communication_511', 'type': 'received', 'target': 'Sailor_Shifts_Team'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcfcd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102993' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:465' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2978', 'source': 'Event_Communication_513', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102994' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:466' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2985', 'source': 'Event_Communication_515', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102995' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:467' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2279' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2993', 'source': 'Event_Communication_518', 'type': 'received', 'target': 'Elise'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102996' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:468' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2997', 'source': 'Event_Communication_519', 'type': 'received', 'target': 'Liam_Thorne'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102997' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:469' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2998', 'source': 'Event_Communication_520', 'type': 'received', 'target': 'Nadia_Conti'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a9a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102998' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:470' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '2999', 'source': 'Event_Communication_521', 'type': 'received', 'target': 'Nadia_Conti'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630102999' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:471' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3001', 'source': 'Event_Communication_523', 'type': 'received', 'target': 'The_Intern'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9040>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103000' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:472' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3006', 'source': 'Event_Communication_525', 'type': 'received', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103001' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:473' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3015', 'source': 'Event_Communication_528', 'type': 'received', 'target': 'Nadia_Conti'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103002' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:474' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3022', 'source': 'Event_Communication_529', 'type': 'received', 'target': 'Liam_Thorne'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103003' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:475' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3026', 'source': 'Event_Communication_531', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e484f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103004' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:476' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3032', 'source': 'Event_Communication_533', 'type': 'received', 'target': 'Liam_Thorne'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103005' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:477' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3039', 'source': 'Event_Communication_535', 'type': 'received', 'target': 'Nadia_Conti'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103006' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:478' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3043', 'source': 'Event_Communication_536', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a040>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103007' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:479' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3047', 'source': 'Event_Communication_537', 'type': 'received', 'target': 'Nadia_Conti'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103008' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:480' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3052', 'source': 'Event_Communication_538', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddfbe0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103009' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:481' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2279' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3054', 'source': 'Event_Communication_539', 'type': 'received', 'target': 'Elise'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x103476310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103010' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:482' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3057', 'source': 'Event_Communication_541', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b280>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103011' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:483' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2281' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3062', 'source': 'Event_Communication_543', 'type': 'received', 'target': 'Samantha_Blake'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7e80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103012' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:484' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3066', 'source': 'Event_Communication_544', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103013' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:485' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3069', 'source': 'Event_Communication_545', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103014' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:486' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3073', 'source': 'Event_Communication_546', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b280>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103015' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:487' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3079', 'source': 'Event_Communication_548', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a3a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103016' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:488' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3086', 'source': 'Event_Communication_551', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddfc40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103017' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:489' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3093', 'source': 'Event_Communication_553', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103018' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:490' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3099', 'source': 'Event_Communication_555', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103019' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:491' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3103', 'source': 'Event_Communication_556', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103020' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:492' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3107', 'source': 'Event_Communication_558', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103021' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:493' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3111', 'source': 'Event_Communication_559', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e488b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103022' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:494' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3114', 'source': 'Event_Communication_560', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de79d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103023' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:495' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3117', 'source': 'Event_Communication_562', 'type': 'received', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103024' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:496' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3122', 'source': 'Event_Communication_565', 'type': 'received', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7a90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103025' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:497' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3126', 'source': 'Event_Communication_566', 'type': 'received', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103026' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:498' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3129', 'source': 'Event_Communication_568', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e5b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103027' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:499' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3138', 'source': 'Event_Communication_571', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de83a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103028' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:500' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3145', 'source': 'Event_Communication_572', 'type': 'received', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103029' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:501' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3151', 'source': 'Event_Communication_574', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103030' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:502' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3155', 'source': 'Event_Communication_575', 'type': 'received', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de79d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103031' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:503' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3157', 'source': 'Event_Communication_576', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc88e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103032' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:504' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3160', 'source': 'Event_Communication_578', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103033' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:505' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2300' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3162', 'source': 'Event_Communication_579', 'type': 'received', 'target': 'Marlin'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103034' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:506' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3165', 'source': 'Event_Communication_581', 'type': 'received', 'target': 'Davis'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103035' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:507' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3169', 'source': 'Event_Communication_582', 'type': 'received', 'target': 'Nadia_Conti'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b280>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103036' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:508' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2300' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3172', 'source': 'Event_Communication_584', 'type': 'received', 'target': 'Marlin'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103037' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:509' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3175', 'source': 'Event_Communication_585', 'type': 'received', 'target': 'Nadia_Conti'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e482e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103038' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:510' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3181', 'source': 'Event_Communication_588', 'type': 'received', 'target': 'Rodriguez'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc83d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103039' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:511' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3188', 'source': 'Event_Communication_590', 'type': 'received', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103040' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:512' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3190', 'source': 'Event_Communication_591', 'type': 'received', 'target': 'Seawatch'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103041' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:513' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3193', 'source': 'Event_Communication_593', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103042' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:514' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3197', 'source': 'Event_Communication_594', 'type': 'received', 'target': 'The_Intern'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b5e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103043' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:515' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3201', 'source': 'Event_Communication_596', 'type': 'received', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103044' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:516' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3204', 'source': 'Event_Communication_597', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fdf0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103045' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:517' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3206', 'source': 'Event_Communication_598', 'type': 'received', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103046' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:518' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3209', 'source': 'Event_Communication_599', 'type': 'received', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034fffa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103047' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:519' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3213', 'source': 'Event_Communication_601', 'type': 'received', 'target': 'Nadia_Conti'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103048' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:520' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3217', 'source': 'Event_Communication_603', 'type': 'received', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd15b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103049' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:521' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3221', 'source': 'Event_Communication_604', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103050' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:522' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3225', 'source': 'Event_Communication_605', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103051' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:523' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3228', 'source': 'Event_Communication_606', 'type': 'received', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5ad00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103052' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:524' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3231', 'source': 'Event_Communication_607', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bcd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103053' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:525' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3235', 'source': 'Event_Communication_610', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b4c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103054' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:526' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3242', 'source': 'Event_Communication_612', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ffa60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103055' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:527' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3247', 'source': 'Event_Communication_613', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e656a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103056' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:528' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3252', 'source': 'Event_Communication_614', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5aa00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103057' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:529' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3257', 'source': 'Event_Communication_616', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e486a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103058' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:530' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3260', 'source': 'Event_Communication_617', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e339a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103059' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:531' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3263', 'source': 'Event_Communication_619', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a550>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103060' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:532' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3270', 'source': 'Event_Communication_621', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103061' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:533' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3277', 'source': 'Event_Communication_623', 'type': 'received', 'target': 'EcoVigil'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103062' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:534' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3281', 'source': 'Event_Communication_627', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fc10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103063' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:535' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2300' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3289', 'source': 'Event_Communication_630', 'type': 'received', 'target': 'Marlin'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103064' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:536' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3294', 'source': 'Event_Communication_632', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103065' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:537' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3297', 'source': 'Event_Communication_633', 'type': 'received', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce92b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103066' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:538' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3300', 'source': 'Event_Communication_635', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5aa00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103067' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:539' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3303', 'source': 'Event_Communication_636', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103068' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:540' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3306', 'source': 'Event_Communication_637', 'type': 'received', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103069' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:541' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3309', 'source': 'Event_Communication_638', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103070' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:542' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3315', 'source': 'Event_Communication_639', 'type': 'received', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a1c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103071' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:543' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3321', 'source': 'Event_Communication_640', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103072' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:544' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3324', 'source': 'Event_Communication_641', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103073' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:545' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3326', 'source': 'Event_Communication_642', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c8b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103074' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:546' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3328', 'source': 'Event_Communication_644', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e536a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103075' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:547' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2310' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3332', 'source': 'Event_Communication_645', 'type': 'received', 'target': 'Northern_Light'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103076' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:548' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3336', 'source': 'Event_Communication_647', 'type': 'received', 'target': 'Liam_Thorne'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103077' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:549' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3340', 'source': 'Event_Communication_649', 'type': 'received', 'target': 'The_Intern'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c550>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103078' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:550' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3345', 'source': 'Event_Communication_651', 'type': 'received', 'target': 'The_Lookout'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5aeb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103079' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:551' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2276' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3348', 'source': 'Event_Communication_652', 'type': 'received', 'target': 'Sam'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103080' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:552' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3351', 'source': 'Event_Communication_654', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103081' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:553' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3354', 'source': 'Event_Communication_655', 'type': 'received', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e657f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103082' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:554' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3356', 'source': 'Event_Communication_656', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103083' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:555' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2281' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3359', 'source': 'Event_Communication_657', 'type': 'received', 'target': 'Samantha_Blake'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103084' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:556' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2300' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3364', 'source': 'Event_Communication_660', 'type': 'received', 'target': 'Marlin'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103085' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:557' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3370', 'source': 'Event_Communication_662', 'type': 'received', 'target': 'EcoVigil'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65280>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103086' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:558' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3374', 'source': 'Event_Communication_663', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b4c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103087' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:559' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3377', 'source': 'Event_Communication_664', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034710d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103088' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:560' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3381', 'source': 'Event_Communication_665', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103089' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:561' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3387', 'source': 'Event_Communication_668', 'type': 'received', 'target': 'EcoVigil'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103090' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:562' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3395', 'source': 'Event_Communication_672', 'type': 'received', 'target': 'EcoVigil'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53f40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103091' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:563' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3401', 'source': 'Event_Communication_674', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103092' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:564' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3404', 'source': 'Event_Communication_675', 'type': 'received', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103093' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:565' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3409', 'source': 'Event_Communication_677', 'type': 'received', 'target': 'Nadia_Conti'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c8e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103094' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:566' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3414', 'source': 'Event_Communication_679', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6dc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103095' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:567' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3419', 'source': 'Event_Communication_681', 'type': 'received', 'target': 'Seawatch'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103096' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:568' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3423', 'source': 'Event_Communication_683', 'type': 'received', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73bb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103097' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:569' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2281' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3426', 'source': 'Event_Communication_684', 'type': 'received', 'target': 'Samantha_Blake'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103098' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:570' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3428', 'source': 'Event_Communication_685', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf2e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103099' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:571' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2281' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3431', 'source': 'Event_Communication_686', 'type': 'received', 'target': 'Samantha_Blake'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103100' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:572' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3435', 'source': 'Event_Communication_687', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6dc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103101' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:573' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3439', 'source': 'Event_Communication_689', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103102' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:574' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3444', 'source': 'Event_Communication_692', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103103' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:575' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3451', 'source': 'Event_Communication_694', 'type': 'received', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103104' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:576' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3456', 'source': 'Event_Communication_696', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de83a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103105' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:577' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3464', 'source': 'Event_Communication_700', 'type': 'received', 'target': 'Liam_Thorne'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1cf70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103106' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:578' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3471', 'source': 'Event_Communication_702', 'type': 'received', 'target': 'The_Intern'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103107' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:579' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3478', 'source': 'Event_Communication_705', 'type': 'received', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e4c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103108' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:580' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3488', 'source': 'Event_Communication_708', 'type': 'received', 'target': 'Nadia_Conti'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de76a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103109' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:581' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3497', 'source': 'Event_Communication_710', 'type': 'received', 'target': 'Seawatch'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1ce20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103110' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:582' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3501', 'source': 'Event_Communication_712', 'type': 'received', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73cd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103111' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:583' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3504', 'source': 'Event_Communication_714', 'type': 'received', 'target': 'The_Intern'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3aa90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103112' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:584' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3507', 'source': 'Event_Communication_715', 'type': 'received', 'target': 'The_Lookout'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103113' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:585' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3509', 'source': 'Event_Communication_717', 'type': 'received', 'target': 'The_Intern'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103114' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:586' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3515', 'source': 'Event_Communication_720', 'type': 'received', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103115' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:587' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3520', 'source': 'Event_Communication_721', 'type': 'received', 'target': 'Liam_Thorne'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6ff40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103116' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:588' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2279' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3524', 'source': 'Event_Communication_724', 'type': 'received', 'target': 'Elise'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e3a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103117' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:589' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3531', 'source': 'Event_Communication_726', 'type': 'received', 'target': 'Boss'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a3a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103118' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:590' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3535', 'source': 'Event_Communication_727', 'type': 'received', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a1c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103119' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:591' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2279' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3536', 'source': 'Event_Communication_728', 'type': 'received', 'target': 'Elise'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103120' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:592' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3537', 'source': 'Event_Communication_730', 'type': 'received', 'target': 'The_Intern'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf4f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103121' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:593' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3542', 'source': 'Event_Communication_731', 'type': 'received', 'target': 'EcoVigil'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103122' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:594' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3548', 'source': 'Event_Communication_733', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103123' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:595' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3556', 'source': 'Event_Communication_735', 'type': 'received', 'target': 'EcoVigil'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de84f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103124' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:596' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3563', 'source': 'Event_Communication_737', 'type': 'received', 'target': 'Liam_Thorne'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5970>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103125' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:597' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3568', 'source': 'Event_Communication_739', 'type': 'received', 'target': 'Boss'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103126' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:598' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3574', 'source': 'Event_Communication_741', 'type': 'received', 'target': 'EcoVigil'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9b80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103127' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:599' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3579', 'source': 'Event_Communication_742', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6f700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103128' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:600' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3582', 'source': 'Event_Communication_744', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103129' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:601' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3586', 'source': 'Event_Communication_746', 'type': 'received', 'target': 'Liam_Thorne'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103130' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:602' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3593', 'source': 'Event_Communication_749', 'type': 'received', 'target': 'EcoVigil'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103131' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:603' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3600', 'source': 'Event_Communication_751', 'type': 'received', 'target': 'Liam_Thorne'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103132' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:604' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3606', 'source': 'Event_Communication_753', 'type': 'received', 'target': 'Nadia_Conti'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103133' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:605' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3611', 'source': 'Event_Communication_754', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4edc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103134' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:606' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3615', 'source': 'Event_Communication_755', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf0a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103135' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:607' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3621', 'source': 'Event_Communication_756', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8df0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103136' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:608' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3625', 'source': 'Event_Communication_757', 'type': 'received', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10347c3a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103137' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:609' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3629', 'source': 'Event_Communication_758', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103138' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:610' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3635', 'source': 'Event_Communication_759', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103139' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:611' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3642', 'source': 'Event_Communication_761', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd65b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103140' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:612' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3649', 'source': 'Event_Communication_762', 'type': 'received', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103141' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:613' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3655', 'source': 'Event_Communication_763', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103142' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:614' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3659', 'source': 'Event_Communication_764', 'type': 'received', 'target': 'Boss'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b5b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103143' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:615' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3664', 'source': 'Event_Communication_767', 'type': 'received', 'target': 'Clepper_Jensen'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103144' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:616' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3669', 'source': 'Event_Communication_768', 'type': 'received', 'target': 'Miranda_Jordan'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103145' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:617' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3673', 'source': 'Event_Communication_770', 'type': 'received', 'target': 'Clepper_Jensen'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5ad00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103146' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:618' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3677', 'source': 'Event_Communication_771', 'type': 'received', 'target': 'Miranda_Jordan'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0ef10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103147' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:619' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3679', 'source': 'Event_Communication_772', 'type': 'received', 'target': 'Clepper_Jensen'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e657c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103148' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:620' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3681', 'source': 'Event_Communication_773', 'type': 'received', 'target': 'Miranda_Jordan'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1beb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103149' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:621' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3685', 'source': 'Event_Communication_774', 'type': 'received', 'target': 'Clepper_Jensen'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65b50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103150' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:622' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2286' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3689', 'source': 'Event_Communication_775', 'type': 'received', 'target': 'Miranda_Jordan'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103151' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:623' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3692', 'source': 'Event_Communication_776', 'type': 'received', 'target': 'Clepper_Jensen'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103152' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:624' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3694', 'source': 'Event_Communication_778', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd85e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103153' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:625' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3700', 'source': 'Event_Communication_781', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a1f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103154' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:626' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3706', 'source': 'Event_Communication_783', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff6d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103155' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:627' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3711', 'source': 'Event_Communication_785', 'type': 'received', 'target': 'Seawatch'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103156' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:628' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3715', 'source': 'Event_Communication_787', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff9d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103157' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:629' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3718', 'source': 'Event_Communication_789', 'type': 'received', 'target': 'Seawatch'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103158' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:630' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3724', 'source': 'Event_Communication_792', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103159' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:631' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3730', 'source': 'Event_Communication_793', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103160' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:632' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2276' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3732', 'source': 'Event_Communication_794', 'type': 'received', 'target': 'Sam'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103161' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:633' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3735', 'source': 'Event_Communication_795', 'type': 'received', 'target': 'Liam_Thorne'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103162' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:634' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2289' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3740', 'source': 'Event_Communication_796', 'type': 'received', 'target': 'The_Accountant'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103163' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:635' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3745', 'source': 'Event_Communication_799', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103164' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:636' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2309' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3750', 'source': 'Event_Communication_801', 'type': 'received', 'target': 'Defender'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103165' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:637' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3755', 'source': 'Event_Communication_802', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103166' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:638' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3761', 'source': 'Event_Communication_804', 'type': 'received', 'target': 'Davis'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1cd60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103167' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:639' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3765', 'source': 'Event_Communication_805', 'type': 'received', 'target': 'Nadia_Conti'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103168' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:640' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3772', 'source': 'Event_Communication_808', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8c10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103169' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:641' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3778', 'source': 'Event_Communication_809', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103170' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:642' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3782', 'source': 'Event_Communication_810', 'type': 'received', 'target': 'Rodriguez'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73e20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103171' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:643' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3786', 'source': 'Event_Communication_811', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103172' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:644' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3790', 'source': 'Event_Communication_812', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103173' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:645' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2308' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3795', 'source': 'Event_Communication_815', 'type': 'received', 'target': 'Osprey'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1cd90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103174' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:646' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3800', 'source': 'Event_Communication_817', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103175' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:647' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3807', 'source': 'Event_Communication_819', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd83a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103176' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:648' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3813', 'source': 'Event_Communication_820', 'type': 'received', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8cd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103177' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:649' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3816', 'source': 'Event_Communication_821', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103178' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:650' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3819', 'source': 'Event_Communication_822', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103179' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:651' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3823', 'source': 'Event_Communication_823', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de72e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103180' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:652' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3827', 'source': 'Event_Communication_824', 'type': 'received', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e538b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103181' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:653' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3831', 'source': 'Event_Communication_825', 'type': 'received', 'target': 'Davis'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a7c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103182' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:654' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3833', 'source': 'Event_Communication_826', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103183' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:655' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3837', 'source': 'Event_Communication_828', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc56d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103184' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:656' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3843', 'source': 'Event_Communication_831', 'type': 'received', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103185' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:657' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3849', 'source': 'Event_Communication_833', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103186' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:658' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3856', 'source': 'Event_Communication_834', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351be20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103187' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:659' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3864', 'source': 'Event_Communication_836', 'type': 'received', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103188' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:660' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3870', 'source': 'Event_Communication_838', 'type': 'received', 'target': 'EcoVigil'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fc70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103189' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:661' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3875', 'source': 'Event_Communication_840', 'type': 'received', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48be0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103190' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:662' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3880', 'source': 'Event_Communication_841', 'type': 'received', 'target': 'Rodriguez'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351be20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103191' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:663' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3887', 'source': 'Event_Communication_842', 'type': 'received', 'target': 'Davis'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf9d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103192' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:664' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3896', 'source': 'Event_Communication_844', 'type': 'received', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8d90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103193' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:665' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3900', 'source': 'Event_Communication_845', 'type': 'received', 'target': 'Nadia_Conti'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103194' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:666' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3906', 'source': 'Event_Communication_846', 'type': 'received', 'target': 'Nadia_Conti'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351be20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103195' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:667' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3909', 'source': 'Event_Communication_847', 'type': 'received', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf9d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103196' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:668' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3911', 'source': 'Event_Communication_849', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103197' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:669' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3914', 'source': 'Event_Communication_850', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4ee20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103198' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:670' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3918', 'source': 'Event_Communication_851', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351be20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103199' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:671' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3922', 'source': 'Event_Communication_852', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103200' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:672' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3925', 'source': 'Event_Communication_853', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103201' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:673' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3930', 'source': 'Event_Communication_855', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103202' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:674' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3935', 'source': 'Event_Communication_857', 'type': 'received', 'target': 'Seawatch'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351be20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103203' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:675' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2276' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3939', 'source': 'Event_Communication_859', 'type': 'received', 'target': 'Sam'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4ebe0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103204' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:676' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3941', 'source': 'Event_Communication_860', 'type': 'received', 'target': 'The_Lookout'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103205' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:677' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2276' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3943', 'source': 'Event_Communication_862', 'type': 'received', 'target': 'Sam'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103206' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:678' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3947', 'source': 'Event_Communication_864', 'type': 'received', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103207' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:679' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3952', 'source': 'Event_Communication_866', 'type': 'received', 'target': 'Boss'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3af70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103208' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:680' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2289' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3955', 'source': 'Event_Communication_867', 'type': 'received', 'target': 'The_Accountant'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103209' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:681' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3959', 'source': 'Event_Communication_869', 'type': 'received', 'target': 'Nadia_Conti'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103210' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:682' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3964', 'source': 'Event_Communication_871', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26e80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103211' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:683' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3969', 'source': 'Event_Communication_873', 'type': 'received', 'target': 'Davis'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6f6a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103212' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:684' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3973', 'source': 'Event_Communication_875', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103213' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:685' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3977', 'source': 'Event_Communication_877', 'type': 'received', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103214' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:686' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3982', 'source': 'Event_Communication_879', 'type': 'received', 'target': 'Seawatch'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4eb80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103215' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:687' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3988', 'source': 'Event_Communication_881', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103216' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:688' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3993', 'source': 'Event_Communication_882', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e489d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103217' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:689' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2312' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '3997', 'source': 'Event_Communication_884', 'type': 'received', 'target': 'Knowles'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6f880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103218' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:690' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2320' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4002', 'source': 'Event_Communication_886', 'type': 'received', 'target': 'Haacklee_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103219' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:691' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4007', 'source': 'Event_Communication_888', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103220' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:692' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4012', 'source': 'Event_Communication_890', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5bb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103221' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:693' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4016', 'source': 'Event_Communication_891', 'type': 'received', 'target': 'Davis'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103222' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:694' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4019', 'source': 'Event_Communication_893', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103223' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:695' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4022', 'source': 'Event_Communication_895', 'type': 'received', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7a90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103224' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:696' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4024', 'source': 'Event_Communication_897', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddfbe0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103225' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:697' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4027', 'source': 'Event_Communication_898', 'type': 'received', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fc40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103226' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:698' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4029', 'source': 'Event_Communication_899', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df75e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103227' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:699' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4031', 'source': 'Event_Communication_901', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb00d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103228' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:700' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4035', 'source': 'Event_Communication_902', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103229' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:701' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4038', 'source': 'Event_Communication_903', 'type': 'received', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6feb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103230' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:702' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4043', 'source': 'Event_Communication_905', 'type': 'received', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df75e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103231' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:703' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4051', 'source': 'Event_Communication_908', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103232' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:704' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4058', 'source': 'Event_Communication_910', 'type': 'received', 'target': 'Seawatch'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103233' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:705' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4062', 'source': 'Event_Communication_912', 'type': 'received', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e7c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103234' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:706' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4067', 'source': 'Event_Communication_914', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103235' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:707' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4074', 'source': 'Event_Communication_916', 'type': 'received', 'target': 'Davis'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b8e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103236' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:708' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4081', 'source': 'Event_Communication_919', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fb80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103237' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:709' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4085', 'source': 'Event_Communication_920', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103238' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:710' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4087', 'source': 'Event_Communication_921', 'type': 'received', 'target': 'The_Lookout'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103239' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:711' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4090', 'source': 'Event_Communication_923', 'type': 'received', 'target': 'The_Intern'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103240' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:712' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4096', 'source': 'Event_Communication_925', 'type': 'received', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103241' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:713' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4100', 'source': 'Event_Communication_926', 'type': 'received', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7fb20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103243' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:715' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4103', 'source': 'Event_Communication_928', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103245' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:717' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4110', 'source': 'Event_Communication_930', 'type': 'received', 'target': 'Liam_Thorne'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103246' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:718' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4119', 'source': 'Event_Communication_933', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103247' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:719' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4124', 'source': 'Event_Communication_935', 'type': 'received', 'target': 'The_Intern'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10347cdc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103248' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:720' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4127', 'source': 'Event_Communication_936', 'type': 'received', 'target': 'The_Lookout'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103249' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:721' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2287' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4129', 'source': 'Event_Communication_937', 'type': 'received', 'target': 'The_Intern'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103250' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:722' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2298' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4132', 'source': 'Event_Communication_939', 'type': 'received', 'target': 'Sailor_Shifts_Team'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103251' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:723' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4137', 'source': 'Event_Communication_940', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103252' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:724' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4144', 'source': 'Event_Communication_943', 'type': 'received', 'target': 'Nadia_Conti'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103253' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:725' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4150', 'source': 'Event_Communication_945', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65df0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103254' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:726' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4157', 'source': 'Event_Communication_949', 'type': 'received', 'target': 'EcoVigil'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5afd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103255' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:727' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2289' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4166', 'source': 'Event_Communication_950', 'type': 'received', 'target': 'The_Accountant'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fc40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103256' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:728' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2291' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4172', 'source': 'Event_Communication_951', 'type': 'received', 'target': 'The_Middleman'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103257' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:729' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4176', 'source': 'Event_Communication_953', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e2e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103258' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:730' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4179', 'source': 'Event_Communication_955', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b5b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103259' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:731' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4185', 'source': 'Event_Communication_958', 'type': 'received', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc57c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103260' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:732' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4192', 'source': 'Event_Communication_960', 'type': 'received', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103261' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:733' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4196', 'source': 'Event_Communication_961', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e735b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103262' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:734' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4201', 'source': 'Event_Communication_963', 'type': 'received', 'target': 'Boss'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e731c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103264' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:736' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4206', 'source': 'Event_Communication_964', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103265' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:737' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4208', 'source': 'Event_Communication_965', 'type': 'received', 'target': 'Seawatch'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103266' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:738' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4213', 'source': 'Event_Communication_968', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e735b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103267' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:739' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2347' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4222', 'source': 'Event_Communication_970', 'type': 'received', 'target': 'Port_Security'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103268' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:740' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4228', 'source': 'Event_Communication_974', 'type': 'received', 'target': 'EcoVigil'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103269' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:741' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4235', 'source': 'Event_Communication_976', 'type': 'received', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103270' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:742' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4238', 'source': 'Event_Communication_977', 'type': 'received', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcfc70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103271' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:743' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4241', 'source': 'Event_Communication_979', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103272' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:744' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4244', 'source': 'Event_Communication_981', 'type': 'received', 'target': 'Davis'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26f10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103275' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:747' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4246', 'source': 'Event_Communication_982', 'type': 'received', 'target': 'Rodriguez'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b5b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103276' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:748' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4250', 'source': 'Event_Communication_984', 'type': 'received', 'target': 'Davis'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103277' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:749' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4257', 'source': 'Event_Communication_986', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b5b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103278' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:750' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4262', 'source': 'Event_Communication_987', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103279' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:751' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4266', 'source': 'Event_Communication_989', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103280' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:752' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4270', 'source': 'Event_Communication_991', 'type': 'received', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de82e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103281' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:753' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4275', 'source': 'Event_Communication_993', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103282' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:754' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4280', 'source': 'Event_Communication_994', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6dc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103283' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:755' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4285', 'source': 'Event_Communication_997', 'type': 'received', 'target': 'EcoVigil'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e339d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103284' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:756' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4291', 'source': 'Event_Communication_999', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e1c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103285' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:757' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4296', 'source': 'Event_Communication_1001', 'type': 'received', 'target': 'Davis'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103286' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:758' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2282' labels=frozenset() properties={}>) type='received' properties={'is_inferred': False, 'id': '4301', 'source': 'Event_Communication_1003', 'type': 'received', 'target': 'Davis'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4ef70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103287' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:759' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2324' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1796', 'source': 'Event_Assessment_14', 'type': 'received', 'target': 'Azure_Cove'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f4c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103288' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:760' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2330' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1701', 'source': 'Event_Assessment_18', 'type': 'received', 'target': 'Coral_Point'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155175503443788536' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:760' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2331' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1702', 'source': 'Event_Assessment_18', 'type': 'received', 'target': 'Dolphin_Bay'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de83a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103289' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:761' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2497', 'source': 'Event_Assessment_41', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bcd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103290' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:762' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2331' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1797', 'source': 'Event_Assessment_56', 'type': 'received', 'target': 'Dolphin_Bay'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103291' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:763' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2038', 'source': 'Event_Assessment_65', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103292' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:764' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2468', 'source': 'Event_Assessment_101', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103293' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:765' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2330' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1936', 'source': 'Event_Assessment_114', 'type': 'received', 'target': 'Coral_Point'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08b50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155175503443788541' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:765' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2331' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1937', 'source': 'Event_Assessment_114', 'type': 'received', 'target': 'Dolphin_Bay'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de83a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103295' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:767' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3698', 'source': 'Event_Assessment_174', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103296' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:768' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2329' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2139', 'source': 'Event_Assessment_198', 'type': 'received', 'target': 'Southern_coastline'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8eb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103297' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:769' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2221', 'source': 'Event_Assessment_223', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155175503443788545' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:769' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2329' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2222', 'source': 'Event_Assessment_223', 'type': 'received', 'target': 'Southern_coastline'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103298' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:770' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2484', 'source': 'Event_Assessment_329', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103299' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:771' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2432', 'source': 'Event_Assessment_337', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4edf0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103300' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:772' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2320' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2814', 'source': 'Event_Assessment_445', 'type': 'received', 'target': 'Haacklee_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73e80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103301' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:773' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2326' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2864', 'source': 'Event_Assessment_463', 'type': 'received', 'target': 'Eastern_reefs'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103302' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:774' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2339' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2922', 'source': 'Event_Assessment_488', 'type': 'received', 'target': 'Eastern_Boundary'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7fa30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103303' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:775' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1733', 'source': 'Event_Assessment_492', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f7f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103304' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:776' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2884', 'source': 'Event_Assessment_522', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a4f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103306' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:778' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2341' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3171', 'source': 'Event_Assessment_583', 'type': 'received', 'target': 'Eastern_Shoals'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103307' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:779' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3483', 'source': 'Event_Assessment_600', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7fa30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103310' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:782' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3266', 'source': 'Event_Assessment_628', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103311' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:783' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2323' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3343', 'source': 'Event_Assessment_650', 'type': 'received', 'target': 'Restricted_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc53a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103313' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:785' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3470', 'source': 'Event_Assessment_701', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103314' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:786' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3475', 'source': 'Event_Assessment_703', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103316' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:788' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2323' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3661', 'source': 'Event_Assessment_765', 'type': 'received', 'target': 'Restricted_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a7f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103317' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:789' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3714', 'source': 'Event_Assessment_786', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e485b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103318' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:790' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3721', 'source': 'Event_Assessment_791', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103319' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:791' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3868', 'source': 'Event_Assessment_837', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8d90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103320' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:792' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2325' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4209', 'source': 'Event_Assessment_966', 'type': 'received', 'target': 'Protected_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103321' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:793' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4064', 'source': 'Event_Assessment_973', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48be0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103322' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:794' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3561', 'source': 'Event_Assessment_996', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7fa30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103323' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:795' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2715', 'source': 'Event_VesselMovement_25', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e0d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103324' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:796' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4264', 'source': 'Event_VesselMovement_122', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a7f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103325' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:797' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2037', 'source': 'Event_VesselMovement_154', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103326' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:798' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2046', 'source': 'Event_VesselMovement_157', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de87f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6919783026478025000' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:798' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2344' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2047', 'source': 'Event_VesselMovement_157', 'type': 'received', 'target': 'South_Dock'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e0d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103327' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:799' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2121', 'source': 'Event_VesselMovement_190', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103328' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:800' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2336' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2185', 'source': 'Event_VesselMovement_210', 'type': 'received', 'target': 'Western_quadrant'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48be0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103330' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:802' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2339' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2388', 'source': 'Event_VesselMovement_284', 'type': 'received', 'target': 'Eastern_Boundary'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103331' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:803' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2335' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2396', 'source': 'Event_VesselMovement_288', 'type': 'received', 'target': 'Eastern_quadrant'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103332' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:804' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2337' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2420', 'source': 'Event_VesselMovement_300', 'type': 'received', 'target': 'Eastern_Islands'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e0d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103333' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:805' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2426', 'source': 'Event_VesselMovement_303', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155175503443788581' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:805' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2337' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2427', 'source': 'Event_VesselMovement_303', 'type': 'received', 'target': 'Eastern_Islands'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b1c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103334' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:806' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2480', 'source': 'Event_VesselMovement_326', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddfa00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103336' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:808' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2577', 'source': 'Event_VesselMovement_363', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155175503443788584' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:808' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2578', 'source': 'Event_VesselMovement_363', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f7f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103337' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:809' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3327', 'source': 'Event_VesselMovement_393', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0efd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103339' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:811' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4010', 'source': 'Event_VesselMovement_402', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103341' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:813' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2340' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2910', 'source': 'Event_VesselMovement_483', 'type': 'received', 'target': 'Southern_Boundary'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8970>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103342' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:814' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2326' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2934', 'source': 'Event_VesselMovement_494', 'type': 'received', 'target': 'Eastern_reefs'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f1c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103343' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:815' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2326' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3090', 'source': 'Event_VesselMovement_495', 'type': 'received', 'target': 'Eastern_reefs'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4ee80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103344' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:816' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2326' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2841', 'source': 'Event_VesselMovement_503', 'type': 'received', 'target': 'Eastern_reefs'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103345' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:817' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3116', 'source': 'Event_VesselMovement_509', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103346' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:818' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2343' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2941', 'source': 'Event_VesselMovement_510', 'type': 'received', 'target': 'Route_C'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de76a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103349' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:821' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2273', 'source': 'Event_VesselMovement_549', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103350' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:822' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3119', 'source': 'Event_VesselMovement_563', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103351' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:823' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2097', 'source': 'Event_VesselMovement_569', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd81f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103352' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:824' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3362', 'source': 'Event_VesselMovement_577', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6f550>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103353' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:825' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2341' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3163', 'source': 'Event_VesselMovement_580', 'type': 'received', 'target': 'Eastern_Shoals'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7f40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103355' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:827' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2335' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3361', 'source': 'Event_VesselMovement_629', 'type': 'received', 'target': 'Eastern_quadrant'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a7c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103356' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:828' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3299', 'source': 'Event_VesselMovement_634', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bc10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103357' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:829' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3392', 'source': 'Event_VesselMovement_670', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6ff10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103358' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:830' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2333' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3744', 'source': 'Event_VesselMovement_798', 'type': 'received', 'target': 'Northern_quadrant'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7f40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103359' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:831' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3769', 'source': 'Event_VesselMovement_806', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddfa00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103360' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:832' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3892', 'source': 'Event_VesselMovement_843', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53df0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103361' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:833' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2320' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4000', 'source': 'Event_VesselMovement_883', 'type': 'received', 'target': 'Haacklee_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6f610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103362' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:834' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4005', 'source': 'Event_VesselMovement_887', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9eb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103363' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:835' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2344' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4178', 'source': 'Event_VesselMovement_892', 'type': 'received', 'target': 'South_Dock'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73bb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103364' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:836' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4040', 'source': 'Event_VesselMovement_904', 'type': 'received', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b5b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103365' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:837' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2333' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3985', 'source': 'Event_VesselMovement_931', 'type': 'received', 'target': 'Northern_quadrant'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103366' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:838' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2331' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4149', 'source': 'Event_VesselMovement_944', 'type': 'received', 'target': 'Dolphin_Bay'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8d30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103367' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:839' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2346' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4243', 'source': 'Event_VesselMovement_980', 'type': 'received', 'target': 'Berth_14'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33a90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103368' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:840' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2344' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1798', 'source': 'Event_VesselMovement_1000', 'type': 'received', 'target': 'South_Dock'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103369' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:841' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2344' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4299', 'source': 'Event_VesselMovement_1002', 'type': 'received', 'target': 'South_Dock'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1cd90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103370' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:842' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1728', 'source': 'Event_Enforcement_29', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de73a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103371' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:843' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2325' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1742', 'source': 'Event_Enforcement_34', 'type': 'received', 'target': 'Protected_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1beb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155175503443788619' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:843' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1743', 'source': 'Event_Enforcement_34', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de77f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103372' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:844' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1768', 'source': 'Event_Enforcement_42', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103373' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:845' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1776', 'source': 'Event_Enforcement_44', 'type': 'received', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73b80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103374' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:846' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1715', 'source': 'Event_Enforcement_177', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103376' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:848' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2313' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2127', 'source': 'Event_Enforcement_193', 'type': 'received', 'target': 'Mariner_s_Dream'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103377' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:849' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2310' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2245', 'source': 'Event_Enforcement_233', 'type': 'received', 'target': 'Northern_Light'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1cdc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103378' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:850' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2340', 'source': 'Event_Enforcement_235', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103379' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:851' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2298', 'source': 'Event_Enforcement_261', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103380' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:852' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2404', 'source': 'Event_Enforcement_292', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26e80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103381' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:853' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3384', 'source': 'Event_Enforcement_666', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103382' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:854' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3449', 'source': 'Event_Enforcement_693', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103383' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:855' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2208', 'source': 'Event_Enforcement_745', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103384' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:856' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2323' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3671', 'source': 'Event_Enforcement_769', 'type': 'received', 'target': 'Restricted_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103385' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:857' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3454', 'source': 'Event_Enforcement_784', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103387' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:859' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3873', 'source': 'Event_Enforcement_839', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103388' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:860' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3927', 'source': 'Event_Enforcement_854', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4eac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155175503443788636' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:860' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3928', 'source': 'Event_Enforcement_854', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103389' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:861' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4153', 'source': 'Event_Enforcement_947', 'type': 'received', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4ec40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103390' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:862' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2333' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4175', 'source': 'Event_Enforcement_952', 'type': 'received', 'target': 'Northern_quadrant'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103391' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:863' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4272', 'source': 'Event_Enforcement_992', 'type': 'received', 'target': 'Seawatch'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e482e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103393' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:865' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4289', 'source': 'Event_Enforcement_998', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103396' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:868' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1752', 'source': 'Event_TourActivity_46', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103397' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:869' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1807', 'source': 'Event_TourActivity_61', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155175503443788645' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:869' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2325' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1808', 'source': 'Event_TourActivity_61', 'type': 'received', 'target': 'Protected_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103398' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:870' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1832', 'source': 'Event_TourActivity_70', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155175503443788646' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:870' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2325' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1833', 'source': 'Event_TourActivity_70', 'type': 'received', 'target': 'Protected_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103399' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:871' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2320' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1888', 'source': 'Event_TourActivity_96', 'type': 'received', 'target': 'Haacklee_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc56d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103400' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:872' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2003', 'source': 'Event_TourActivity_137', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103401' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:873' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2008', 'source': 'Event_TourActivity_140', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e489d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103402' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:874' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2115', 'source': 'Event_TourActivity_188', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd67f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103404' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:876' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3349', 'source': 'Event_TourActivity_807', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103405' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:877' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2345' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3794', 'source': 'Event_TourActivity_814', 'type': 'received', 'target': 'Castaway_Cove'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f1f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103406' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:878' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2345' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3798', 'source': 'Event_TourActivity_816', 'type': 'received', 'target': 'Castaway_Cove'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4eb50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103407' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:879' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2344' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4181', 'source': 'Event_TourActivity_938', 'type': 'received', 'target': 'South_Dock'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fc10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103408' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:880' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2688', 'source': 'Event_TourActivity_962', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddfa00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103409' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:881' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1788', 'source': 'Event_Fishing_49', 'type': 'received', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a4f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103410' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:882' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1792', 'source': 'Event_Criticize_52', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103413' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:885' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2107', 'source': 'Event_Collaborate_184', 'type': 'received', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb01f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103414' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:886' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2312' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2153', 'source': 'Event_Collaborate_200', 'type': 'received', 'target': 'Knowles'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103415' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:887' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2341', 'source': 'Event_Collaborate_236', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f1f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103421' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:893' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2579', 'source': 'Event_Collaborate_364', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103426' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:898' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2315' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2893', 'source': 'Event_Collaborate_477', 'type': 'received', 'target': 'City_Officials'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103428' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:900' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2294' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2975', 'source': 'Event_Collaborate_512', 'type': 'received', 'target': 'Glitters_Team'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a5e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103429' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:901' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2989', 'source': 'Event_Collaborate_517', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155175503443788677' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:901' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2990', 'source': 'Event_Collaborate_517', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103430' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:902' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3060', 'source': 'Event_Collaborate_542', 'type': 'received', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3abb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103431' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:903' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3084', 'source': 'Event_Collaborate_550', 'type': 'received', 'target': 'Nadia_Conti'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a5e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103432' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:904' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3097', 'source': 'Event_Collaborate_554', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e86d60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103433' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:905' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3105', 'source': 'Event_Collaborate_557', 'type': 'received', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e2e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103435' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:907' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3459', 'source': 'Event_Collaborate_697', 'type': 'received', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e86a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103436' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:908' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2288' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '1667', 'source': 'Event_Collaborate_719', 'type': 'received', 'target': 'The_Lookout'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103437' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:909' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3460', 'source': 'Event_Collaborate_723', 'type': 'received', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103438' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:910' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3639', 'source': 'Event_Collaborate_760', 'type': 'received', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fb80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103439' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:911' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '3803', 'source': 'Event_Collaborate_818', 'type': 'received', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103442' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:914' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2328' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2196', 'source': 'Event_HarborReport_215', 'type': 'received', 'target': 'Southern_islands'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155175503443788690' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:914' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2325' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2197', 'source': 'Event_HarborReport_215', 'type': 'received', 'target': 'Protected_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103443' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:915' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '4101', 'source': 'Event_HarborReport_927', 'type': 'received', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103444' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:916' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2332' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2289', 'source': 'Event_TransponderPing_251', 'type': 'received', 'target': 'E7'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e867f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103445' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:917' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2325' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2333', 'source': 'Event_TransponderPing_271', 'type': 'received', 'target': 'Protected_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152923703630103446' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:918' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='received' properties={'is_inferred': True, 'id': '2869', 'source': 'Event_TransponderPing_308', 'type': 'received', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358237' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:157' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:0' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1662', 'source': 'Event_Communication_1', 'type': 'evidence_for', 'target': 'Event_Monitoring_0'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b5b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358246' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:166' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:919' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1665', 'source': 'Event_Communication_2', 'type': 'evidence_for', 'target': 'Relationship_Friends_0'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358251' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:171' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:946' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1671', 'source': 'Event_Communication_5', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_589'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4eee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043499' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:171' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:908' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1670', 'source': 'Event_Communication_5', 'type': 'evidence_for', 'target': 'Event_Collaborate_719'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358252' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:172' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:921' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1674', 'source': 'Event_Communication_6', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_2'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358253' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:173' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:932' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1680', 'source': 'Event_Communication_7', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_158'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043501' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:173' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:921' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': 'Event_Communication_7_evidence_for_Relationship_Colleagues_2', 'source': 'Event_Communication_7', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_2'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4eee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728749' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:173' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:922' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1681', 'source': 'Event_Communication_7', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_11'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8970>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358259' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:179' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:952' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1689', 'source': 'Event_Communication_13', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_7'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358260' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:180' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:759' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1692', 'source': 'Event_Communication_15', 'type': 'evidence_for', 'target': 'Event_Assessment_14'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358261' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:181' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:952' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1695', 'source': 'Event_Communication_16', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_7'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddfa00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594059' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:182' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1099' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1699', 'source': 'Event_Communication_17', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_387'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26be0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043510' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:182' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:965' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1700', 'source': 'Event_Communication_17', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_148'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358263' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:183' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:760' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1705', 'source': 'Event_Communication_20', 'type': 'evidence_for', 'target': 'Event_Assessment_18'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33d90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043511' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:183' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:796' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1706', 'source': 'Event_Communication_20', 'type': 'evidence_for', 'target': 'Event_VesselMovement_122'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358264' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:184' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:922' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1712', 'source': 'Event_Communication_21', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_11'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1ce20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043512' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:184' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:932' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': 'Event_Communication_21_evidence_for_Relationship_Colleagues_158', 'source': 'Event_Communication_21', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_158'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd83a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728760' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:184' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:921' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1711', 'source': 'Event_Communication_21', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_2'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6feb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358266' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:186' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:952' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1719', 'source': 'Event_Communication_24', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_7'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043514' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:186' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:846' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1718', 'source': 'Event_Communication_24', 'type': 'evidence_for', 'target': 'Event_Enforcement_177'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358267' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:187' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:795' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1722', 'source': 'Event_Communication_26', 'type': 'evidence_for', 'target': 'Event_VesselMovement_25'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53f10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358268' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:188' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:976' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1727', 'source': 'Event_Communication_28', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_238'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf3d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043516' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:188' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:795' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1726', 'source': 'Event_Communication_28', 'type': 'evidence_for', 'target': 'Event_VesselMovement_25'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358269' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:189' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:842' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1731', 'source': 'Event_Communication_30', 'type': 'evidence_for', 'target': 'Event_Enforcement_29'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5ab20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043517' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:189' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:989' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1732', 'source': 'Event_Communication_30', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_338'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1be80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358270' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:190' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:924' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1738', 'source': 'Event_Communication_32', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_16'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043518' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:190' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:989' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1739', 'source': 'Event_Communication_32', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_338'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5af40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728766' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:190' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:775' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1737', 'source': 'Event_Communication_32', 'type': 'evidence_for', 'target': 'Event_Assessment_492'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73cd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358271' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:191' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1748', 'source': 'Event_Communication_35', 'type': 'evidence_for', 'target': 'Event_Monitoring_33'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e338b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043519' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:191' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:843' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1749', 'source': 'Event_Communication_35', 'type': 'evidence_for', 'target': 'Event_Enforcement_34'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73f10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728767' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:191' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1020' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1750', 'source': 'Event_Communication_35', 'type': 'evidence_for', 'target': 'Relationship_Reports_18'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c550>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594005' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:191' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1045' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1751', 'source': 'Event_Communication_35', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_19'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e656a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358272' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:192' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1058' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1758', 'source': 'Event_Communication_37', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_20'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043520' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:192' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1046' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1759', 'source': 'Event_Communication_37', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_21'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73e20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728768' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:192' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1760', 'source': 'Event_Communication_37', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414016' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:192' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:868' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1757', 'source': 'Event_Communication_37', 'type': 'evidence_for', 'target': 'Event_TourActivity_46'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358273' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:193' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1764', 'source': 'Event_Communication_39', 'type': 'evidence_for', 'target': 'Event_Monitoring_38'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e538b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043521' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:193' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:932' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': 'Event_Communication_39_evidence_for_Relationship_Colleagues_158', 'source': 'Event_Communication_39', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_158'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e657f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358275' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:195' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:761' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1772', 'source': 'Event_Communication_43', 'type': 'evidence_for', 'target': 'Event_Assessment_41'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043523' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:195' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:844' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1773', 'source': 'Event_Communication_43', 'type': 'evidence_for', 'target': 'Event_Enforcement_42'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728771' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:195' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1059' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1774', 'source': 'Event_Communication_43', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_24'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bf70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594001' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:195' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1041' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1775', 'source': 'Event_Communication_43', 'type': 'evidence_for', 'target': 'Relationship_Reports_587'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358276' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:196' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:845' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1779', 'source': 'Event_Communication_45', 'type': 'evidence_for', 'target': 'Event_Enforcement_44'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043524' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:196' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1059' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1780', 'source': 'Event_Communication_45', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_24'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358277' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:197' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:868' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1785', 'source': 'Event_Communication_48', 'type': 'evidence_for', 'target': 'Event_TourActivity_46'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e538b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043525' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:197' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1060' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1787', 'source': 'Event_Communication_48', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_27'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728773' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:197' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:76' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1786', 'source': 'Event_Communication_48', 'type': 'evidence_for', 'target': 'Event_Monitoring_946'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8bb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358278' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:198' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:881' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1790', 'source': 'Event_Communication_50', 'type': 'evidence_for', 'target': 'Event_Fishing_49'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e6a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358280' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:200' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:882' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1794', 'source': 'Event_Communication_53', 'type': 'evidence_for', 'target': 'Event_Criticize_52'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd81f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358282' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:202' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:762' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1802', 'source': 'Event_Communication_59', 'type': 'evidence_for', 'target': 'Event_Assessment_56'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd64c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043530' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:202' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:759' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1801', 'source': 'Event_Communication_59', 'type': 'evidence_for', 'target': 'Event_Assessment_14'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728778' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:202' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:840' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1803', 'source': 'Event_Communication_59', 'type': 'evidence_for', 'target': 'Event_VesselMovement_1000'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4ee50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414026' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:202' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:835' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1804', 'source': 'Event_Communication_59', 'type': 'evidence_for', 'target': 'Event_VesselMovement_892'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb09d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358283' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:203' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:3' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1812', 'source': 'Event_Communication_62', 'type': 'evidence_for', 'target': 'Event_Monitoring_60'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcfcd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043531' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:203' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:869' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1813', 'source': 'Event_Communication_62', 'type': 'evidence_for', 'target': 'Event_TourActivity_61'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728779' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:203' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1047' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1815', 'source': 'Event_Communication_62', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_29'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de84f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414027' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:203' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1170' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1814', 'source': 'Event_Communication_62', 'type': 'evidence_for', 'target': 'Relationship_Operates_566'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351be20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358284' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:204' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1061' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1819', 'source': 'Event_Communication_64', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_30'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358285' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:205' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:763' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1823', 'source': 'Event_Communication_66', 'type': 'evidence_for', 'target': 'Event_Assessment_65'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043533' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:205' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:954' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1824', 'source': 'Event_Communication_66', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_81'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358286' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:206' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:997' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1827', 'source': 'Event_Communication_67', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_415'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fb50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358287' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:207' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:4' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1831', 'source': 'Event_Communication_69', 'type': 'evidence_for', 'target': 'Event_Monitoring_68'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358288' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:208' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:870' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1837', 'source': 'Event_Communication_72', 'type': 'evidence_for', 'target': 'Event_TourActivity_70'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043536' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:208' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:5' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1838', 'source': 'Event_Communication_72', 'type': 'evidence_for', 'target': 'Event_Monitoring_71'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b1c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728784' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:208' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1062' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1839', 'source': 'Event_Communication_72', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_33'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf4f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358289' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:209' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1846', 'source': 'Event_Communication_76', 'type': 'evidence_for', 'target': 'Event_Monitoring_73'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f970>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043537' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:209' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:7' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1847', 'source': 'Event_Communication_76', 'type': 'evidence_for', 'target': 'Event_Monitoring_74'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728785' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:209' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1063' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1850', 'source': 'Event_Communication_76', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_35'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6ff10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414033' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:209' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1070' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1849', 'source': 'Event_Communication_76', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_116'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4ee80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1161933101908099281' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:209' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:868' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1848', 'source': 'Event_Communication_76', 'type': 'evidence_for', 'target': 'Event_TourActivity_46'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358290' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:210' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:8' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1855', 'source': 'Event_Communication_79', 'type': 'evidence_for', 'target': 'Event_Monitoring_77'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043538' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:210' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:868' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1856', 'source': 'Event_Communication_79', 'type': 'evidence_for', 'target': 'Event_TourActivity_46'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e86850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358291' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:211' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:9' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1864', 'source': 'Event_Communication_85', 'type': 'evidence_for', 'target': 'Event_Monitoring_83'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594025' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:211' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1065' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1866', 'source': 'Event_Communication_85', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_39'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043539' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:211' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:868' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1865', 'source': 'Event_Communication_85', 'type': 'evidence_for', 'target': 'Event_TourActivity_46'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358292' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:212' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:34' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1869', 'source': 'Event_Communication_87', 'type': 'evidence_for', 'target': 'Event_Monitoring_595'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e86850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358293' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:213' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:946' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1874', 'source': 'Event_Communication_89', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_589'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043541' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:213' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:34' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1873', 'source': 'Event_Communication_89', 'type': 'evidence_for', 'target': 'Event_Monitoring_595'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1ce20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687593982' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:216' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1022' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1880', 'source': 'Event_Communication_92', 'type': 'evidence_for', 'target': 'Relationship_Reports_41'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b1c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043544' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:216' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:946' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1881', 'source': 'Event_Communication_92', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_589'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7fc70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358297' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:217' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:34' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1884', 'source': 'Event_Communication_94', 'type': 'evidence_for', 'target': 'Event_Monitoring_595'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a5b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358298' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:218' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1066' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1887', 'source': 'Event_Communication_95', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_43'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e86310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358299' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:219' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:871' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1891', 'source': 'Event_Communication_97', 'type': 'evidence_for', 'target': 'Event_TourActivity_96'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594075' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:219' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1115' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1892', 'source': 'Event_Communication_97', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_509'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e3d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358300' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:220' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:925' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1897', 'source': 'Event_Communication_99', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_45'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043548' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:220' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:796' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1896', 'source': 'Event_Communication_99', 'type': 'evidence_for', 'target': 'Event_VesselMovement_122'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e86430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687593983' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:221' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1023' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1900', 'source': 'Event_Communication_100', 'type': 'evidence_for', 'target': 'Relationship_Reports_46'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6f220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358302' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:222' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:764' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1905', 'source': 'Event_Communication_102', 'type': 'evidence_for', 'target': 'Event_Assessment_101'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043550' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:222' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:997' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1907', 'source': 'Event_Communication_102', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_415'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728798' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:222' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1906', 'source': 'Event_Communication_102', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e966a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358303' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:223' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:972' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1910', 'source': 'Event_Communication_103', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_196'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6f550>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358304' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:224' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:10' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1917', 'source': 'Event_Communication_106', 'type': 'evidence_for', 'target': 'Event_Monitoring_105'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4ee80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687593984' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:224' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1024' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1919', 'source': 'Event_Communication_106', 'type': 'evidence_for', 'target': 'Relationship_Reports_51'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043552' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:224' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:767' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1916', 'source': 'Event_Communication_106', 'type': 'evidence_for', 'target': 'Event_Assessment_174'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e869d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728800' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:224' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1080' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1918', 'source': 'Event_Communication_106', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_251'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e3d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358305' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:225' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:884' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1923', 'source': 'Event_Communication_109', 'type': 'evidence_for', 'target': 'Event_Collaborate_108'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7f40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043553' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:225' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1067' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1925', 'source': 'Event_Communication_109', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_53'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e488b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728801' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:225' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1080' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1924', 'source': 'Event_Communication_109', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_251'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3abb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594028' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:226' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1068' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1928', 'source': 'Event_Communication_110', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_54'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b4c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358307' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:227' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1080' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1931', 'source': 'Event_Communication_111', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_251'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7f40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358308' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:228' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1068' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1934', 'source': 'Event_Communication_112', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_54'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcfc70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358310' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:230' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:765' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1940', 'source': 'Event_Communication_115', 'type': 'evidence_for', 'target': 'Event_Assessment_114'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e869a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043558' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:230' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:950' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1941', 'source': 'Event_Communication_115', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_619'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b4c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594093' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:231' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1133' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1947', 'source': 'Event_Communication_117', 'type': 'evidence_for', 'target': 'Relationship_Operates_58'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96dc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043559' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:231' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1134' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1948', 'source': 'Event_Communication_117', 'type': 'evidence_for', 'target': 'Relationship_Operates_59'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e538b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728807' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:231' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:796' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1946', 'source': 'Event_Communication_117', 'type': 'evidence_for', 'target': 'Event_VesselMovement_122'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e863d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358312' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:232' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:976' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1951', 'source': 'Event_Communication_118', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_238'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358313' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:233' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:976' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1954', 'source': 'Event_Communication_119', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_238'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358314' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:234' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:932' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1959', 'source': 'Event_Communication_120', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_158'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043562' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:234' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:929' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1960', 'source': 'Event_Communication_120', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_84'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7fa60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728810' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:234' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:921' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': 'Event_Communication_120_evidence_for_Relationship_Colleagues_2', 'source': 'Event_Communication_120', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_2'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e080a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358316' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:236' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:796' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1967', 'source': 'Event_Communication_123', 'type': 'evidence_for', 'target': 'Event_VesselMovement_122'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594095' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:236' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1135' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1968', 'source': 'Event_Communication_123', 'type': 'evidence_for', 'target': 'Relationship_Operates_65'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043564' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:236' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:926' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1969', 'source': 'Event_Communication_123', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_66'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358318' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:238' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:11' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1973', 'source': 'Event_Communication_126', 'type': 'evidence_for', 'target': 'Event_Monitoring_129'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358319' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:239' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:934' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1978', 'source': 'Event_Communication_128', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_290'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043567' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:239' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:11' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1977', 'source': 'Event_Communication_128', 'type': 'evidence_for', 'target': 'Event_Monitoring_129'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd64c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358320' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:240' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:11' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1983', 'source': 'Event_Communication_130', 'type': 'evidence_for', 'target': 'Event_Monitoring_129'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043568' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:240' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:953' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1984', 'source': 'Event_Communication_130', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_68'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8d30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728816' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:240' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1025' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1985', 'source': 'Event_Communication_130', 'type': 'evidence_for', 'target': 'Relationship_Reports_69'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99d90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358321' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:241' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1174' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1990', 'source': 'Event_Communication_131', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_71'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043569' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:241' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1177' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1989', 'source': 'Event_Communication_131', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_107'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6f220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358322' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:242' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:934' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1993', 'source': 'Event_Communication_132', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_290'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8d30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358323' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:243' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:12' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1998', 'source': 'Event_Communication_134', 'type': 'evidence_for', 'target': 'Event_Monitoring_133'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043571' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:243' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1026' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '1999', 'source': 'Event_Communication_134', 'type': 'evidence_for', 'target': 'Relationship_Reports_73'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5aa30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728819' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:243' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1175' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2000', 'source': 'Event_Communication_134', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_74'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358326' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:246' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:872' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2006', 'source': 'Event_Communication_139', 'type': 'evidence_for', 'target': 'Event_TourActivity_137'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e966a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043574' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:246' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:796' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2007', 'source': 'Event_Communication_139', 'type': 'evidence_for', 'target': 'Event_VesselMovement_122'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c5e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358327' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:247' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:873' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2010', 'source': 'Event_Communication_141', 'type': 'evidence_for', 'target': 'Event_TourActivity_140'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594096' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:248' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1136' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2014', 'source': 'Event_Communication_142', 'type': 'evidence_for', 'target': 'Relationship_Operates_75'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a6a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043576' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:248' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:970' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2015', 'source': 'Event_Communication_142', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_190'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8c10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358329' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:249' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1069' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2018', 'source': 'Event_Communication_143', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_77'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358330' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:250' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:796' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2021', 'source': 'Event_Communication_145', 'type': 'evidence_for', 'target': 'Event_VesselMovement_122'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8970>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358331' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:251' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1050' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2028', 'source': 'Event_Communication_147', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_390'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043579' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:251' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:976' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2027', 'source': 'Event_Communication_147', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_238'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a550>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728827' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:251' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:795' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2026', 'source': 'Event_Communication_147', 'type': 'evidence_for', 'target': 'Event_VesselMovement_25'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6e50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358332' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:252' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:13' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2031', 'source': 'Event_Communication_149', 'type': 'evidence_for', 'target': 'Event_Monitoring_148'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e485b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358334' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:254' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:23' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2035', 'source': 'Event_Communication_152', 'type': 'evidence_for', 'target': 'Event_Monitoring_266'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c4f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358336' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:256' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:797' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2042', 'source': 'Event_Communication_156', 'type': 'evidence_for', 'target': 'Event_VesselMovement_154'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a550>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043584' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:256' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:927' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2044', 'source': 'Event_Communication_156', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_80'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7970>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728832' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:256' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:954' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2045', 'source': 'Event_Communication_156', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_81'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5bb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414080' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:256' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:763' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2043', 'source': 'Event_Communication_156', 'type': 'evidence_for', 'target': 'Event_Assessment_65'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358337' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:257' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:798' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2051', 'source': 'Event_Communication_158', 'type': 'evidence_for', 'target': 'Event_VesselMovement_157'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043585' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:257' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:928' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2053', 'source': 'Event_Communication_158', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_83'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728833' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:257' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:989' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2052', 'source': 'Event_Communication_158', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_338'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6040>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358339' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:259' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:929' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2058', 'source': 'Event_Communication_160', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_84'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1cfd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043587' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:259' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:946' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2059', 'source': 'Event_Communication_160', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_589'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358343' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:263' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:14' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2066', 'source': 'Event_Communication_165', 'type': 'evidence_for', 'target': 'Event_Monitoring_164'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f4c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358344' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:264' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:76' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2069', 'source': 'Event_Communication_167', 'type': 'evidence_for', 'target': 'Event_Monitoring_946'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de72e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358345' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:265' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:15' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2072', 'source': 'Event_Communication_169', 'type': 'evidence_for', 'target': 'Event_Monitoring_168'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9b430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358346' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:266' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:34' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2075', 'source': 'Event_Communication_171', 'type': 'evidence_for', 'target': 'Event_Monitoring_595'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e533a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358347' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:267' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:767' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2081', 'source': 'Event_Communication_175', 'type': 'evidence_for', 'target': 'Event_Assessment_174'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1be80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043595' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:267' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2082', 'source': 'Event_Communication_175', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358348' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:268' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2085', 'source': 'Event_Communication_176', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358349' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:269' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:846' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2092', 'source': 'Event_Communication_179', 'type': 'evidence_for', 'target': 'Event_Enforcement_177'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e533a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043597' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:269' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1037' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2095', 'source': 'Event_Communication_179', 'type': 'evidence_for', 'target': 'Relationship_Reports_526'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fcd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728845' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:269' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2096', 'source': 'Event_Communication_179', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414093' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:269' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1170' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2094', 'source': 'Event_Communication_179', 'type': 'evidence_for', 'target': 'Relationship_Operates_566'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e659a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1161933101908099341' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:269' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:76' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2093', 'source': 'Event_Communication_179', 'type': 'evidence_for', 'target': 'Event_Monitoring_946'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e538b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358350' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:270' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1037' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2104', 'source': 'Event_Communication_182', 'type': 'evidence_for', 'target': 'Relationship_Reports_526'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4ef70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043598' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:270' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1170' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2105', 'source': 'Event_Communication_182', 'type': 'evidence_for', 'target': 'Relationship_Operates_566'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034710d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728846' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:270' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:76' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2103', 'source': 'Event_Communication_182', 'type': 'evidence_for', 'target': 'Event_Monitoring_946'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b280>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414094' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:270' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:823' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2102', 'source': 'Event_Communication_182', 'type': 'evidence_for', 'target': 'Event_VesselMovement_569'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358352' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:272' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:885' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2111', 'source': 'Event_Communication_186', 'type': 'evidence_for', 'target': 'Event_Collaborate_184'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e86310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043600' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:272' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2113', 'source': 'Event_Communication_186', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fdf0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728848' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:272' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:855' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2112', 'source': 'Event_Communication_186', 'type': 'evidence_for', 'target': 'Event_Enforcement_745'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5afd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358353' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:273' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:874' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2119', 'source': 'Event_Communication_189', 'type': 'evidence_for', 'target': 'Event_TourActivity_188'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043601' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:273' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:955' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2120', 'source': 'Event_Communication_189', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_96'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7fc40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728849' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:273' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:34' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2118', 'source': 'Event_Communication_189', 'type': 'evidence_for', 'target': 'Event_Monitoring_595'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce92b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358354' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:274' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:799' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2124', 'source': 'Event_Communication_191', 'type': 'evidence_for', 'target': 'Event_VesselMovement_190'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043602' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:274' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1138' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2125', 'source': 'Event_Communication_191', 'type': 'evidence_for', 'target': 'Relationship_Operates_97'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358355' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:275' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1063' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2135', 'source': 'Event_Communication_196', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_35'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96a90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043603' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:275' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:17' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2133', 'source': 'Event_Communication_196', 'type': 'evidence_for', 'target': 'Event_Monitoring_192'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e866a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728851' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:275' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:767' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2134', 'source': 'Event_Communication_196', 'type': 'evidence_for', 'target': 'Event_Assessment_174'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e338b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358356' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:276' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:957' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2138', 'source': 'Event_Communication_197', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_100'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358357' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:277' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:768' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2143', 'source': 'Event_Communication_199', 'type': 'evidence_for', 'target': 'Event_Assessment_198'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6f7c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043605' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:277' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:958' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2144', 'source': 'Event_Communication_199', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_101'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728853' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:277' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:930' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2145', 'source': 'Event_Communication_199', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_102'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcfcd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358358' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:278' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:886' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2150', 'source': 'Event_Communication_201', 'type': 'evidence_for', 'target': 'Event_Collaborate_200'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043606' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:278' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1139' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2151', 'source': 'Event_Communication_201', 'type': 'evidence_for', 'target': 'Relationship_Operates_103'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728854' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:278' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1179' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2152', 'source': 'Event_Communication_201', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_110'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc83d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358359' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:279' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1176' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2161', 'source': 'Event_Communication_203', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_106'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e4c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043607' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:279' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1177' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2162', 'source': 'Event_Communication_203', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_107'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6f490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728855' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:279' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1178' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2163', 'source': 'Event_Communication_203', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_108'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b712e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414103' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:279' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:886' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2159', 'source': 'Event_Communication_203', 'type': 'evidence_for', 'target': 'Event_Collaborate_200'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc36a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1161933101908099351' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:279' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:934' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2160', 'source': 'Event_Communication_203', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_290'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e4c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594100' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1140' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2167', 'source': 'Event_Communication_204', 'type': 'evidence_for', 'target': 'Relationship_Operates_109'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a7f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043608' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:280' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1179' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2168', 'source': 'Event_Communication_204', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_110'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b712e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358361' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:281' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1180' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2173', 'source': 'Event_Communication_205', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_112'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3ad60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043609' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:281' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:934' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2172', 'source': 'Event_Communication_205', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_290'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358362' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:282' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1181' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2176', 'source': 'Event_Communication_206', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_113'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358363' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:283' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:934' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2179', 'source': 'Event_Communication_207', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_290'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8d90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358364' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:284' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:18' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2183', 'source': 'Event_Communication_209', 'type': 'evidence_for', 'target': 'Event_Monitoring_208'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0ed90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043612' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:284' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1080' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2184', 'source': 'Event_Communication_209', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_251'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4edf0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358365' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:800' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2188', 'source': 'Event_Communication_211', 'type': 'evidence_for', 'target': 'Event_VesselMovement_210'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043613' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:285' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1070' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2189', 'source': 'Event_Communication_211', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_116'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df70d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358366' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:286' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:23' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2192', 'source': 'Event_Communication_213', 'type': 'evidence_for', 'target': 'Event_Monitoring_266'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358367' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:287' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:957' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2195', 'source': 'Event_Communication_214', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_100'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e862e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358368' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:914' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2200', 'source': 'Event_Communication_216', 'type': 'evidence_for', 'target': 'Event_HarborReport_215'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043616' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:288' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:959' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2201', 'source': 'Event_Communication_216', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_118'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358369' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:289' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2206', 'source': 'Event_Communication_218', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043617' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:289' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:23' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2205', 'source': 'Event_Communication_218', 'type': 'evidence_for', 'target': 'Event_Monitoring_266'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4ec10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358370' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1071' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2214', 'source': 'Event_Communication_221', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_120'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043618' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:931' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2215', 'source': 'Event_Communication_221', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_121'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728866' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:855' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2213', 'source': 'Event_Communication_221', 'type': 'evidence_for', 'target': 'Event_Enforcement_745'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414114' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:290' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2212', 'source': 'Event_Communication_221', 'type': 'evidence_for', 'target': 'Event_Monitoring_38'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e86280>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358371' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:291' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:960' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2219', 'source': 'Event_Communication_222', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_122'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043619' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:291' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1182' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2220', 'source': 'Event_Communication_222', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_123'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358372' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:292' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:769' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2226', 'source': 'Event_Communication_224', 'type': 'evidence_for', 'target': 'Event_Assessment_223'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043620' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:292' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:961' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2228', 'source': 'Event_Communication_224', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_125'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b5b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728868' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:292' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1160' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2227', 'source': 'Event_Communication_224', 'type': 'evidence_for', 'target': 'Relationship_Operates_474'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358373' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:293' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:952' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2231', 'source': 'Event_Communication_225', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_7'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc58b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358374' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:294' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:962' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2235', 'source': 'Event_Communication_226', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_127'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33a90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043622' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:294' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:963' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2236', 'source': 'Event_Communication_226', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_128'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358378' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:298' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:964' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2242', 'source': 'Event_Communication_230', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_129'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358381' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:301' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:19' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2248', 'source': 'Event_Communication_234', 'type': 'evidence_for', 'target': 'Event_Monitoring_232'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9b910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043629' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:301' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:849' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2249', 'source': 'Event_Communication_234', 'type': 'evidence_for', 'target': 'Event_Enforcement_233'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728877' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:301' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2365' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2250', 'source': 'Event_Communication_234', 'type': 'evidence_for', 'target': 'Relationship_Unfriendly_130'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358382' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:850' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2255', 'source': 'Event_Communication_237', 'type': 'evidence_for', 'target': 'Event_Enforcement_235'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26be0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043630' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:887' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2256', 'source': 'Event_Communication_237', 'type': 'evidence_for', 'target': 'Event_Collaborate_236'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9b1f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728878' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:302' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1048' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2257', 'source': 'Event_Communication_237', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_131'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e486a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358383' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1070' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2263', 'source': 'Event_Communication_239', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_116'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f1f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043631' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1144' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2264', 'source': 'Event_Communication_239', 'type': 'evidence_for', 'target': 'Relationship_Operates_176'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6f220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728879' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:303' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:17' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2262', 'source': 'Event_Communication_239', 'type': 'evidence_for', 'target': 'Event_Monitoring_192'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de76a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358385' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:305' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:801' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2270', 'source': 'Event_Communication_244', 'type': 'evidence_for', 'target': 'Event_VesselMovement_242'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaad30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043633' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:305' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:20' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2271', 'source': 'Event_Communication_244', 'type': 'evidence_for', 'target': 'Event_Monitoring_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e339d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728881' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:305' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:821' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2269', 'source': 'Event_Communication_244', 'type': 'evidence_for', 'target': 'Event_VesselMovement_549'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414129' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:305' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:977' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2272', 'source': 'Event_Communication_244', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1cca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358387' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:307' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:821' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2275', 'source': 'Event_Communication_246', 'type': 'evidence_for', 'target': 'Event_VesselMovement_549'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358388' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:308' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1022' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2280', 'source': 'Event_Communication_248', 'type': 'evidence_for', 'target': 'Relationship_Reports_41'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9be50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043636' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:308' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:46' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2279', 'source': 'Event_Communication_248', 'type': 'evidence_for', 'target': 'Event_Monitoring_722'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358389' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:309' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:929' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2286', 'source': 'Event_Communication_249', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_84'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf9d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594111' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:309' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1151' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2285', 'source': 'Event_Communication_249', 'type': 'evidence_for', 'target': 'Relationship_Operates_283'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043637' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:309' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:921' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': 'Event_Communication_249_evidence_for_Relationship_Colleagues_2', 'source': 'Event_Communication_249', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_2'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de77f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358391' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:311' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:916' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2291', 'source': 'Event_Communication_252', 'type': 'evidence_for', 'target': 'Event_TransponderPing_251'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358392' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:312' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:21' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2294', 'source': 'Event_Communication_254', 'type': 'evidence_for', 'target': 'Event_Monitoring_253'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf9d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358393' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:313' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:851' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2302', 'source': 'Event_Communication_258', 'type': 'evidence_for', 'target': 'Event_Enforcement_261'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1cf40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043641' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:313' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1048' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2303', 'source': 'Event_Communication_258', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_131'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33970>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728889' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:313' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:977' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2304', 'source': 'Event_Communication_258', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358394' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:314' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1133' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2309', 'source': 'Event_Communication_260', 'type': 'evidence_for', 'target': 'Relationship_Operates_58'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043642' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:314' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:796' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2308', 'source': 'Event_Communication_260', 'type': 'evidence_for', 'target': 'Event_VesselMovement_122'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf4f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358395' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:315' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:851' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2314', 'source': 'Event_Communication_262', 'type': 'evidence_for', 'target': 'Event_Enforcement_261'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9b7c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043643' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:315' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1048' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2315', 'source': 'Event_Communication_262', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_131'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8af0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728891' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:315' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:977' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2316', 'source': 'Event_Communication_262', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358396' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:316' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:918' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2319', 'source': 'Event_Communication_264', 'type': 'evidence_for', 'target': 'Event_TransponderPing_308'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358397' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:317' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:23' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2324', 'source': 'Event_Communication_267', 'type': 'evidence_for', 'target': 'Event_Monitoring_266'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33e20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043645' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:317' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:918' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2323', 'source': 'Event_Communication_267', 'type': 'evidence_for', 'target': 'Event_TransponderPing_308'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaa8e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358399' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1183' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2331', 'source': 'Event_Communication_270', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_145'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0efa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043647' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:918' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2330', 'source': 'Event_Communication_270', 'type': 'evidence_for', 'target': 'Event_TransponderPing_308'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff5e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594043' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:319' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1083' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2332', 'source': 'Event_Communication_270', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_269'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaa0a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358400' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:320' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:917' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2337', 'source': 'Event_Communication_272', 'type': 'evidence_for', 'target': 'Event_TransponderPing_271'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73d30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043648' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:320' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:965' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2339', 'source': 'Event_Communication_272', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_148'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fb20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728896' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:320' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1183' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2338', 'source': 'Event_Communication_272', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_145'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358401' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:887' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2345', 'source': 'Event_Communication_275', 'type': 'evidence_for', 'target': 'Event_Collaborate_236'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9b460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043649' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2346', 'source': 'Event_Communication_275', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7e80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728897' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:321' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:850' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2344', 'source': 'Event_Communication_275', 'type': 'evidence_for', 'target': 'Event_Enforcement_235'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0efa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358402' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:322' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:888' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2349', 'source': 'Event_Communication_277', 'type': 'evidence_for', 'target': 'Event_Collaborate_276'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1b670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043650' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:322' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:922' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': 'Event_Communication_277_evidence_for_Relationship_Colleagues_11', 'source': 'Event_Communication_277', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_11'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358403' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:323' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:922' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2355', 'source': 'Event_Communication_278', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_11'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaafd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043651' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:323' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:932' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2354', 'source': 'Event_Communication_278', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_158'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a1f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358404' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:324' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:922' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2358', 'source': 'Event_Communication_279', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_11'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6f8e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043652' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:324' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:932' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2357', 'source': 'Event_Communication_279', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_158'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3abb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594101' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:325' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1141' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2367', 'source': 'Event_Communication_280', 'type': 'evidence_for', 'target': 'Relationship_Operates_153'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce9910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043653' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:325' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1142' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2368', 'source': 'Event_Communication_280', 'type': 'evidence_for', 'target': 'Relationship_Operates_154'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e86910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728901' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:325' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:966' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2370', 'source': 'Event_Communication_280', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_156'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0eac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414149' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:325' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:932' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2372', 'source': 'Event_Communication_280', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_158'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96bb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1161933101908099397' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:325' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:921' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2371', 'source': 'Event_Communication_280', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_2'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53df0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1164184901721784645' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:325' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:958' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2369', 'source': 'Event_Communication_280', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_101'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1166436701535469893' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:325' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:922' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': 'Event_Communication_280_evidence_for_Relationship_Colleagues_11', 'source': 'Event_Communication_280', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_11'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fc70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358406' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:326' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:967' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2378', 'source': 'Event_Communication_281', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_161'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7fbb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043654' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:326' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1049' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2379', 'source': 'Event_Communication_281', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_162'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53df0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594129' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:326' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1169' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2377', 'source': 'Event_Communication_281', 'type': 'evidence_for', 'target': 'Relationship_Operates_546'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358407' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:327' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:968' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2383', 'source': 'Event_Communication_282', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_163'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7ff40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043655' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:327' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1169' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2384', 'source': 'Event_Communication_282', 'type': 'evidence_for', 'target': 'Relationship_Operates_546'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358408' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:328' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1133' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2387', 'source': 'Event_Communication_283', 'type': 'evidence_for', 'target': 'Relationship_Operates_58'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6f4f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358409' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:329' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:802' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2390', 'source': 'Event_Communication_285', 'type': 'evidence_for', 'target': 'Event_VesselMovement_284'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358410' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:330' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:24' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2394', 'source': 'Event_Communication_287', 'type': 'evidence_for', 'target': 'Event_Monitoring_286'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb01f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043658' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:330' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1098' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2395', 'source': 'Event_Communication_287', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_380'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a9a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358411' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:331' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:803' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2398', 'source': 'Event_Communication_289', 'type': 'evidence_for', 'target': 'Event_VesselMovement_288'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358412' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:332' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1133' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2403', 'source': 'Event_Communication_291', 'type': 'evidence_for', 'target': 'Relationship_Operates_58'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043660' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:332' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:821' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2402', 'source': 'Event_Communication_291', 'type': 'evidence_for', 'target': 'Event_VesselMovement_549'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7fa60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358413' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:333' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:852' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2407', 'source': 'Event_Communication_293', 'type': 'evidence_for', 'target': 'Event_Enforcement_292'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043661' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:333' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2408', 'source': 'Event_Communication_293', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358414' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:334' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1133' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2413', 'source': 'Event_Communication_295', 'type': 'evidence_for', 'target': 'Relationship_Operates_58'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043662' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:334' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:796' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2412', 'source': 'Event_Communication_295', 'type': 'evidence_for', 'target': 'Event_VesselMovement_122'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e263a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358415' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:335' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:23' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2416', 'source': 'Event_Communication_297', 'type': 'evidence_for', 'target': 'Event_Monitoring_266'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e2e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358416' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:336' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:918' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2419', 'source': 'Event_Communication_299', 'type': 'evidence_for', 'target': 'Event_TransponderPing_308'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358417' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:337' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:804' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2423', 'source': 'Event_Communication_301', 'type': 'evidence_for', 'target': 'Event_VesselMovement_300'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1cd90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687593987' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:337' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1027' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2424', 'source': 'Event_Communication_301', 'type': 'evidence_for', 'target': 'Relationship_Reports_170'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358419' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:339' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:805' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2429', 'source': 'Event_Communication_304', 'type': 'evidence_for', 'target': 'Event_VesselMovement_303'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358421' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:341' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:918' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2438', 'source': 'Event_Communication_309', 'type': 'evidence_for', 'target': 'Event_TransponderPing_308'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043669' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:341' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:796' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2436', 'source': 'Event_Communication_309', 'type': 'evidence_for', 'target': 'Event_VesselMovement_122'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728917' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:341' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:977' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2439', 'source': 'Event_Communication_309', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034710a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414165' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:341' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:771' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2437', 'source': 'Event_Communication_309', 'type': 'evidence_for', 'target': 'Event_Assessment_337'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358422' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:342' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1072' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2445', 'source': 'Event_Communication_311', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_172'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043670' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:342' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1041' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2446', 'source': 'Event_Communication_311', 'type': 'evidence_for', 'target': 'Relationship_Reports_587'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728918' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:342' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:52' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2444', 'source': 'Event_Communication_311', 'type': 'evidence_for', 'target': 'Event_Monitoring_803'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd87f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358424' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:344' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1148' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2450', 'source': 'Event_Communication_313', 'type': 'evidence_for', 'target': 'Relationship_Operates_255'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358425' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:345' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:17' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2455', 'source': 'Event_Communication_316', 'type': 'evidence_for', 'target': 'Event_Monitoring_192'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e338b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043673' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:345' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:796' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2454', 'source': 'Event_Communication_316', 'type': 'evidence_for', 'target': 'Event_VesselMovement_122'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1cf40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358427' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:347' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:977' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2459', 'source': 'Event_Communication_318', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358428' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:348' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1144' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2464', 'source': 'Event_Communication_320', 'type': 'evidence_for', 'target': 'Relationship_Operates_176'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9b0a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043676' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:348' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:17' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2463', 'source': 'Event_Communication_320', 'type': 'evidence_for', 'target': 'Event_Monitoring_192'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd64c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358429' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:349' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:981' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2467', 'source': 'Event_Communication_321', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_266'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9ba00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358430' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:350' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2474', 'source': 'Event_Communication_323', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73e20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043678' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:350' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:764' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2472', 'source': 'Event_Communication_323', 'type': 'evidence_for', 'target': 'Event_Assessment_101'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc87f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728926' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:350' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:981' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2473', 'source': 'Event_Communication_323', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_266'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd64c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358431' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:351' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2355' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2479', 'source': 'Event_Communication_325', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_368'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9b6d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043679' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:351' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:17' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2478', 'source': 'Event_Communication_325', 'type': 'evidence_for', 'target': 'Event_Monitoring_192'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358432' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:352' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:806' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2482', 'source': 'Event_Communication_327', 'type': 'evidence_for', 'target': 'Event_VesselMovement_326'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fc70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358434' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:354' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:770' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2487', 'source': 'Event_Communication_330', 'type': 'evidence_for', 'target': 'Event_Assessment_329'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcfcd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043682' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:354' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:969' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2488', 'source': 'Event_Communication_330', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_181'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9b6d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358435' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:355' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:969' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2491', 'source': 'Event_Communication_331', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_181'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaa400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358436' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:356' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:969' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2494', 'source': 'Event_Communication_332', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_181'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358439' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:359' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1073' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2503', 'source': 'Event_Communication_336', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_185'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043687' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:359' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1041' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2502', 'source': 'Event_Communication_336', 'type': 'evidence_for', 'target': 'Relationship_Reports_587'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaad60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728935' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:359' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:761' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2501', 'source': 'Event_Communication_336', 'type': 'evidence_for', 'target': 'Event_Assessment_41'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e86430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358440' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:360' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:771' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2506', 'source': 'Event_Communication_338', 'type': 'evidence_for', 'target': 'Event_Assessment_337'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358441' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:361' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2509', 'source': 'Event_Communication_339', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a7f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594049' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:362' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1089' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2512', 'source': 'Event_Communication_340', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_297'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb23d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358443' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:363' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1089' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2515', 'source': 'Event_Communication_341', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_297'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b712e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358444' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:364' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:970' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2522', 'source': 'Event_Communication_343', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_190'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043692' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:364' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1133' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2521', 'source': 'Event_Communication_343', 'type': 'evidence_for', 'target': 'Relationship_Operates_58'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99dc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728940' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:364' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:796' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2520', 'source': 'Event_Communication_343', 'type': 'evidence_for', 'target': 'Event_VesselMovement_122'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65be0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358445' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:365' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:807' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2525', 'source': 'Event_Communication_345', 'type': 'evidence_for', 'target': 'Event_VesselMovement_344'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043693' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:365' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:971' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2527', 'source': 'Event_Communication_345', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_192'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728941' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:365' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:992' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2526', 'source': 'Event_Communication_345', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_382'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb25e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358446' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:366' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:821' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2531', 'source': 'Event_Communication_347', 'type': 'evidence_for', 'target': 'Event_VesselMovement_549'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65be0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043694' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:366' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:977' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2532', 'source': 'Event_Communication_347', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358447' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:367' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:796' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2536', 'source': 'Event_Communication_349', 'type': 'evidence_for', 'target': 'Event_VesselMovement_122'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaaf70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043695' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:367' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:970' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2537', 'source': 'Event_Communication_349', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_190'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9be50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358448' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:368' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2540', 'source': 'Event_Communication_350', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358449' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:369' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:972' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2544', 'source': 'Event_Communication_351', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_196'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043697' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:369' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2545', 'source': 'Event_Communication_351', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358450' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:370' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1006' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2550', 'source': 'Event_Communication_353', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_497'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043698' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:370' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:76' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2549', 'source': 'Event_Communication_353', 'type': 'evidence_for', 'target': 'Event_Monitoring_946'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99550>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358451' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:371' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1170' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2555', 'source': 'Event_Communication_354', 'type': 'evidence_for', 'target': 'Relationship_Operates_566'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7bb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043699' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:371' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1006' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2554', 'source': 'Event_Communication_354', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_497'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99d30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358453' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:373' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1074' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2559', 'source': 'Event_Communication_356', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_201'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358454' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:374' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1145' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2564', 'source': 'Event_Communication_357', 'type': 'evidence_for', 'target': 'Relationship_Operates_202'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9bfa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043702' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:374' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:934' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2566', 'source': 'Event_Communication_357', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_290'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e488b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728950' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:374' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1176' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2565', 'source': 'Event_Communication_357', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_106'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e995b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358455' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:375' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:25' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2570', 'source': 'Event_Communication_359', 'type': 'evidence_for', 'target': 'Event_Monitoring_358'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043703' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:375' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1028' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2571', 'source': 'Event_Communication_359', 'type': 'evidence_for', 'target': 'Relationship_Reports_205'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358456' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:376' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:934' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2574', 'source': 'Event_Communication_360', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_290'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358459' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:379' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:808' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2582', 'source': 'Event_Communication_365', 'type': 'evidence_for', 'target': 'Event_VesselMovement_363'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043707' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:379' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:893' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2583', 'source': 'Event_Communication_365', 'type': 'evidence_for', 'target': 'Event_Collaborate_364'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728955' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:379' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:977' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2584', 'source': 'Event_Communication_365', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594144' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:380' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1184' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2591', 'source': 'Event_Communication_366', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_209'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65970>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594106' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:380' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1146' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2592', 'source': 'Event_Communication_366', 'type': 'evidence_for', 'target': 'Relationship_Operates_210'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594107' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:380' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1147' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2593', 'source': 'Event_Communication_366', 'type': 'evidence_for', 'target': 'Relationship_Operates_211'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bf70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043708' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:380' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:921' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': 'Event_Communication_366_evidence_for_Relationship_Colleagues_2', 'source': 'Event_Communication_366', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_2'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358462' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:382' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:973' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2597', 'source': 'Event_Communication_368', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_214'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bc10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358463' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:383' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:973' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2600', 'source': 'Event_Communication_369', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_214'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358464' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:384' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:933' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2605', 'source': 'Event_Communication_370', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_215'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687595308' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:384' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2348' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2607', 'source': 'Event_Communication_370', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_217'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53af0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043712' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:384' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:940' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2606', 'source': 'Event_Communication_370', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_430'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358465' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:385' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1029' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2611', 'source': 'Event_Communication_371', 'type': 'evidence_for', 'target': 'Relationship_Reports_218'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb25b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043713' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:385' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2349' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2612', 'source': 'Event_Communication_371', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_219'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358466' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:386' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1022' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2617', 'source': 'Event_Communication_372', 'type': 'evidence_for', 'target': 'Relationship_Reports_41'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd87c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043714' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:386' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:977' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2616', 'source': 'Event_Communication_372', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358467' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:387' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1113' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2622', 'source': 'Event_Communication_373', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_499'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043715' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:387' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:977' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2621', 'source': 'Event_Communication_373', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358468' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:388' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2625', 'source': 'Event_Communication_375', 'type': 'evidence_for', 'target': 'Event_Monitoring_38'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358470' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:390' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:934' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2629', 'source': 'Event_Communication_377', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_290'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358471' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:391' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:977' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2632', 'source': 'Event_Communication_378', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8bb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358472' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:392' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1075' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2637', 'source': 'Event_Communication_380', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_226'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6f7c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043720' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:392' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:796' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2636', 'source': 'Event_Communication_380', 'type': 'evidence_for', 'target': 'Event_VesselMovement_122'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb5f40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358473' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:393' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:997' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2641', 'source': 'Event_Communication_381', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_415'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb5c10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043721' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:393' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2642', 'source': 'Event_Communication_381', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a2b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358474' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:394' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2366' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2646', 'source': 'Event_Communication_382', 'type': 'evidence_for', 'target': 'Relationship_Unfriendly_229'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043722' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:394' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2647', 'source': 'Event_Communication_382', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358475' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:395' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:26' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2651', 'source': 'Event_Communication_384', 'type': 'evidence_for', 'target': 'Event_Monitoring_383'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594036' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:395' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1076' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2652', 'source': 'Event_Communication_384', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_231'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e533a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358476' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:396' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:974' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2657', 'source': 'Event_Communication_386', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_232'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6f070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043724' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:396' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:76' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2656', 'source': 'Event_Communication_386', 'type': 'evidence_for', 'target': 'Event_Monitoring_946'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358477' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:397' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:975' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2661', 'source': 'Event_Communication_387', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_233'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4ea90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043725' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:397' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1054' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2662', 'source': 'Event_Communication_387', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_583'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a5b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358478' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:398' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:945' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2665', 'source': 'Event_Communication_388', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_551'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358479' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:399' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1077' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2668', 'source': 'Event_Communication_389', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_236'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358480' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:400' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:952' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2671', 'source': 'Event_Communication_390', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_7'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b712e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358481' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:401' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:976' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2676', 'source': 'Event_Communication_392', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_238'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034710d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043729' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:401' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:795' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2675', 'source': 'Event_Communication_392', 'type': 'evidence_for', 'target': 'Event_VesselMovement_25'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e280>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358482' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:402' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:809' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2680', 'source': 'Event_Communication_394', 'type': 'evidence_for', 'target': 'Event_VesselMovement_393'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043730' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:402' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:996' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2681', 'source': 'Event_Communication_394', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_405'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358483' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:403' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:796' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2685', 'source': 'Event_Communication_396', 'type': 'evidence_for', 'target': 'Event_VesselMovement_122'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a5e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043731' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:403' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:977' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2686', 'source': 'Event_Communication_396', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e280>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358484' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:404' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:796' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2691', 'source': 'Event_Communication_399', 'type': 'evidence_for', 'target': 'Event_VesselMovement_122'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043732' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:404' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:977' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2693', 'source': 'Event_Communication_399', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728980' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:404' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:880' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2692', 'source': 'Event_Communication_399', 'type': 'evidence_for', 'target': 'Event_TourActivity_962'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358485' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:405' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:977' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2700', 'source': 'Event_Communication_401', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043733' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:405' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:821' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2698', 'source': 'Event_Communication_401', 'type': 'evidence_for', 'target': 'Event_VesselMovement_549'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e0d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728981' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:405' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:950' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': 'Event_Communication_401_evidence_for_Relationship_Colleagues_619', 'source': 'Event_Communication_401', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_619'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358486' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:406' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:811' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2705', 'source': 'Event_Communication_403', 'type': 'evidence_for', 'target': 'Event_VesselMovement_402'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73bb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043734' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:406' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:978' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2706', 'source': 'Event_Communication_403', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_244'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728982' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:406' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1109' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2707', 'source': 'Event_Communication_403', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_471'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358487' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:407' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:796' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2710', 'source': 'Event_Communication_405', 'type': 'evidence_for', 'target': 'Event_VesselMovement_122'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf4f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358488' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:408' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1078' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2714', 'source': 'Event_Communication_406', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_247'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043736' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:408' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:973' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2713', 'source': 'Event_Communication_406', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_214'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358489' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:409' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:795' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2717', 'source': 'Event_Communication_408', 'type': 'evidence_for', 'target': 'Event_VesselMovement_25'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9b370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594039' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:410' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1079' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2720', 'source': 'Event_Communication_409', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_248'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e657c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358491' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:411' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:27' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2723', 'source': 'Event_Communication_411', 'type': 'evidence_for', 'target': 'Event_Monitoring_410'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb09d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043739' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:411' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1144' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2724', 'source': 'Event_Communication_411', 'type': 'evidence_for', 'target': 'Relationship_Operates_176'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358492' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:412' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2729', 'source': 'Event_Communication_413', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaa340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043740' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:412' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:17' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2728', 'source': 'Event_Communication_413', 'type': 'evidence_for', 'target': 'Event_Monitoring_192'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358493' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:413' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:28' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2733', 'source': 'Event_Communication_415', 'type': 'evidence_for', 'target': 'Event_Monitoring_414'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaa2b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043741' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:413' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1080' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2734', 'source': 'Event_Communication_415', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_251'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358494' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:414' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1081' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2739', 'source': 'Event_Communication_417', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_252'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc58b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043742' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:414' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:52' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2738', 'source': 'Event_Communication_417', 'type': 'evidence_for', 'target': 'Event_Monitoring_803'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358495' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:415' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:812' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2741', 'source': 'Event_Communication_419', 'type': 'evidence_for', 'target': 'Event_VesselMovement_418'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9bf70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594042' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:416' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1082' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2746', 'source': 'Event_Communication_420', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_253'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e868b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358497' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:417' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1148' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2752', 'source': 'Event_Communication_421', 'type': 'evidence_for', 'target': 'Relationship_Operates_255'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5afd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043745' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:417' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1149' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2753', 'source': 'Event_Communication_421', 'type': 'evidence_for', 'target': 'Relationship_Operates_256'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaadf0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728993' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:417' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1079' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2751', 'source': 'Event_Communication_421', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_248'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8cd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358498' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:418' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:894' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2757', 'source': 'Event_Communication_423', 'type': 'evidence_for', 'target': 'Event_Collaborate_422'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e868b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043746' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:418' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:979' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2760', 'source': 'Event_Communication_423', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_259'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5afd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728994' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:418' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1148' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2759', 'source': 'Event_Communication_423', 'type': 'evidence_for', 'target': 'Relationship_Operates_255'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594052' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:418' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1092' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2758', 'source': 'Event_Communication_423', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_305'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2dc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358499' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:419' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:895' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2763', 'source': 'Event_Communication_425', 'type': 'evidence_for', 'target': 'Event_Collaborate_424'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043747' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:419' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1089' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2764', 'source': 'Event_Communication_425', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_297'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9bca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358500' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:420' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:980' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2769', 'source': 'Event_Communication_426', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_262'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf9a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043748' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:420' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1092' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2768', 'source': 'Event_Communication_426', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_305'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9b640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358501' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:421' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1120' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2775', 'source': 'Event_Communication_428', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_555'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9b760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043749' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:421' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:144' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2774', 'source': 'Event_Communication_428', 'type': 'evidence_for', 'target': 'Event_Monitoring_978'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a970>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728997' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:421' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:974' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2776', 'source': 'Event_Communication_428', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_232'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358502' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:422' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1132' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2783', 'source': 'Event_Communication_431', 'type': 'evidence_for', 'target': 'Relationship_Operates_36'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaa910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043750' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:422' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:918' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2782', 'source': 'Event_Communication_431', 'type': 'evidence_for', 'target': 'Event_TransponderPing_308'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaa0d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728998' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:422' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:144' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2781', 'source': 'Event_Communication_431', 'type': 'evidence_for', 'target': 'Event_Monitoring_978'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73b80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358503' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:423' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:981' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2789', 'source': 'Event_Communication_433', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_266'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a6d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043751' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:423' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2790', 'source': 'Event_Communication_433', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dcf0a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280728999' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:423' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:793' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2788', 'source': 'Event_Communication_433', 'type': 'evidence_for', 'target': 'Event_Assessment_973'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358504' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:424' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:23' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2793', 'source': 'Event_Communication_435', 'type': 'evidence_for', 'target': 'Event_Monitoring_266'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2be0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358506' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:426' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1083' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2799', 'source': 'Event_Communication_437', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_269'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8af0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043754' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:426' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1144' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2798', 'source': 'Event_Communication_437', 'type': 'evidence_for', 'target': 'Relationship_Operates_176'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9b100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358508' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:428' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1150' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2805', 'source': 'Event_Communication_439', 'type': 'evidence_for', 'target': 'Relationship_Operates_271'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff5e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043756' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:428' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1054' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2804', 'source': 'Event_Communication_439', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_583'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4ee80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358509' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:429' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:809' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2808', 'source': 'Event_Communication_441', 'type': 'evidence_for', 'target': 'Event_VesselMovement_393'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e338b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358511' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:431' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:920' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2812', 'source': 'Event_Communication_443', 'type': 'evidence_for', 'target': 'Relationship_Friends_272'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9be50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358512' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:432' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:29' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2818', 'source': 'Event_Communication_446', 'type': 'evidence_for', 'target': 'Event_Monitoring_444'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034710a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043760' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:432' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:772' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2819', 'source': 'Event_Communication_446', 'type': 'evidence_for', 'target': 'Event_Assessment_445'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e86d60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729008' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:432' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1084' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2821', 'source': 'Event_Communication_446', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_274'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53af0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414256' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:432' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1164' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2820', 'source': 'Event_Communication_446', 'type': 'evidence_for', 'target': 'Relationship_Operates_514'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaa670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358513' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:433' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:796' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2826', 'source': 'Event_Communication_449', 'type': 'evidence_for', 'target': 'Event_VesselMovement_122'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaab20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043761' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:433' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:970' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2828', 'source': 'Event_Communication_449', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_190'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e86d60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729009' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:433' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:52' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2827', 'source': 'Event_Communication_449', 'type': 'evidence_for', 'target': 'Event_Monitoring_803'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594055' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:434' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1095' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2834', 'source': 'Event_Communication_451', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_336'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e0d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043762' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:434' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:796' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2833', 'source': 'Event_Communication_451', 'type': 'evidence_for', 'target': 'Event_VesselMovement_122'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729010' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:434' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:970' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2835', 'source': 'Event_Communication_451', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_190'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fb20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358515' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:435' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:809' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2839', 'source': 'Event_Communication_453', 'type': 'evidence_for', 'target': 'Event_VesselMovement_393'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043763' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:435' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:996' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2840', 'source': 'Event_Communication_453', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_405'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9b820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358516' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:436' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:897' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2846', 'source': 'Event_Communication_456', 'type': 'evidence_for', 'target': 'Event_Collaborate_455'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5af40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594045' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:436' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1085' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2847', 'source': 'Event_Communication_456', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_279'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fb20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043764' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:436' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:816' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2845', 'source': 'Event_Communication_456', 'type': 'evidence_for', 'target': 'Event_VesselMovement_503'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594046' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:437' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1086' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2854', 'source': 'Event_Communication_458', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_280'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043765' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:437' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:982' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2855', 'source': 'Event_Communication_458', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_281'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fcd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729013' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:437' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:816' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2853', 'source': 'Event_Communication_458', 'type': 'evidence_for', 'target': 'Event_VesselMovement_503'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e962b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358518' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:438' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:816' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2858', 'source': 'Event_Communication_460', 'type': 'evidence_for', 'target': 'Event_VesselMovement_503'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7fa90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594050' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:439' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1090' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2863', 'source': 'Event_Communication_462', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_298'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e993a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043767' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:439' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:796' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2862', 'source': 'Event_Communication_462', 'type': 'evidence_for', 'target': 'Event_VesselMovement_122'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd87f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358520' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:440' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:773' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2867', 'source': 'Event_Communication_464', 'type': 'evidence_for', 'target': 'Event_Assessment_463'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043768' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:440' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1151' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2868', 'source': 'Event_Communication_464', 'type': 'evidence_for', 'target': 'Relationship_Operates_283'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4ec40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358521' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:441' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:52' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2874', 'source': 'Event_Communication_467', 'type': 'evidence_for', 'target': 'Event_Monitoring_803'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5aa00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043769' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:441' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:977' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2875', 'source': 'Event_Communication_467', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6ff40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729017' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:441' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:918' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2873', 'source': 'Event_Communication_467', 'type': 'evidence_for', 'target': 'Event_TransponderPing_308'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96e50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358522' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:442' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:934' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2878', 'source': 'Event_Communication_468', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_290'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e966a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358524' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:444' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:934' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2882', 'source': 'Event_Communication_470', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_290'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e969d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358525' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:445' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:809' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2886', 'source': 'Event_Communication_473', 'type': 'evidence_for', 'target': 'Event_VesselMovement_393'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e86220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043773' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:445' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:776' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2887', 'source': 'Event_Communication_473', 'type': 'evidence_for', 'target': 'Event_Assessment_522'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96e50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358528' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:448' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:934' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2892', 'source': 'Event_Communication_476', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_290'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e863d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358529' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:449' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:898' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2897', 'source': 'Event_Communication_478', 'type': 'evidence_for', 'target': 'Event_Collaborate_477'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb5ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043777' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:449' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1030' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2898', 'source': 'Event_Communication_478', 'type': 'evidence_for', 'target': 'Relationship_Reports_288'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec46a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729025' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:449' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1087' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2899', 'source': 'Event_Communication_478', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_289'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358530' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:450' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:934' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2902', 'source': 'Event_Communication_479', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_290'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358531' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:451' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:36' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2907', 'source': 'Event_Communication_482', 'type': 'evidence_for', 'target': 'Event_Monitoring_631'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fdf0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043779' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:451' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1088' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2909', 'source': 'Event_Communication_482', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_292'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729027' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:451' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:793' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2908', 'source': 'Event_Communication_482', 'type': 'evidence_for', 'target': 'Event_Assessment_973'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358532' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:452' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:813' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2915', 'source': 'Event_Communication_485', 'type': 'evidence_for', 'target': 'Event_VesselMovement_483'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bcd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043780' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:452' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:30' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2916', 'source': 'Event_Communication_485', 'type': 'evidence_for', 'target': 'Event_Monitoring_484'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb58e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729028' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:452' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1088' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2917', 'source': 'Event_Communication_485', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_292'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec4fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687595310' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:452' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2350' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2918', 'source': 'Event_Communication_485', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_293'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358533' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:453' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:809' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2921', 'source': 'Event_Communication_487', 'type': 'evidence_for', 'target': 'Event_VesselMovement_393'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358534' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:454' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:774' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2924', 'source': 'Event_Communication_489', 'type': 'evidence_for', 'target': 'Event_Assessment_488'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb53d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358535' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:455' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:31' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2927', 'source': 'Event_Communication_491', 'type': 'evidence_for', 'target': 'Event_Monitoring_490'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043783' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:455' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2351' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2928', 'source': 'Event_Communication_491', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_294'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd60d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358536' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:456' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:775' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2932', 'source': 'Event_Communication_493', 'type': 'evidence_for', 'target': 'Event_Assessment_492'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043784' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:456' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1089' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2933', 'source': 'Event_Communication_493', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_297'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358537' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:457' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:814' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2938', 'source': 'Event_Communication_496', 'type': 'evidence_for', 'target': 'Event_VesselMovement_494'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043785' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:457' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:815' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2939', 'source': 'Event_Communication_496', 'type': 'evidence_for', 'target': 'Event_VesselMovement_495'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729033' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:457' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1099' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2940', 'source': 'Event_Communication_496', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_387'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358538' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:458' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:875' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2945', 'source': 'Event_Communication_499', 'type': 'evidence_for', 'target': 'Event_TourActivity_498'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043786' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:458' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1089' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2946', 'source': 'Event_Communication_499', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_297'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729034' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:458' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:818' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2944', 'source': 'Event_Communication_499', 'type': 'evidence_for', 'target': 'Event_VesselMovement_510'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358539' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:459' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:817' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2949', 'source': 'Event_Communication_501', 'type': 'evidence_for', 'target': 'Event_VesselMovement_509'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358541' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:461' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:816' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2954', 'source': 'Event_Communication_504', 'type': 'evidence_for', 'target': 'Event_VesselMovement_503'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf4f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043789' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:461' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1090' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2955', 'source': 'Event_Communication_504', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_298'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358542' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:462' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:811' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2959', 'source': 'Event_Communication_506', 'type': 'evidence_for', 'target': 'Event_VesselMovement_402'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9baf0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043790' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:462' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:982' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2960', 'source': 'Event_Communication_506', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_281'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a7f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358543' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:463' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1092' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2965', 'source': 'Event_Communication_508', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_305'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x124b71f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043791' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:463' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:809' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2964', 'source': 'Event_Communication_508', 'type': 'evidence_for', 'target': 'Event_VesselMovement_393'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358544' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:464' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:817' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2971', 'source': 'Event_Communication_511', 'type': 'evidence_for', 'target': 'Event_VesselMovement_509'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaad60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043792' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:464' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:818' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2972', 'source': 'Event_Communication_511', 'type': 'evidence_for', 'target': 'Event_VesselMovement_510'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de84f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729040' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:464' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1091' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2974', 'source': 'Event_Communication_511', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_302'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8970>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594121' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:464' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1161' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2973', 'source': 'Event_Communication_511', 'type': 'evidence_for', 'target': 'Relationship_Operates_476'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358545' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:465' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:900' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2979', 'source': 'Event_Communication_513', 'type': 'evidence_for', 'target': 'Event_Collaborate_512'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043793' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:465' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:983' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2980', 'source': 'Event_Communication_513', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_303'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9b640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729041' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:465' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:984' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2981', 'source': 'Event_Communication_513', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_304'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358546' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:466' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1092' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2987', 'source': 'Event_Communication_515', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_305'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7fa30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043794' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:466' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:985' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2988', 'source': 'Event_Communication_515', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_306'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729042' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:466' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:818' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2986', 'source': 'Event_Communication_515', 'type': 'evidence_for', 'target': 'Event_VesselMovement_510'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf3d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358547' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:467' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:819' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2994', 'source': 'Event_Communication_518', 'type': 'evidence_for', 'target': 'Event_VesselMovement_516'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb5520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043795' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:467' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:901' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2995', 'source': 'Event_Communication_518', 'type': 'evidence_for', 'target': 'Event_Collaborate_517'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594053' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:467' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1093' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '2996', 'source': 'Event_Communication_518', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_307'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358551' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:471' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:776' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3002', 'source': 'Event_Communication_523', 'type': 'evidence_for', 'target': 'Event_Assessment_522'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99df0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358552' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:472' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1164' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3008', 'source': 'Event_Communication_525', 'type': 'evidence_for', 'target': 'Relationship_Operates_514'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaa2b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043800' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:472' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:996' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3009', 'source': 'Event_Communication_525', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_405'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729048' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:472' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:36' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3007', 'source': 'Event_Communication_525', 'type': 'evidence_for', 'target': 'Event_Monitoring_631'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358553' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:473' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2367' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3020', 'source': 'Event_Communication_528', 'type': 'evidence_for', 'target': 'Relationship_Unfriendly_312'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a7f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043801' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:473' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:36' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3017', 'source': 'Event_Communication_528', 'type': 'evidence_for', 'target': 'Event_Monitoring_631'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9b8e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729049' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:473' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:821' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3016', 'source': 'Event_Communication_528', 'type': 'evidence_for', 'target': 'Event_VesselMovement_549'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9b190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414297' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:473' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:940' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3019', 'source': 'Event_Communication_528', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_430'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1161933101908099545' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:473' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:937' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': 'Event_Communication_528_evidence_for_Relationship_Colleagues_321', 'source': 'Event_Communication_528', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_321'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e994c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358554' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:474' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:986' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3023', 'source': 'Event_Communication_529', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_313'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9b670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358555' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:475' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:32' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3027', 'source': 'Event_Communication_531', 'type': 'evidence_for', 'target': 'Event_Monitoring_530'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5bb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043803' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:475' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1041' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3028', 'source': 'Event_Communication_531', 'type': 'evidence_for', 'target': 'Relationship_Reports_587'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e087f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358556' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:476' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1041' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3034', 'source': 'Event_Communication_533', 'type': 'evidence_for', 'target': 'Relationship_Reports_587'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b1c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043804' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:476' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3035', 'source': 'Event_Communication_533', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65280>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729052' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:476' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3033', 'source': 'Event_Communication_533', 'type': 'evidence_for', 'target': 'Event_Monitoring_38'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358557' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:477' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:33' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3040', 'source': 'Event_Communication_535', 'type': 'evidence_for', 'target': 'Event_Monitoring_534'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043805' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:477' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2352' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3041', 'source': 'Event_Communication_535', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_317'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729053' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:477' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:942' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': 'Event_Communication_535_evidence_for_Relationship_Colleagues_494', 'source': 'Event_Communication_535', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_494'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9bc70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358559' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:479' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:935' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3048', 'source': 'Event_Communication_537', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_319'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e486a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043807' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:479' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:936' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3049', 'source': 'Event_Communication_537', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_320'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729055' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:479' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:937' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3050', 'source': 'Event_Communication_537', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_321'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358560' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:480' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:938' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3053', 'source': 'Event_Communication_538', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_322'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358562' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:482' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:820' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3058', 'source': 'Event_Communication_541', 'type': 'evidence_for', 'target': 'Event_VesselMovement_540'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e486a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687593899' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:482' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:939' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3059', 'source': 'Event_Communication_541', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_323'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358563' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:483' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:902' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3063', 'source': 'Event_Communication_543', 'type': 'evidence_for', 'target': 'Event_Collaborate_542'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043811' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:483' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1099' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3064', 'source': 'Event_Communication_543', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_387'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358564' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:484' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:997' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3067', 'source': 'Event_Communication_544', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_415'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358565' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:485' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:977' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3070', 'source': 'Event_Communication_545', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6f490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358566' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:486' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3074', 'source': 'Event_Communication_546', 'type': 'evidence_for', 'target': 'Relationship_Operates_327'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043814' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:486' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:987' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3075', 'source': 'Event_Communication_546', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_328'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358567' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:487' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1133' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3081', 'source': 'Event_Communication_548', 'type': 'evidence_for', 'target': 'Relationship_Operates_58'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043815' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:487' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:996' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3082', 'source': 'Event_Communication_548', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_405'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7fa60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729063' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:487' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:821' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3080', 'source': 'Event_Communication_548', 'type': 'evidence_for', 'target': 'Event_VesselMovement_549'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358568' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:488' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:821' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3087', 'source': 'Event_Communication_551', 'type': 'evidence_for', 'target': 'Event_VesselMovement_549'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043816' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:488' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:903' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3088', 'source': 'Event_Communication_551', 'type': 'evidence_for', 'target': 'Event_Collaborate_550'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fb20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729064' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:488' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1133' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3089', 'source': 'Event_Communication_551', 'type': 'evidence_for', 'target': 'Relationship_Operates_58'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358569' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:489' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:988' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3095', 'source': 'Event_Communication_553', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_332'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6f820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043817' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:489' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1090' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3096', 'source': 'Event_Communication_553', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_298'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5ad60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729065' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:489' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:815' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3094', 'source': 'Event_Communication_553', 'type': 'evidence_for', 'target': 'Event_VesselMovement_495'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2e20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358570' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:490' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:904' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3100', 'source': 'Event_Communication_555', 'type': 'evidence_for', 'target': 'Event_Collaborate_554'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4ec10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594054' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:490' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1094' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3101', 'source': 'Event_Communication_555', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_334'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358571' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:491' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1089' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3104', 'source': 'Event_Communication_556', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_297'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e657f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358572' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:492' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:905' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3108', 'source': 'Event_Communication_558', 'type': 'evidence_for', 'target': 'Event_Collaborate_557'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043820' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:492' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1095' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3109', 'source': 'Event_Communication_558', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_336'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb5ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358573' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:493' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1092' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3112', 'source': 'Event_Communication_559', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_305'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358574' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:494' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:989' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3115', 'source': 'Event_Communication_560', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_338'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb5460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358575' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:495' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:817' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3118', 'source': 'Event_Communication_562', 'type': 'evidence_for', 'target': 'Event_VesselMovement_509'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec4130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358576' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:496' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:822' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3123', 'source': 'Event_Communication_565', 'type': 'evidence_for', 'target': 'Event_VesselMovement_563'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043824' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:496' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2350' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3125', 'source': 'Event_Communication_565', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_293'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729072' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:496' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:23' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3124', 'source': 'Event_Communication_565', 'type': 'evidence_for', 'target': 'Event_Monitoring_266'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec47f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358578' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:498' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:777' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3130', 'source': 'Event_Communication_568', 'type': 'evidence_for', 'target': 'Event_Assessment_567'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043826' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:498' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2353' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3132', 'source': 'Event_Communication_568', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_341'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53df0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729074' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:498' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1144' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3131', 'source': 'Event_Communication_568', 'type': 'evidence_for', 'target': 'Relationship_Operates_176'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e8b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358579' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:499' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:823' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3139', 'source': 'Event_Communication_571', 'type': 'evidence_for', 'target': 'Event_VesselMovement_569'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594056' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:499' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1096' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3142', 'source': 'Event_Communication_571', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_343'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043827' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:499' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1125' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3141', 'source': 'Event_Communication_571', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_609'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecd9a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729075' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:499' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:782' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3140', 'source': 'Event_Communication_571', 'type': 'evidence_for', 'target': 'Event_Assessment_628'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351bd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358580' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:500' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1031' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3146', 'source': 'Event_Communication_572', 'type': 'evidence_for', 'target': 'Relationship_Reports_344'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecda00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043828' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:500' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1125' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3147', 'source': 'Event_Communication_572', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_609'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358581' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:501' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2350' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3153', 'source': 'Event_Communication_574', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_293'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecd9a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043829' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:501' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:977' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3154', 'source': 'Event_Communication_574', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034710a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729077' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:501' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:793' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3152', 'source': 'Event_Communication_574', 'type': 'evidence_for', 'target': 'Event_Assessment_973'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358583' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:503' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1088' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3158', 'source': 'Event_Communication_576', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_292'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec41f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358584' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:504' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:824' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3161', 'source': 'Event_Communication_578', 'type': 'evidence_for', 'target': 'Event_VesselMovement_577'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358586' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:506' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:825' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3166', 'source': 'Event_Communication_581', 'type': 'evidence_for', 'target': 'Event_VesselMovement_580'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e968e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043834' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:506' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:990' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3167', 'source': 'Event_Communication_581', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_349'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb5790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358587' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:507' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:945' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3170', 'source': 'Event_Communication_582', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_551'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358588' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:508' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:778' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3173', 'source': 'Event_Communication_584', 'type': 'evidence_for', 'target': 'Event_Assessment_583'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594113' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:509' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1153' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3176', 'source': 'Event_Communication_585', 'type': 'evidence_for', 'target': 'Relationship_Operates_351'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3ac10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358590' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:510' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1154' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3184', 'source': 'Event_Communication_588', 'type': 'evidence_for', 'target': 'Relationship_Operates_352'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bd60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043838' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:510' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:821' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3182', 'source': 'Event_Communication_588', 'type': 'evidence_for', 'target': 'Event_VesselMovement_549'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecd460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729086' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:510' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:977' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3185', 'source': 'Event_Communication_588', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414334' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:510' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:771' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3183', 'source': 'Event_Communication_588', 'type': 'evidence_for', 'target': 'Event_Assessment_337'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1161933101908099582' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:510' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:950' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': 'Event_Communication_588_evidence_for_Relationship_Colleagues_619', 'source': 'Event_Communication_588', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_619'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358591' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:511' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:34' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3189', 'source': 'Event_Communication_590', 'type': 'evidence_for', 'target': 'Event_Monitoring_595'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687593992' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:513' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1032' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3195', 'source': 'Event_Communication_593', 'type': 'evidence_for', 'target': 'Relationship_Reports_355'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7970>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043841' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:513' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:17' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3194', 'source': 'Event_Communication_593', 'type': 'evidence_for', 'target': 'Event_Monitoring_192'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358594' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:514' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:946' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': 'Event_Communication_594_evidence_for_Relationship_Colleagues_589', 'source': 'Event_Communication_594', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_589'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e9a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358595' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:515' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:34' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3202', 'source': 'Event_Communication_596', 'type': 'evidence_for', 'target': 'Event_Monitoring_595'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043843' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:515' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1022' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3203', 'source': 'Event_Communication_596', 'type': 'evidence_for', 'target': 'Relationship_Reports_41'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5bb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358597' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:517' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1164' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3207', 'source': 'Event_Communication_598', 'type': 'evidence_for', 'target': 'Relationship_Operates_514'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e659d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358598' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:518' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:946' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3210', 'source': 'Event_Communication_599', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_589'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bd60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358599' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:519' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:779' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3214', 'source': 'Event_Communication_601', 'type': 'evidence_for', 'target': 'Event_Assessment_600'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687595314' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:519' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2354' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3215', 'source': 'Event_Communication_601', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_360'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e485b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358600' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:520' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:782' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3218', 'source': 'Event_Communication_603', 'type': 'evidence_for', 'target': 'Event_Assessment_628'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a9d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358601' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:521' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3222', 'source': 'Event_Communication_604', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaaca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043849' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:521' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1006' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3223', 'source': 'Event_Communication_604', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_497'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ce92b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358602' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:522' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1094' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3226', 'source': 'Event_Communication_605', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_334'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaac70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687593996' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:523' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1036' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3229', 'source': 'Event_Communication_606', 'type': 'evidence_for', 'target': 'Relationship_Reports_513'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf9d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358604' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:524' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1092' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3232', 'source': 'Event_Communication_607', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_305'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e9a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358605' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:525' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:35' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3236', 'source': 'Event_Communication_610', 'type': 'evidence_for', 'target': 'Event_Monitoring_608'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e86220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043853' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:525' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:780' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3237', 'source': 'Event_Communication_610', 'type': 'evidence_for', 'target': 'Event_Assessment_609'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729101' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:525' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3239', 'source': 'Event_Communication_610', 'type': 'evidence_for', 'target': 'Relationship_Operates_367'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e485b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414349' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:525' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1132' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3238', 'source': 'Event_Communication_610', 'type': 'evidence_for', 'target': 'Relationship_Operates_36'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2e50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358606' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:526' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2355' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3244', 'source': 'Event_Communication_612', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_368'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf9a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043854' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:526' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:767' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3243', 'source': 'Event_Communication_612', 'type': 'evidence_for', 'target': 'Event_Assessment_174'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecbd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358607' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:527' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:991' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3249', 'source': 'Event_Communication_613', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_370'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043855' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:527' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1054' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3248', 'source': 'Event_Communication_613', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_583'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358608' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:528' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3254', 'source': 'Event_Communication_614', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043856' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:528' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1006' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3253', 'source': 'Event_Communication_614', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_497'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fb50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358609' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:529' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1006' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3259', 'source': 'Event_Communication_616', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_497'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043857' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:529' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:782' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3258', 'source': 'Event_Communication_616', 'type': 'evidence_for', 'target': 'Event_Assessment_628'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358611' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:531' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1032' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3265', 'source': 'Event_Communication_619', 'type': 'evidence_for', 'target': 'Relationship_Reports_355'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e732b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043859' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:531' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:144' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3264', 'source': 'Event_Communication_619', 'type': 'evidence_for', 'target': 'Event_Monitoring_978'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358612' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:532' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1038' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3274', 'source': 'Event_Communication_621', 'type': 'evidence_for', 'target': 'Relationship_Reports_529'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb27f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043860' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:532' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1170' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3272', 'source': 'Event_Communication_621', 'type': 'evidence_for', 'target': 'Relationship_Operates_566'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaa340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729108' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:532' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1031' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3273', 'source': 'Event_Communication_621', 'type': 'evidence_for', 'target': 'Relationship_Reports_344'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e732b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414356' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:532' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:782' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3271', 'source': 'Event_Communication_621', 'type': 'evidence_for', 'target': 'Event_Assessment_628'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de76d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358613' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:533' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1097' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3279', 'source': 'Event_Communication_623', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_378'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd87f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043861' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:533' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:782' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3278', 'source': 'Event_Communication_623', 'type': 'evidence_for', 'target': 'Event_Assessment_628'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358614' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:534' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:826' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3282', 'source': 'Event_Communication_627', 'type': 'evidence_for', 'target': 'Event_VesselMovement_624'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043862' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:534' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:781' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3283', 'source': 'Event_Communication_627', 'type': 'evidence_for', 'target': 'Event_Assessment_625'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729110' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:534' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:906' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3284', 'source': 'Event_Communication_627', 'type': 'evidence_for', 'target': 'Event_Collaborate_626'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594060' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:534' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1100' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3285', 'source': 'Event_Communication_627', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_401'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73d30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358615' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:535' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:782' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3290', 'source': 'Event_Communication_630', 'type': 'evidence_for', 'target': 'Event_Assessment_628'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043863' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:535' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:827' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3291', 'source': 'Event_Communication_630', 'type': 'evidence_for', 'target': 'Event_VesselMovement_629'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729111' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:535' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1098' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3292', 'source': 'Event_Communication_630', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_380'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358616' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:536' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:36' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3295', 'source': 'Event_Communication_632', 'type': 'evidence_for', 'target': 'Event_Monitoring_631'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96e50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358617' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:537' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1036' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3298', 'source': 'Event_Communication_633', 'type': 'evidence_for', 'target': 'Relationship_Reports_513'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9bd60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358618' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:538' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:828' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3301', 'source': 'Event_Communication_635', 'type': 'evidence_for', 'target': 'Event_VesselMovement_634'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358619' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:539' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:992' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3304', 'source': 'Event_Communication_636', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_382'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358620' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:540' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1148' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3307', 'source': 'Event_Communication_637', 'type': 'evidence_for', 'target': 'Relationship_Operates_255'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358621' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:541' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1148' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3310', 'source': 'Event_Communication_638', 'type': 'evidence_for', 'target': 'Relationship_Operates_255'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb22b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358622' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:542' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1099' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3318', 'source': 'Event_Communication_639', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_387'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043870' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:542' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1133' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3316', 'source': 'Event_Communication_639', 'type': 'evidence_for', 'target': 'Relationship_Operates_58'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e86220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729118' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:542' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1160' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3317', 'source': 'Event_Communication_639', 'type': 'evidence_for', 'target': 'Relationship_Operates_474'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414366' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:542' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1183' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3319', 'source': 'Event_Communication_639', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_145'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e335e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358623' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:543' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:997' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3322', 'source': 'Event_Communication_640', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_415'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358624' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:544' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1050' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3325', 'source': 'Event_Communication_641', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_390'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a4f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358626' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:546' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:809' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3329', 'source': 'Event_Communication_644', 'type': 'evidence_for', 'target': 'Event_VesselMovement_393'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb58e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358627' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:547' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:993' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3333', 'source': 'Event_Communication_645', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_392'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e964c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043875' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:547' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:994' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3334', 'source': 'Event_Communication_645', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_393'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecdc10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358628' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:548' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:32' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3337', 'source': 'Event_Communication_647', 'type': 'evidence_for', 'target': 'Event_Monitoring_530'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358629' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:549' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:46' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3341', 'source': 'Event_Communication_649', 'type': 'evidence_for', 'target': 'Event_Monitoring_722'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c6d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043877' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:549' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:946' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': 'Event_Communication_649_evidence_for_Relationship_Colleagues_589', 'source': 'Event_Communication_649', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_589'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd62b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358630' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:550' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:783' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3346', 'source': 'Event_Communication_651', 'type': 'evidence_for', 'target': 'Event_Assessment_650'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043878' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:550' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:946' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3347', 'source': 'Event_Communication_651', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_589'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb5a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358632' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:552' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:995' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3353', 'source': 'Event_Communication_654', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_397'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e991f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043880' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:552' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:876' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3352', 'source': 'Event_Communication_654', 'type': 'evidence_for', 'target': 'Event_TourActivity_807'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7fc40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358634' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:554' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:977' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3357', 'source': 'Event_Communication_656', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec48e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358635' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:555' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:977' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3360', 'source': 'Event_Communication_657', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358636' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:556' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1098' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3367', 'source': 'Event_Communication_660', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_380'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaaeb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043884' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:556' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:824' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3366', 'source': 'Event_Communication_660', 'type': 'evidence_for', 'target': 'Event_VesselMovement_577'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec4730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729132' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:556' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:827' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3365', 'source': 'Event_Communication_660', 'type': 'evidence_for', 'target': 'Event_VesselMovement_629'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecb460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358637' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:557' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:37' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3371', 'source': 'Event_Communication_662', 'type': 'evidence_for', 'target': 'Event_Monitoring_661'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecb160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043885' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:557' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1100' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3372', 'source': 'Event_Communication_662', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_401'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecdf70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358638' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:558' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1092' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3375', 'source': 'Event_Communication_663', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_305'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358639' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:559' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1089' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3378', 'source': 'Event_Communication_664', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_297'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e966a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358640' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:560' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:996' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3383', 'source': 'Event_Communication_665', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_405'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e338b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043888' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:560' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1099' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3382', 'source': 'Event_Communication_665', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_387'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034710a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358641' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:561' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:853' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3388', 'source': 'Event_Communication_668', 'type': 'evidence_for', 'target': 'Event_Enforcement_666'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb55b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043889' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:561' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1001' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3390', 'source': 'Event_Communication_668', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_444'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e966a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729137' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:561' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:156' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3389', 'source': 'Event_Communication_668', 'type': 'evidence_for', 'target': 'Event_Monitoring_995'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358642' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:562' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:829' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3397', 'source': 'Event_Communication_672', 'type': 'evidence_for', 'target': 'Event_VesselMovement_670'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecd580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043890' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:562' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1067' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3399', 'source': 'Event_Communication_672', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_53'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e338b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729138' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:562' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:767' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3398', 'source': 'Event_Communication_672', 'type': 'evidence_for', 'target': 'Event_Assessment_174'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414386' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:562' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:76' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3396', 'source': 'Event_Communication_672', 'type': 'evidence_for', 'target': 'Event_Monitoring_946'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358643' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:563' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:23' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3402', 'source': 'Event_Communication_674', 'type': 'evidence_for', 'target': 'Event_Monitoring_266'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb5430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687593993' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:564' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1033' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3405', 'source': 'Event_Communication_675', 'type': 'evidence_for', 'target': 'Relationship_Reports_408'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecd790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687595316' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:565' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2356' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3412', 'source': 'Event_Communication_677', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_410'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fb80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043893' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:565' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3411', 'source': 'Event_Communication_677', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729141' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:565' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:23' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3410', 'source': 'Event_Communication_677', 'type': 'evidence_for', 'target': 'Event_Monitoring_266'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec4e80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358646' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:566' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:38' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3415', 'source': 'Event_Communication_679', 'type': 'evidence_for', 'target': 'Event_Monitoring_678'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecd790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043894' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:566' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1101' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3416', 'source': 'Event_Communication_679', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_411'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e866a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358647' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:567' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1118' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3421', 'source': 'Event_Communication_681', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_548'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043895' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:567' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:76' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3420', 'source': 'Event_Communication_681', 'type': 'evidence_for', 'target': 'Event_Monitoring_946'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecd580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594062' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:568' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1102' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3424', 'source': 'Event_Communication_683', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_413'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358649' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:569' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1094' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3427', 'source': 'Event_Communication_684', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_334'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358651' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:571' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:997' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3432', 'source': 'Event_Communication_686', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_415'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99e50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043899' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:571' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3433', 'source': 'Event_Communication_686', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecbc10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358652' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:572' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:977' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3436', 'source': 'Event_Communication_687', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3ac10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358653' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:573' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:39' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3440', 'source': 'Event_Communication_689', 'type': 'evidence_for', 'target': 'Event_Monitoring_688'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043901' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:573' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1103' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3441', 'source': 'Event_Communication_689', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_418'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358654' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:574' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:40' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3445', 'source': 'Event_Communication_692', 'type': 'evidence_for', 'target': 'Event_Monitoring_690'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4eb80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043902' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:574' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:784' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3446', 'source': 'Event_Communication_692', 'type': 'evidence_for', 'target': 'Event_Assessment_691'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729150' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:574' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1170' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3447', 'source': 'Event_Communication_692', 'type': 'evidence_for', 'target': 'Relationship_Operates_566'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a9d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414398' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:574' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1125' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3448', 'source': 'Event_Communication_692', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_609'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b1c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358655' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:575' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:854' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3452', 'source': 'Event_Communication_694', 'type': 'evidence_for', 'target': 'Event_Enforcement_693'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec4460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043903' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:575' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:998' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3453', 'source': 'Event_Communication_694', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_421'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e866a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358656' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:576' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3458', 'source': 'Event_Communication_696', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99d30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043904' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:576' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:857' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3457', 'source': 'Event_Communication_696', 'type': 'evidence_for', 'target': 'Event_Enforcement_784'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e6a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358657' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:577' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:907' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3465', 'source': 'Event_Communication_700', 'type': 'evidence_for', 'target': 'Event_Collaborate_697'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043905' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:577' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1104' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3468', 'source': 'Event_Communication_700', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_423'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729153' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:577' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:909' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3466', 'source': 'Event_Communication_700', 'type': 'evidence_for', 'target': 'Event_Collaborate_723'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414401' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:577' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3469', 'source': 'Event_Communication_700', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e734c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1161933101908099649' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:577' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:855' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3467', 'source': 'Event_Communication_700', 'type': 'evidence_for', 'target': 'Event_Enforcement_745'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358658' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:578' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:785' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3472', 'source': 'Event_Communication_702', 'type': 'evidence_for', 'target': 'Event_Assessment_701'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99d90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043906' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:578' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:999' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3473', 'source': 'Event_Communication_702', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_425'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9bd60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729154' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:578' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2357' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3474', 'source': 'Event_Communication_702', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_426'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2d60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358659' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:579' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:786' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3479', 'source': 'Event_Communication_705', 'type': 'evidence_for', 'target': 'Event_Assessment_703'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec46d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043907' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:579' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:42' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3480', 'source': 'Event_Communication_705', 'type': 'evidence_for', 'target': 'Event_Monitoring_704'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729155' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:579' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:946' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3481', 'source': 'Event_Communication_705', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_589'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126edcf40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594065' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:580' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1105' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3491', 'source': 'Event_Communication_708', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_428'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043908' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:580' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:940' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3493', 'source': 'Event_Communication_708', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_430'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729156' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:580' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:941' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3494', 'source': 'Event_Communication_708', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_431'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414404' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:580' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:779' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3490', 'source': 'Event_Communication_708', 'type': 'evidence_for', 'target': 'Event_Assessment_600'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e86a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1161933101908099652' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:580' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:46' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3489', 'source': 'Event_Communication_708', 'type': 'evidence_for', 'target': 'Event_Monitoring_722'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1164184901721784900' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:580' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:937' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3492', 'source': 'Event_Communication_708', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_321'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2a90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358661' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:581' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:43' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3498', 'source': 'Event_Communication_710', 'type': 'evidence_for', 'target': 'Event_Monitoring_709'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaad60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043909' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:581' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1118' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3499', 'source': 'Event_Communication_710', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_548'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358662' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:582' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:56' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3502', 'source': 'Event_Communication_712', 'type': 'evidence_for', 'target': 'Event_Monitoring_878'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358663' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:583' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:17' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3505', 'source': 'Event_Communication_714', 'type': 'evidence_for', 'target': 'Event_Monitoring_192'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358664' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:584' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:946' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3508', 'source': 'Event_Communication_715', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_589'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358665' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:585' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:44' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3510', 'source': 'Event_Communication_717', 'type': 'evidence_for', 'target': 'Event_Monitoring_716'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358666' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:586' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:908' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3517', 'source': 'Event_Communication_720', 'type': 'evidence_for', 'target': 'Event_Collaborate_719'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb01f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043914' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:586' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:946' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3518', 'source': 'Event_Communication_720', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_589'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2b80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729162' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:586' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:929' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3519', 'source': 'Event_Communication_720', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_84'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414410' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:586' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:46' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3516', 'source': 'Event_Communication_720', 'type': 'evidence_for', 'target': 'Event_Monitoring_722'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e338b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358668' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:588' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:46' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3525', 'source': 'Event_Communication_724', 'type': 'evidence_for', 'target': 'Event_Monitoring_722'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e997f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043916' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:588' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:909' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3526', 'source': 'Event_Communication_724', 'type': 'evidence_for', 'target': 'Event_Collaborate_723'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729164' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:588' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2358' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3527', 'source': 'Event_Communication_724', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_436'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e659a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358669' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:589' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1106' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3533', 'source': 'Event_Communication_726', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_437'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4ed00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043917' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:589' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2364' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3534', 'source': 'Event_Communication_726', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_600'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fb80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729165' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:589' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:23' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3532', 'source': 'Event_Communication_726', 'type': 'evidence_for', 'target': 'Event_Monitoring_266'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaac10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358672' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:592' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:787' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3538', 'source': 'Event_Communication_730', 'type': 'evidence_for', 'target': 'Event_Assessment_729'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e998b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043920' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:592' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1156' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3539', 'source': 'Event_Communication_730', 'type': 'evidence_for', 'target': 'Relationship_Operates_439'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08b50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358673' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:593' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1000' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3544', 'source': 'Event_Communication_731', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_441'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043921' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:593' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3543', 'source': 'Event_Communication_731', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358674' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:594' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3550', 'source': 'Event_Communication_733', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043922' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:594' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1001' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3551', 'source': 'Event_Communication_733', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_444'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f040>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729170' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:594' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:156' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3549', 'source': 'Event_Communication_733', 'type': 'evidence_for', 'target': 'Event_Monitoring_995'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf0a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358675' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:595' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1001' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3558', 'source': 'Event_Communication_735', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_444'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e732b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043923' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:595' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1107' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3559', 'source': 'Event_Communication_735', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_445'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bd60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729171' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:595' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3560', 'source': 'Event_Communication_735', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecdac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414419' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:595' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:794' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3557', 'source': 'Event_Communication_735', 'type': 'evidence_for', 'target': 'Event_Assessment_996'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687593994' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:596' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1034' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3565', 'source': 'Event_Communication_737', 'type': 'evidence_for', 'target': 'Relationship_Reports_447'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043924' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:596' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:794' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3564', 'source': 'Event_Communication_737', 'type': 'evidence_for', 'target': 'Event_Assessment_996'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358677' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:597' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1108' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3570', 'source': 'Event_Communication_739', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_448'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb5370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043925' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:597' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:156' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3569', 'source': 'Event_Communication_739', 'type': 'evidence_for', 'target': 'Event_Monitoring_995'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6f7c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358678' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:598' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1034' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3577', 'source': 'Event_Communication_741', 'type': 'evidence_for', 'target': 'Relationship_Reports_447'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9bf10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043926' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:598' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1097' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3576', 'source': 'Event_Communication_741', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_378'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08eb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729174' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:598' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:156' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3575', 'source': 'Event_Communication_741', 'type': 'evidence_for', 'target': 'Event_Monitoring_995'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc83d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358679' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:599' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1034' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3580', 'source': 'Event_Communication_742', 'type': 'evidence_for', 'target': 'Relationship_Reports_447'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecd940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358680' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:600' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:76' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3583', 'source': 'Event_Communication_744', 'type': 'evidence_for', 'target': 'Event_Monitoring_946'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb21f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358681' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:601' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:855' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3587', 'source': 'Event_Communication_746', 'type': 'evidence_for', 'target': 'Event_Enforcement_745'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043929' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:601' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1060' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3588', 'source': 'Event_Communication_746', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_27'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec4640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358682' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:602' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1052' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3597', 'source': 'Event_Communication_749', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_454'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043930' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:602' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1001' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3596', 'source': 'Event_Communication_749', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_444'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c6d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729178' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:602' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:156' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3594', 'source': 'Event_Communication_749', 'type': 'evidence_for', 'target': 'Event_Monitoring_995'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414426' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:602' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:47' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3595', 'source': 'Event_Communication_749', 'type': 'evidence_for', 'target': 'Event_Monitoring_752'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec46d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358683' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:603' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1002' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3602', 'source': 'Event_Communication_751', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_455'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec45b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043931' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:603' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:47' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3601', 'source': 'Event_Communication_751', 'type': 'evidence_for', 'target': 'Event_Monitoring_752'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358684' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:604' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:47' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3607', 'source': 'Event_Communication_753', 'type': 'evidence_for', 'target': 'Event_Monitoring_752'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bb50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687595319' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:604' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2359' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3609', 'source': 'Event_Communication_753', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_457'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f040>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043932' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:604' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:942' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3608', 'source': 'Event_Communication_753', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_494'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358685' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:605' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1090' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3612', 'source': 'Event_Communication_754', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_298'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecdeb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358686' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:606' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3616', 'source': 'Event_Communication_755', 'type': 'evidence_for', 'target': 'Relationship_Operates_459'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc83d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043934' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:606' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1095' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3617', 'source': 'Event_Communication_755', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_336'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a1f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594118' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:607' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1158' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3622', 'source': 'Event_Communication_756', 'type': 'evidence_for', 'target': 'Relationship_Operates_461'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4ec10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043935' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:607' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1090' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3623', 'source': 'Event_Communication_756', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_298'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb51c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358688' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:608' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3626', 'source': 'Event_Communication_757', 'type': 'evidence_for', 'target': 'Relationship_Operates_463'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e965b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358689' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:609' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1109' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3630', 'source': 'Event_Communication_758', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_471'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034710a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043937' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:609' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1110' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3631', 'source': 'Event_Communication_758', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_473'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358690' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:610' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1164' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3637', 'source': 'Event_Communication_759', 'type': 'evidence_for', 'target': 'Relationship_Operates_514'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb5730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043938' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:610' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1160' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3638', 'source': 'Event_Communication_759', 'type': 'evidence_for', 'target': 'Relationship_Operates_474'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec4a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729186' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:610' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1092' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3636', 'source': 'Event_Communication_759', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_305'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358691' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:611' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:910' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3643', 'source': 'Event_Communication_761', 'type': 'evidence_for', 'target': 'Event_Collaborate_760'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fdc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687595320' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:611' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2360' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3645', 'source': 'Event_Communication_761', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_470'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb5ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594076' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:611' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1116' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3644', 'source': 'Event_Communication_761', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_516'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a1f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358692' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:612' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1109' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3650', 'source': 'Event_Communication_762', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_471'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043940' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:612' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1110' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3652', 'source': 'Event_Communication_762', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_473'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e656a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729188' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:612' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1113' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3651', 'source': 'Event_Communication_762', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_499'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb5460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358693' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:613' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1160' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3656', 'source': 'Event_Communication_763', 'type': 'evidence_for', 'target': 'Relationship_Operates_474'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a1f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043941' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:613' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1164' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3657', 'source': 'Event_Communication_763', 'type': 'evidence_for', 'target': 'Relationship_Operates_514'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358694' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:614' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1161' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3660', 'source': 'Event_Communication_764', 'type': 'evidence_for', 'target': 'Relationship_Operates_476'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358695' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:615' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:788' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3665', 'source': 'Event_Communication_767', 'type': 'evidence_for', 'target': 'Event_Assessment_765'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb5610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043943' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:615' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:49' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3666', 'source': 'Event_Communication_767', 'type': 'evidence_for', 'target': 'Event_Monitoring_766'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3aac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729191' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:615' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1003' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3667', 'source': 'Event_Communication_767', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_477'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd87f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358696' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:616' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:934' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3670', 'source': 'Event_Communication_768', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_290'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358697' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:617' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:856' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3674', 'source': 'Event_Communication_770', 'type': 'evidence_for', 'target': 'Event_Enforcement_769'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043945' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:617' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1004' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3675', 'source': 'Event_Communication_770', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_479'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec4550>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358698' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:618' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:934' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3678', 'source': 'Event_Communication_771', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_290'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c6d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358700' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:620' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:934' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3682', 'source': 'Event_Communication_773', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_290'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358701' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:621' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2361' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3687', 'source': 'Event_Communication_774', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_483'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e965b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043949' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:621' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1055' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3686', 'source': 'Event_Communication_774', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_586'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358702' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:622' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2362' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3691', 'source': 'Event_Communication_775', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_485'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043950' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:622' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:934' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3690', 'source': 'Event_Communication_775', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_290'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358704' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:624' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:50' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3695', 'source': 'Event_Communication_778', 'type': 'evidence_for', 'target': 'Event_Monitoring_777'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043952' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:624' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1144' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3696', 'source': 'Event_Communication_778', 'type': 'evidence_for', 'target': 'Relationship_Operates_176'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358705' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:625' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3703', 'source': 'Event_Communication_781', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043953' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:625' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:17' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3701', 'source': 'Event_Communication_781', 'type': 'evidence_for', 'target': 'Event_Monitoring_192'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf4f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729201' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:625' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:767' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3702', 'source': 'Event_Communication_781', 'type': 'evidence_for', 'target': 'Event_Assessment_174'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e964f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358706' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:626' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3708', 'source': 'Event_Communication_783', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5d30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043954' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:626' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:855' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3707', 'source': 'Event_Communication_783', 'type': 'evidence_for', 'target': 'Event_Enforcement_745'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9be80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358707' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:627' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:857' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3712', 'source': 'Event_Communication_785', 'type': 'evidence_for', 'target': 'Event_Enforcement_784'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043955' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:627' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1005' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3713', 'source': 'Event_Communication_785', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_489'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358708' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:628' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:789' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3716', 'source': 'Event_Communication_787', 'type': 'evidence_for', 'target': 'Event_Assessment_786'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73d60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358709' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:629' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:46' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3719', 'source': 'Event_Communication_789', 'type': 'evidence_for', 'target': 'Event_Monitoring_722'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126edc130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358710' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:630' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:790' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3726', 'source': 'Event_Communication_792', 'type': 'evidence_for', 'target': 'Event_Assessment_791'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddfc40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043958' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:630' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1032' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3728', 'source': 'Event_Communication_792', 'type': 'evidence_for', 'target': 'Relationship_Reports_355'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126edcd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729206' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:630' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:34' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3725', 'source': 'Event_Communication_792', 'type': 'evidence_for', 'target': 'Event_Monitoring_595'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc56d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414454' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:630' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:974' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3727', 'source': 'Event_Communication_792', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_232'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126edc130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358711' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:631' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1111' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3731', 'source': 'Event_Communication_793', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_492'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaae80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358713' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:633' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1112' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3736', 'source': 'Event_Communication_795', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_493'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043961' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:633' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:942' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3737', 'source': 'Event_Communication_795', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_494'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9b160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358714' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:634' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1035' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3742', 'source': 'Event_Communication_796', 'type': 'evidence_for', 'target': 'Relationship_Reports_496'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043962' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:634' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:948' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': 'Event_Communication_796_evidence_for_Relationship_Colleagues_601', 'source': 'Event_Communication_796', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_601'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358715' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:635' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:51' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3746', 'source': 'Event_Communication_799', 'type': 'evidence_for', 'target': 'Event_Monitoring_797'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ee38e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043963' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:635' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:830' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3747', 'source': 'Event_Communication_799', 'type': 'evidence_for', 'target': 'Event_VesselMovement_798'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73d60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358716' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:636' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1006' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3752', 'source': 'Event_Communication_801', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_497'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043964' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:636' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:76' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3751', 'source': 'Event_Communication_801', 'type': 'evidence_for', 'target': 'Event_Monitoring_946'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e866a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358717' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:637' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1113' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3757', 'source': 'Event_Communication_802', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_499'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2b50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043965' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:637' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1133' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3756', 'source': 'Event_Communication_802', 'type': 'evidence_for', 'target': 'Relationship_Operates_58'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358718' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:638' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:52' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3762', 'source': 'Event_Communication_804', 'type': 'evidence_for', 'target': 'Event_Monitoring_803'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043966' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:638' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:977' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3763', 'source': 'Event_Communication_804', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729214' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:638' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:950' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3764', 'source': 'Event_Communication_804', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_619'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99df0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358719' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:639' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:52' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3766', 'source': 'Event_Communication_805', 'type': 'evidence_for', 'target': 'Event_Monitoring_803'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043967' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:639' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:977' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3767', 'source': 'Event_Communication_805', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729215' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:639' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:950' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3768', 'source': 'Event_Communication_805', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_619'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaac10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358720' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:640' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:831' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3773', 'source': 'Event_Communication_808', 'type': 'evidence_for', 'target': 'Event_VesselMovement_806'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bc8c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043968' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:640' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:876' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3774', 'source': 'Event_Communication_808', 'type': 'evidence_for', 'target': 'Event_TourActivity_807'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0efd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729216' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:640' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1007' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3775', 'source': 'Event_Communication_808', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_502'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594074' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:641' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1114' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3779', 'source': 'Event_Communication_809', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_503'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fdf0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594122' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:642' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1162' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3784', 'source': 'Event_Communication_810', 'type': 'evidence_for', 'target': 'Relationship_Operates_505'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ee3bb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043970' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:642' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1161' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3783', 'source': 'Event_Communication_810', 'type': 'evidence_for', 'target': 'Relationship_Operates_476'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594123' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:643' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1163' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3787', 'source': 'Event_Communication_811', 'type': 'evidence_for', 'target': 'Relationship_Operates_506'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358724' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:644' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1113' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3792', 'source': 'Event_Communication_812', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_499'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b1c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043972' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:644' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1089' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3791', 'source': 'Event_Communication_812', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_297'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ee3c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358725' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:645' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:877' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3797', 'source': 'Event_Communication_815', 'type': 'evidence_for', 'target': 'Event_TourActivity_814'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc56d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043973' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:645' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:796' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3796', 'source': 'Event_Communication_815', 'type': 'evidence_for', 'target': 'Event_VesselMovement_122'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd60d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358726' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:646' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:878' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3801', 'source': 'Event_Communication_817', 'type': 'evidence_for', 'target': 'Event_TourActivity_816'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043974' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:646' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1115' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3802', 'source': 'Event_Communication_817', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_509'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358727' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:647' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:911' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3808', 'source': 'Event_Communication_819', 'type': 'evidence_for', 'target': 'Event_Collaborate_818'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd81f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043975' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:647' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1008' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3810', 'source': 'Event_Communication_819', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_511'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b1c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729223' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:647' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1009' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3811', 'source': 'Event_Communication_819', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_512'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414471' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:647' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1133' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3809', 'source': 'Event_Communication_819', 'type': 'evidence_for', 'target': 'Relationship_Operates_58'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c8b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358728' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:648' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1036' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3814', 'source': 'Event_Communication_820', 'type': 'evidence_for', 'target': 'Relationship_Reports_513'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4eee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358729' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:649' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1164' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3817', 'source': 'Event_Communication_821', 'type': 'evidence_for', 'target': 'Relationship_Operates_514'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec4190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358730' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:650' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1092' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3820', 'source': 'Event_Communication_822', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_305'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4eb80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358731' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:651' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1116' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3824', 'source': 'Event_Communication_823', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_516'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043979' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:651' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1164' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3825', 'source': 'Event_Communication_823', 'type': 'evidence_for', 'target': 'Relationship_Operates_514'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4eee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594077' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:652' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1117' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3828', 'source': 'Event_Communication_824', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_518'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecd6a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594125' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:653' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1165' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3832', 'source': 'Event_Communication_825', 'type': 'evidence_for', 'target': 'Relationship_Operates_519'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecd2b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358735' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:655' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1166' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3840', 'source': 'Event_Communication_828', 'type': 'evidence_for', 'target': 'Relationship_Operates_521'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043983' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:655' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1006' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3839', 'source': 'Event_Communication_828', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_497'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb5730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729231' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:655' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:76' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3838', 'source': 'Event_Communication_828', 'type': 'evidence_for', 'target': 'Event_Monitoring_946'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecd6a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358736' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:656' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:53' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3844', 'source': 'Event_Communication_831', 'type': 'evidence_for', 'target': 'Event_Monitoring_829'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecb550>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043984' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:656' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1132' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3846', 'source': 'Event_Communication_831', 'type': 'evidence_for', 'target': 'Relationship_Operates_36'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729232' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:656' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:767' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3845', 'source': 'Event_Communication_831', 'type': 'evidence_for', 'target': 'Event_Assessment_174'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358737' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:657' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2355' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3851', 'source': 'Event_Communication_833', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_368'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb5d90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043985' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:657' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:17' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3850', 'source': 'Event_Communication_833', 'type': 'evidence_for', 'target': 'Event_Monitoring_192'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb01f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358738' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:658' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1037' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3859', 'source': 'Event_Communication_834', 'type': 'evidence_for', 'target': 'Relationship_Reports_526'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043986' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:658' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3860', 'source': 'Event_Communication_834', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_446'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb58e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729234' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:658' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1170' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3857', 'source': 'Event_Communication_834', 'type': 'evidence_for', 'target': 'Relationship_Operates_566'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6f490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414482' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:658' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1006' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3858', 'source': 'Event_Communication_834', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_497'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358739' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:659' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:54' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3865', 'source': 'Event_Communication_836', 'type': 'evidence_for', 'target': 'Event_Monitoring_835'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96cd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043987' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:659' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1038' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3867', 'source': 'Event_Communication_836', 'type': 'evidence_for', 'target': 'Relationship_Reports_529'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729235' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:659' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1132' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3866', 'source': 'Event_Communication_836', 'type': 'evidence_for', 'target': 'Relationship_Operates_36'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fc70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358740' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:660' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:791' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3871', 'source': 'Event_Communication_838', 'type': 'evidence_for', 'target': 'Event_Assessment_837'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043988' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:660' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1068' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3872', 'source': 'Event_Communication_838', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_54'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e965b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358741' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:661' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:859' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3876', 'source': 'Event_Communication_840', 'type': 'evidence_for', 'target': 'Event_Enforcement_839'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec4670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043989' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:661' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:973' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3877', 'source': 'Event_Communication_840', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_214'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fc70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358742' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:662' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1164' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3881', 'source': 'Event_Communication_841', 'type': 'evidence_for', 'target': 'Relationship_Operates_514'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fdf0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043990' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:662' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:996' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3882', 'source': 'Event_Communication_841', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_405'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358743' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:663' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:943' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3889', 'source': 'Event_Communication_842', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_535'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043991' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:663' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:944' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3890', 'source': 'Event_Communication_842', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_536'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73550>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687593999' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:663' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1039' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3891', 'source': 'Event_Communication_842', 'type': 'evidence_for', 'target': 'Relationship_Reports_537'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729239' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:663' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:949' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3888', 'source': 'Event_Communication_842', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_617'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e263a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358744' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:664' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:832' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3897', 'source': 'Event_Communication_844', 'type': 'evidence_for', 'target': 'Event_VesselMovement_843'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1be80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594127' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:664' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1167' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3898', 'source': 'Event_Communication_844', 'type': 'evidence_for', 'target': 'Relationship_Operates_538'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043992' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:664' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:945' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3899', 'source': 'Event_Communication_844', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_551'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaaa90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358745' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:665' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:832' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3901', 'source': 'Event_Communication_845', 'type': 'evidence_for', 'target': 'Event_VesselMovement_843'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043993' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:665' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1167' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3902', 'source': 'Event_Communication_845', 'type': 'evidence_for', 'target': 'Relationship_Operates_538'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729241' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:665' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:945' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3903', 'source': 'Event_Communication_845', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_551'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358746' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:666' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:945' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3907', 'source': 'Event_Communication_846', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_551'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043994' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:666' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:973' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3908', 'source': 'Event_Communication_846', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_214'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc56d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358748' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:668' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:23' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3912', 'source': 'Event_Communication_849', 'type': 'evidence_for', 'target': 'Event_Monitoring_266'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e86820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358749' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:669' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1089' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3915', 'source': 'Event_Communication_850', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_297'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594128' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:670' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1168' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3919', 'source': 'Event_Communication_851', 'type': 'evidence_for', 'target': 'Relationship_Operates_543'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53af0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467043998' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:670' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:945' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3920', 'source': 'Event_Communication_851', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_551'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034710a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358751' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:671' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1092' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3923', 'source': 'Event_Communication_852', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_305'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a1f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358752' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:672' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1169' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3926', 'source': 'Event_Communication_853', 'type': 'evidence_for', 'target': 'Relationship_Operates_546'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126edc730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358753' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:673' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:860' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3931', 'source': 'Event_Communication_855', 'type': 'evidence_for', 'target': 'Event_Enforcement_854'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99d90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044001' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:673' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1006' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3932', 'source': 'Event_Communication_855', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_497'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e086d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358754' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:674' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:55' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3936', 'source': 'Event_Communication_857', 'type': 'evidence_for', 'target': 'Event_Monitoring_856'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044002' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:674' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1118' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3937', 'source': 'Event_Communication_857', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_548'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358755' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:675' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:46' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3940', 'source': 'Event_Communication_859', 'type': 'evidence_for', 'target': 'Event_Monitoring_722'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ee3610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358757' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:677' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:46' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3944', 'source': 'Event_Communication_862', 'type': 'evidence_for', 'target': 'Event_Monitoring_722'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6ff40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358758' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:678' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1022' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3949', 'source': 'Event_Communication_864', 'type': 'evidence_for', 'target': 'Relationship_Reports_41'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e657c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044006' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:678' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:46' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3948', 'source': 'Event_Communication_864', 'type': 'evidence_for', 'target': 'Event_Monitoring_722'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9b760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358759' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:679' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1119' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3954', 'source': 'Event_Communication_866', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_550'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de79d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044007' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:679' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:46' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3953', 'source': 'Event_Communication_866', 'type': 'evidence_for', 'target': 'Event_Monitoring_722'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358760' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:680' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1119' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3957', 'source': 'Event_Communication_867', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_550'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e657c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044008' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:680' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:46' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3956', 'source': 'Event_Communication_867', 'type': 'evidence_for', 'target': 'Event_Monitoring_722'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ee37c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358761' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:681' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:912' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3960', 'source': 'Event_Communication_869', 'type': 'evidence_for', 'target': 'Event_Collaborate_868'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044009' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:681' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:945' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3961', 'source': 'Event_Communication_869', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_551'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb21f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358762' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:682' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1010' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3966', 'source': 'Event_Communication_871', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_553'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044010' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:682' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:835' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3965', 'source': 'Event_Communication_871', 'type': 'evidence_for', 'target': 'Event_VesselMovement_892'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e968e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358763' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:683' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1169' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3971', 'source': 'Event_Communication_873', 'type': 'evidence_for', 'target': 'Relationship_Operates_546'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126edc6a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044011' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:683' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:835' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3970', 'source': 'Event_Communication_873', 'type': 'evidence_for', 'target': 'Event_VesselMovement_892'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ee3e50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358764' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:684' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:144' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3974', 'source': 'Event_Communication_875', 'type': 'evidence_for', 'target': 'Event_Monitoring_978'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26e80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358765' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:685' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1120' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3979', 'source': 'Event_Communication_877', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_555'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9bd60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044013' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:685' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:55' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3978', 'source': 'Event_Communication_877', 'type': 'evidence_for', 'target': 'Event_Monitoring_856'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de84f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358766' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:686' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:56' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3983', 'source': 'Event_Communication_879', 'type': 'evidence_for', 'target': 'Event_Monitoring_878'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2e50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594081' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:686' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1121' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3984', 'source': 'Event_Communication_879', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_556'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b1c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358767' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:687' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1041' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3991', 'source': 'Event_Communication_881', 'type': 'evidence_for', 'target': 'Relationship_Reports_587'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9bd60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044015' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:687' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:837' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3989', 'source': 'Event_Communication_881', 'type': 'evidence_for', 'target': 'Event_VesselMovement_931'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729263' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:687' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1016' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3990', 'source': 'Event_Communication_881', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_588'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2e50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358768' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:688' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2369' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3994', 'source': 'Event_Communication_882', 'type': 'evidence_for', 'target': 'Relationship_Unfriendly_625'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc56d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358769' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:689' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:833' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3998', 'source': 'Event_Communication_884', 'type': 'evidence_for', 'target': 'Event_VesselMovement_883'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044017' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:689' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1011' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '3999', 'source': 'Event_Communication_884', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_560'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e869d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358770' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:690' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:833' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4003', 'source': 'Event_Communication_886', 'type': 'evidence_for', 'target': 'Event_VesselMovement_883'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044018' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:690' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1011' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4004', 'source': 'Event_Communication_886', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_560'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358771' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:691' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:834' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4008', 'source': 'Event_Communication_888', 'type': 'evidence_for', 'target': 'Event_VesselMovement_887'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044019' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:691' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1012' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4009', 'source': 'Event_Communication_888', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_562'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e738e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358772' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:692' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:811' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4013', 'source': 'Event_Communication_890', 'type': 'evidence_for', 'target': 'Event_VesselMovement_402'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044020' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:692' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:978' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4014', 'source': 'Event_Communication_890', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_244'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaa850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358773' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:693' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1013' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4017', 'source': 'Event_Communication_891', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_564'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358774' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:694' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:835' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4020', 'source': 'Event_Communication_893', 'type': 'evidence_for', 'target': 'Event_VesselMovement_892'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bcd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358776' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:696' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:23' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4025', 'source': 'Event_Communication_897', 'type': 'evidence_for', 'target': 'Event_Monitoring_266'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ee3190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594082' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:697' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1122' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4028', 'source': 'Event_Communication_898', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_565'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaa850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358779' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:699' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:58' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4032', 'source': 'Event_Communication_901', 'type': 'evidence_for', 'target': 'Event_Monitoring_900'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044027' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:699' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1170' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4033', 'source': 'Event_Communication_901', 'type': 'evidence_for', 'target': 'Relationship_Operates_566'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4eee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358780' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:700' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2368' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4036', 'source': 'Event_Communication_902', 'type': 'evidence_for', 'target': 'Relationship_Unfriendly_567'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358781' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:701' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1054' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4039', 'source': 'Event_Communication_903', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_583'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6f580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358782' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:702' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:836' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4044', 'source': 'Event_Communication_905', 'type': 'evidence_for', 'target': 'Event_VesselMovement_904'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecd250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044030' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:702' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1014' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4045', 'source': 'Event_Communication_905', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_569'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729278' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:702' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1054' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4046', 'source': 'Event_Communication_905', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_583'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecdcd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594000' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:703' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1040' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4055', 'source': 'Event_Communication_908', 'type': 'evidence_for', 'target': 'Relationship_Reports_572'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaaa90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044031' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:703' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1144' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4054', 'source': 'Event_Communication_908', 'type': 'evidence_for', 'target': 'Relationship_Operates_176'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7ffd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729279' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:703' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:23' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4052', 'source': 'Event_Communication_908', 'type': 'evidence_for', 'target': 'Event_Monitoring_266'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4eee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414527' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:703' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:793' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4053', 'source': 'Event_Communication_908', 'type': 'evidence_for', 'target': 'Event_Assessment_973'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358784' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:704' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:61' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4059', 'source': 'Event_Communication_910', 'type': 'evidence_for', 'target': 'Event_Monitoring_909'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff5e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594083' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:704' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1123' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4060', 'source': 'Event_Communication_910', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_573'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358785' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:705' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:63' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4063', 'source': 'Event_Communication_912', 'type': 'evidence_for', 'target': 'Event_Monitoring_911'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7ff40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358786' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:706' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1053' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4070', 'source': 'Event_Communication_914', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_575'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ee3460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044034' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:706' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:793' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4068', 'source': 'Event_Communication_914', 'type': 'evidence_for', 'target': 'Event_Assessment_973'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a6a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729282' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:706' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:998' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4069', 'source': 'Event_Communication_914', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_421'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126edcd30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687595323' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:707' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2363' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4077', 'source': 'Event_Communication_916', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_577'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e993a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044035' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:707' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1133' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4076', 'source': 'Event_Communication_916', 'type': 'evidence_for', 'target': 'Relationship_Operates_58'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eef8e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729283' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:707' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:52' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4075', 'source': 'Event_Communication_916', 'type': 'evidence_for', 'target': 'Event_Monitoring_803'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358788' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:708' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:66' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4082', 'source': 'Event_Communication_919', 'type': 'evidence_for', 'target': 'Event_Monitoring_917'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec4040>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044036' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:708' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1124' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4084', 'source': 'Event_Communication_919', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_578'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecb310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729284' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:708' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:782' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4083', 'source': 'Event_Communication_919', 'type': 'evidence_for', 'target': 'Event_Assessment_628'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358790' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:710' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:946' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4088', 'source': 'Event_Communication_921', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_589'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358791' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:711' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:67' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4091', 'source': 'Event_Communication_923', 'type': 'evidence_for', 'target': 'Event_Monitoring_922'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044039' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:711' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:946' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4092', 'source': 'Event_Communication_923', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_589'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358792' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:712' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:946' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4099', 'source': 'Event_Communication_925', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_589'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecdf70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044040' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:712' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:929' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4098', 'source': 'Event_Communication_925', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_84'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb5730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729288' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:712' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:34' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4097', 'source': 'Event_Communication_925', 'type': 'evidence_for', 'target': 'Event_Monitoring_595'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e657c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358795' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:715' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:915' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4104', 'source': 'Event_Communication_928', 'type': 'evidence_for', 'target': 'Event_HarborReport_927'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec4190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044043' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:715' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1054' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4105', 'source': 'Event_Communication_928', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_583'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358797' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:717' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:68' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4111', 'source': 'Event_Communication_930', 'type': 'evidence_for', 'target': 'Event_Monitoring_929'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99df0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044045' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:717' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1015' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4113', 'source': 'Event_Communication_930', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_585'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e9a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729293' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:717' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1055' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4114', 'source': 'Event_Communication_930', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_586'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414541' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:717' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1041' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4112', 'source': 'Event_Communication_930', 'type': 'evidence_for', 'target': 'Relationship_Reports_587'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6f490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358798' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:718' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:837' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4120', 'source': 'Event_Communication_933', 'type': 'evidence_for', 'target': 'Event_VesselMovement_931'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e659a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044046' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:718' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:70' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4121', 'source': 'Event_Communication_933', 'type': 'evidence_for', 'target': 'Event_Monitoring_932'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e9a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729294' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:718' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1041' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4122', 'source': 'Event_Communication_933', 'type': 'evidence_for', 'target': 'Relationship_Reports_587'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e734c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414542' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:718' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1016' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4123', 'source': 'Event_Communication_933', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_588'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecbb50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358799' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:719' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:71' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4125', 'source': 'Event_Communication_935', 'type': 'evidence_for', 'target': 'Event_Monitoring_934'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358800' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:720' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:946' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4128', 'source': 'Event_Communication_936', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_589'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358802' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:722' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:879' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4133', 'source': 'Event_Communication_939', 'type': 'evidence_for', 'target': 'Event_TourActivity_938'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044050' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:722' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1018' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4134', 'source': 'Event_Communication_939', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_594'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358803' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:723' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1017' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4138', 'source': 'Event_Communication_940', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_591'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7ffd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044051' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:723' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1171' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4139', 'source': 'Event_Communication_940', 'type': 'evidence_for', 'target': 'Relationship_Operates_592'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358804' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:724' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:72' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4145', 'source': 'Event_Communication_943', 'type': 'evidence_for', 'target': 'Event_Monitoring_941'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48a30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044052' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:724' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:75' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4146', 'source': 'Event_Communication_943', 'type': 'evidence_for', 'target': 'Event_Monitoring_942'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecd340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729300' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:724' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1172' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4147', 'source': 'Event_Communication_943', 'type': 'evidence_for', 'target': 'Relationship_Operates_593'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c6d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414548' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:724' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1018' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4148', 'source': 'Event_Communication_943', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_594'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaaa30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358805' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:725' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:838' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4151', 'source': 'Event_Communication_945', 'type': 'evidence_for', 'target': 'Event_VesselMovement_944'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6ff40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358806' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:726' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:76' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4158', 'source': 'Event_Communication_949', 'type': 'evidence_for', 'target': 'Event_Monitoring_946'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecda90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044054' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:726' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:861' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4159', 'source': 'Event_Communication_949', 'type': 'evidence_for', 'target': 'Event_Enforcement_947'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c6d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729302' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:726' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1097' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4161', 'source': 'Event_Communication_949', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_378'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126edc7f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414550' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:726' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1006' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4162', 'source': 'Event_Communication_949', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_497'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96cd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1161933101908099798' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:726' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:794' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4160', 'source': 'Event_Communication_949', 'type': 'evidence_for', 'target': 'Event_Assessment_996'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecbcd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358807' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:727' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:947' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4169', 'source': 'Event_Communication_950', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_599'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3afd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044055' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:727' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:922' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4168', 'source': 'Event_Communication_950', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_11'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729303' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:727' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:948' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4167', 'source': 'Event_Communication_950', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_601'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7d60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358808' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:728' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2364' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4173', 'source': 'Event_Communication_951', 'type': 'evidence_for', 'target': 'Relationship_Suspicious_600'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ee3fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044056' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:728' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:948' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4174', 'source': 'Event_Communication_951', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_601'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358809' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:729' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:862' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4177', 'source': 'Event_Communication_953', 'type': 'evidence_for', 'target': 'Event_Enforcement_952'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ee35e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358810' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:730' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:835' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4180', 'source': 'Event_Communication_955', 'type': 'evidence_for', 'target': 'Event_VesselMovement_892'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eefb80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358811' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:731' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:79' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4187', 'source': 'Event_Communication_958', 'type': 'evidence_for', 'target': 'Event_Monitoring_957'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecda90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594133' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:731' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1173' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4188', 'source': 'Event_Communication_958', 'type': 'evidence_for', 'target': 'Relationship_Operates_602'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e86310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594002' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:731' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1042' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4189', 'source': 'Event_Communication_958', 'type': 'evidence_for', 'target': 'Relationship_Reports_603'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eefd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044059' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:731' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:879' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4186', 'source': 'Event_Communication_958', 'type': 'evidence_for', 'target': 'Event_TourActivity_938'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a3a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594003' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:732' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1043' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4194', 'source': 'Event_Communication_960', 'type': 'evidence_for', 'target': 'Relationship_Reports_604'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044060' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:732' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:156' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4193', 'source': 'Event_Communication_960', 'type': 'evidence_for', 'target': 'Event_Monitoring_995'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e86310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358813' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:733' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1068' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4197', 'source': 'Event_Communication_961', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_54'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ef4cd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358814' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:734' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:880' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4202', 'source': 'Event_Communication_963', 'type': 'evidence_for', 'target': 'Event_TourActivity_962'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ef4ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044062' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:734' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1133' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4203', 'source': 'Event_Communication_963', 'type': 'evidence_for', 'target': 'Relationship_Operates_58'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eef370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729310' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:734' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:977' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4204', 'source': 'Event_Communication_963', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_243'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126edcc70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358816' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:736' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:944' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4207', 'source': 'Event_Communication_964', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_536'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358818' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:738' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:792' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4214', 'source': 'Event_Communication_968', 'type': 'evidence_for', 'target': 'Event_Assessment_966'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de79d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044066' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:738' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:105' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4215', 'source': 'Event_Communication_968', 'type': 'evidence_for', 'target': 'Event_Monitoring_967'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126edc520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729314' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:738' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1125' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4216', 'source': 'Event_Communication_968', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_609'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eefcd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414562' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:738' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1031' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4217', 'source': 'Event_Communication_968', 'type': 'evidence_for', 'target': 'Relationship_Reports_344'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358819' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:739' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1056' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4224', 'source': 'Event_Communication_970', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_611'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5bb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044067' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:739' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1057' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4226', 'source': 'Event_Communication_970', 'type': 'evidence_for', 'target': 'Relationship_Jurisdiction_613'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ee3400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729315' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:739' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1006' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4225', 'source': 'Event_Communication_970', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_497'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7a90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414563' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:739' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:76' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4223', 'source': 'Event_Communication_970', 'type': 'evidence_for', 'target': 'Event_Monitoring_946'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ef44c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358820' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:740' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:123' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4229', 'source': 'Event_Communication_974', 'type': 'evidence_for', 'target': 'Event_Monitoring_971'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd6670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044068' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:740' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:913' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4230', 'source': 'Event_Communication_974', 'type': 'evidence_for', 'target': 'Event_Collaborate_972'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ee3100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729316' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:740' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:793' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4231', 'source': 'Event_Communication_974', 'type': 'evidence_for', 'target': 'Event_Assessment_973'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ef4640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159681302094414564' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:740' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1126' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4232', 'source': 'Event_Communication_974', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_614'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1161933101908099812' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:740' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1019' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4233', 'source': 'Event_Communication_974', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_615'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e86ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358821' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:741' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:156' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4236', 'source': 'Event_Communication_976', 'type': 'evidence_for', 'target': 'Event_Monitoring_995'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ee3070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594087' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:742' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1127' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4239', 'source': 'Event_Communication_977', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_616'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358823' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:743' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:144' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4242', 'source': 'Event_Communication_979', 'type': 'evidence_for', 'target': 'Event_Monitoring_978'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358824' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:744' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:839' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4245', 'source': 'Event_Communication_981', 'type': 'evidence_for', 'target': 'Event_VesselMovement_980'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7e80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358828' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:748' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:949' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4252', 'source': 'Event_Communication_984', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_617'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044076' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:748' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1128' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4253', 'source': 'Event_Communication_984', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_618'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7160>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729324' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:748' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:835' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4251', 'source': 'Event_Communication_984', 'type': 'evidence_for', 'target': 'Event_VesselMovement_892'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ef4b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358829' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:749' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:950' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4259', 'source': 'Event_Communication_986', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_619'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e86220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044077' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:749' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1169' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4260', 'source': 'Event_Communication_986', 'type': 'evidence_for', 'target': 'Relationship_Operates_546'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9b370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729325' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:749' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:835' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4258', 'source': 'Event_Communication_986', 'type': 'evidence_for', 'target': 'Event_VesselMovement_892'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de79d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594089' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:750' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1129' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4263', 'source': 'Event_Communication_987', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_621'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48bb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594004' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:751' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1044' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4268', 'source': 'Event_Communication_989', 'type': 'evidence_for', 'target': 'Relationship_Reports_622'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6f7c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044079' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:751' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:796' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4267', 'source': 'Event_Communication_989', 'type': 'evidence_for', 'target': 'Event_VesselMovement_122'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ee3790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358832' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:752' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:34' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4271', 'source': 'Event_Communication_991', 'type': 'evidence_for', 'target': 'Event_Monitoring_595'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358833' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:753' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:863' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4276', 'source': 'Event_Communication_993', 'type': 'evidence_for', 'target': 'Event_Enforcement_992'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ef4c70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044081' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:753' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1130' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4277', 'source': 'Event_Communication_993', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_623'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1cfd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729329' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:753' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1005' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4278', 'source': 'Event_Communication_993', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_489'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126edc7f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358834' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:754' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2369' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4281', 'source': 'Event_Communication_994', 'type': 'evidence_for', 'target': 'Relationship_Unfriendly_625'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358835' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:755' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:156' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4286', 'source': 'Event_Communication_997', 'type': 'evidence_for', 'target': 'Event_Monitoring_995'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecbac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044083' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:755' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:794' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4287', 'source': 'Event_Communication_997', 'type': 'evidence_for', 'target': 'Event_Assessment_996'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157429502280729331' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:755' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1024' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4288', 'source': 'Event_Communication_997', 'type': 'evidence_for', 'target': 'Relationship_Reports_51'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358836' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:756' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:865' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4292', 'source': 'Event_Communication_999', 'type': 'evidence_for', 'target': 'Event_Enforcement_998'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e0e0d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044084' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:756' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1006' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4293', 'source': 'Event_Communication_999', 'type': 'evidence_for', 'target': 'Relationship_AccessPermission_497'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec4af0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358837' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:757' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:840' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4297', 'source': 'Event_Communication_1001', 'type': 'evidence_for', 'target': 'Event_VesselMovement_1000'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecd8b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155177702467044085' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:757' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:951' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4298', 'source': 'Event_Communication_1001', 'type': 'evidence_for', 'target': 'Relationship_Colleagues_628'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152925902653358838' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:758' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:841' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4302', 'source': 'Event_Communication_1003', 'type': 'evidence_for', 'target': 'Event_VesselMovement_1002'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf9a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917533425687594091' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:758' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1131' labels=frozenset() properties={}>) type='evidence_for' properties={'is_inferred': True, 'id': '4303', 'source': 'Event_Communication_1003', 'type': 'evidence_for', 'target': 'Relationship_Coordinates_629'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb5ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870123' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:939' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3055', 'source': 'Relationship_Colleagues_323', 'type': 'target', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155182100513555371' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:939' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3056', 'source': 'Relationship_Colleagues_323', 'type': 'target', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eef940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917537823734106386' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:952' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2669', 'source': 'Relationship_AccessPermission_7', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870137' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:953' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1980', 'source': 'Relationship_AccessPermission_68', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126efbf40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870138' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:954' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1821', 'source': 'Relationship_AccessPermission_81', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126efb880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870139' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:955' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2116', 'source': 'Relationship_AccessPermission_96', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec4eb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870140' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:956' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2323' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2128', 'source': 'Relationship_AccessPermission_98', 'type': 'target', 'target': 'Restricted_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7970>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870141' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:957' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2328' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2193', 'source': 'Relationship_AccessPermission_100', 'type': 'target', 'target': 'Southern_islands'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870142' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:958' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2361', 'source': 'Relationship_AccessPermission_101', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4ee50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870143' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:959' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2325' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2198', 'source': 'Relationship_AccessPermission_118', 'type': 'target', 'target': 'Protected_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec4670>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870144' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:960' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2325' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2216', 'source': 'Relationship_AccessPermission_122', 'type': 'target', 'target': 'Protected_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb5fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870145' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:961' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2325' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2224', 'source': 'Relationship_AccessPermission_125', 'type': 'target', 'target': 'Protected_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870146' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:962' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2331' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2232', 'source': 'Relationship_AccessPermission_127', 'type': 'target', 'target': 'Dolphin_Bay'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7feb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870147' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:963' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2233', 'source': 'Relationship_AccessPermission_128', 'type': 'target', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7e80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870148' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:964' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2342' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2240', 'source': 'Relationship_AccessPermission_129', 'type': 'target', 'target': 'Restricted_Zone'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e280>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870149' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:965' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2325' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1697', 'source': 'Relationship_AccessPermission_148', 'type': 'target', 'target': 'Protected_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690f940>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870150' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:966' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2362', 'source': 'Relationship_AccessPermission_156', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870152' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:968' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2380', 'source': 'Relationship_AccessPermission_163', 'type': 'target', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870153' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:969' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2492', 'source': 'Relationship_AccessPermission_181', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870154' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:970' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2824', 'source': 'Relationship_AccessPermission_190', 'type': 'target', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870156' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:972' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1908', 'source': 'Relationship_AccessPermission_196', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a7f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870157' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:973' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3874', 'source': 'Relationship_AccessPermission_214', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7970>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870158' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:974' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3722', 'source': 'Relationship_AccessPermission_232', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb51c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870159' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:975' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2658', 'source': 'Relationship_AccessPermission_233', 'type': 'target', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870160' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:976' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2023', 'source': 'Relationship_AccessPermission_238', 'type': 'target', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e86100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870161' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:977' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2580', 'source': 'Relationship_AccessPermission_243', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53df0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870162' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:978' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4011', 'source': 'Relationship_AccessPermission_244', 'type': 'target', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126efbac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870164' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:980' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2344' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2766', 'source': 'Relationship_AccessPermission_262', 'type': 'target', 'target': 'South_Dock'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126efb460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870165' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:981' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2469', 'source': 'Relationship_AccessPermission_266', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecbe20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870166' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:982' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2326' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2957', 'source': 'Relationship_AccessPermission_281', 'type': 'target', 'target': 'Eastern_reefs'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecdbe0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870167' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:983' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2976', 'source': 'Relationship_AccessPermission_303', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7fa90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917537823734106407' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:984' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2343' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2977', 'source': 'Relationship_AccessPermission_304', 'type': 'target', 'target': 'Route_C'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870169' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:985' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2343' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2984', 'source': 'Relationship_AccessPermission_306', 'type': 'target', 'target': 'Route_C'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e869a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870170' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:986' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3021', 'source': 'Relationship_AccessPermission_313', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e280>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870171' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:987' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2342' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3072', 'source': 'Relationship_AccessPermission_328', 'type': 'target', 'target': 'Restricted_Zone'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecb250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870172' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:988' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2326' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3091', 'source': 'Relationship_AccessPermission_332', 'type': 'target', 'target': 'Eastern_reefs'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9b760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870173' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:989' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1729', 'source': 'Relationship_AccessPermission_338', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870174' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:990' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3164', 'source': 'Relationship_AccessPermission_349', 'type': 'target', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870175' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:991' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3246', 'source': 'Relationship_AccessPermission_370', 'type': 'target', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870176' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:992' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2523', 'source': 'Relationship_AccessPermission_382', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126edc520>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870177' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:993' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3330', 'source': 'Relationship_AccessPermission_392', 'type': 'target', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126bb0a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870178' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:994' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3331', 'source': 'Relationship_AccessPermission_393', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08460>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870179' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:995' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3350', 'source': 'Relationship_AccessPermission_397', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870180' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:996' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3078', 'source': 'Relationship_AccessPermission_405', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e730d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870181' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:997' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3320', 'source': 'Relationship_AccessPermission_415', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ee3190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870182' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:998' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4065', 'source': 'Relationship_AccessPermission_421', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ef4d90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870184' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1000' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3541', 'source': 'Relationship_AccessPermission_441', 'type': 'target', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc3190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870185' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1001' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3386', 'source': 'Relationship_AccessPermission_444', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eefdf0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870186' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1002' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2333' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3599', 'source': 'Relationship_AccessPermission_455', 'type': 'target', 'target': 'Northern_quadrant'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126df7e80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870187' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1003' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2323' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3663', 'source': 'Relationship_AccessPermission_477', 'type': 'target', 'target': 'Restricted_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd64c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870188' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1004' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2323' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3672', 'source': 'Relationship_AccessPermission_479', 'type': 'target', 'target': 'Restricted_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870189' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1005' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4274', 'source': 'Relationship_AccessPermission_489', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eefdf0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870190' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1006' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3250', 'source': 'Relationship_AccessPermission_497', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bdc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870191' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1007' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3771', 'source': 'Relationship_AccessPermission_502', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e482e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870192' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1008' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2342' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3805', 'source': 'Relationship_AccessPermission_511', 'type': 'target', 'target': 'Restricted_Zone'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8bb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870193' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1009' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2342' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3806', 'source': 'Relationship_AccessPermission_512', 'type': 'target', 'target': 'Restricted_Zone'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870194' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1010' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2344' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3963', 'source': 'Relationship_AccessPermission_553', 'type': 'target', 'target': 'South_Dock'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de84f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870195' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1011' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2320' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4001', 'source': 'Relationship_AccessPermission_560', 'type': 'target', 'target': 'Haacklee_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ee31f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870196' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1012' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4006', 'source': 'Relationship_AccessPermission_562', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bb50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917537823734106410' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1013' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2346' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4015', 'source': 'Relationship_AccessPermission_564', 'type': 'target', 'target': 'Berth_14'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870198' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1014' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4041', 'source': 'Relationship_AccessPermission_569', 'type': 'target', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2cd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870199' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1015' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2342' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4108', 'source': 'Relationship_AccessPermission_585', 'type': 'target', 'target': 'Restricted_Zone'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126edc850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870200' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1016' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2336' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3986', 'source': 'Relationship_AccessPermission_588', 'type': 'target', 'target': 'Western_quadrant'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaaa90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870201' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1017' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2330' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4135', 'source': 'Relationship_AccessPermission_591', 'type': 'target', 'target': 'Coral_Point'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26880>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870202' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1018' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2344' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4131', 'source': 'Relationship_AccessPermission_594', 'type': 'target', 'target': 'South_Dock'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:6917537823734106359' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1020' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1744', 'source': 'Relationship_Reports_18', 'type': 'target', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e482e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870205' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1021' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1858', 'source': 'Relationship_Reports_38', 'type': 'target', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1bc10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870206' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1022' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2614', 'source': 'Relationship_Reports_41', 'type': 'target', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fdf0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870207' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1023' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1898', 'source': 'Relationship_Reports_46', 'type': 'target', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870208' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1024' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4284', 'source': 'Relationship_Reports_51', 'type': 'target', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126edc3a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870209' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1025' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2298' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1981', 'source': 'Relationship_Reports_69', 'type': 'target', 'target': 'Sailor_Shifts_Team'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ef4dc0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870210' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1026' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1995', 'source': 'Relationship_Reports_73', 'type': 'target', 'target': 'Rodriguez'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c4f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870211' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1027' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2421', 'source': 'Relationship_Reports_170', 'type': 'target', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4ee80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870212' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1028' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2568', 'source': 'Relationship_Reports_205', 'type': 'target', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126edc6d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870213' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1029' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2608', 'source': 'Relationship_Reports_218', 'type': 'target', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb27f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870214' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1030' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2894', 'source': 'Relationship_Reports_288', 'type': 'target', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f1c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870215' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1031' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4212', 'source': 'Relationship_Reports_344', 'type': 'target', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2b50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870216' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1032' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3262', 'source': 'Relationship_Reports_355', 'type': 'target', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ef4250>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870217' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1033' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3403', 'source': 'Relationship_Reports_408', 'type': 'target', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ee3190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870218' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1034' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3578', 'source': 'Relationship_Reports_447', 'type': 'target', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870219' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1035' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3739', 'source': 'Relationship_Reports_496', 'type': 'target', 'target': 'Boss'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c5e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870220' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1036' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3296', 'source': 'Relationship_Reports_513', 'type': 'target', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ef4b80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870221' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1037' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2089', 'source': 'Relationship_Reports_526', 'type': 'target', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e86b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870222' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1038' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3269', 'source': 'Relationship_Reports_529', 'type': 'target', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec4af0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870223' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1039' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3886', 'source': 'Relationship_Reports_537', 'type': 'target', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e867f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870224' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1040' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4050', 'source': 'Relationship_Reports_572', 'type': 'target', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126edc610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870225' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1041' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3030', 'source': 'Relationship_Reports_587', 'type': 'target', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e86b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870226' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1042' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4184', 'source': 'Relationship_Reports_603', 'type': 'target', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecb7f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870227' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1043' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4191', 'source': 'Relationship_Reports_604', 'type': 'target', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870228' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1044' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4265', 'source': 'Relationship_Reports_622', 'type': 'target', 'target': 'Boss'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecbb80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870229' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1045' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2325' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1745', 'source': 'Relationship_Jurisdiction_19', 'type': 'target', 'target': 'Protected_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eef5b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155182100513555477' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1045' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1746', 'source': 'Relationship_Jurisdiction_19', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f1c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870230' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1046' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2325' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1754', 'source': 'Relationship_Jurisdiction_21', 'type': 'target', 'target': 'Protected_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e865b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870231' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1047' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2325' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1810', 'source': 'Relationship_Jurisdiction_29', 'type': 'target', 'target': 'Protected_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9b6d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870232' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1048' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2311', 'source': 'Relationship_Jurisdiction_131', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870233' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1049' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2325' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2375', 'source': 'Relationship_Jurisdiction_162', 'type': 'target', 'target': 'Protected_areas'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb5f40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870234' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1050' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2321' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2024', 'source': 'Relationship_Jurisdiction_390', 'type': 'target', 'target': 'Himark_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e086d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870235' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1051' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2083', 'source': 'Relationship_Jurisdiction_446', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eef400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870236' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1052' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2333' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3592', 'source': 'Relationship_Jurisdiction_454', 'type': 'target', 'target': 'Northern_quadrant'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99a00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870237' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1053' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4066', 'source': 'Relationship_Jurisdiction_575', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126efb490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870238' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1054' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4042', 'source': 'Relationship_Jurisdiction_583', 'type': 'target', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb5730>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870239' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1055' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2342' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3683', 'source': 'Relationship_Jurisdiction_586', 'type': 'target', 'target': 'Restricted_Zone'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126efbc70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870240' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1056' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4219', 'source': 'Relationship_Jurisdiction_611', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870241' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1057' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4221', 'source': 'Relationship_Jurisdiction_613', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e86b20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870242' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1058' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1753', 'source': 'Relationship_Coordinates_20', 'type': 'target', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99e50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870243' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1059' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1777', 'source': 'Relationship_Coordinates_24', 'type': 'target', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecbca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870244' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1060' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3585', 'source': 'Relationship_Coordinates_27', 'type': 'target', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb5490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870245' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1061' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2298' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1817', 'source': 'Relationship_Coordinates_30', 'type': 'target', 'target': 'Sailor_Shifts_Team'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e659a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870246' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1062' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1835', 'source': 'Relationship_Coordinates_33', 'type': 'target', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870247' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1063' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2131', 'source': 'Relationship_Coordinates_35', 'type': 'target', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecb310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870249' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1065' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1861', 'source': 'Relationship_Coordinates_39', 'type': 'target', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99430>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155182100513555497' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1065' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1862', 'source': 'Relationship_Coordinates_39', 'type': 'target', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4ee50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870250' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1066' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1885', 'source': 'Relationship_Coordinates_43', 'type': 'target', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870251' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1067' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3394', 'source': 'Relationship_Coordinates_53', 'type': 'target', 'target': 'EcoVigil'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e080a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870252' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1068' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3869', 'source': 'Relationship_Coordinates_54', 'type': 'target', 'target': 'EcoVigil'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb56d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870253' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1069' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2293' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2016', 'source': 'Relationship_Coordinates_77', 'type': 'target', 'target': 'Small_Fry'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7ffa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870254' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1070' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2077', 'source': 'Relationship_Coordinates_116', 'type': 'target', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126f01f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870255' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1071' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2313' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2209', 'source': 'Relationship_Coordinates_120', 'type': 'target', 'target': 'Mariner_s_Dream'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecb310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870256' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1072' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2441', 'source': 'Relationship_Coordinates_172', 'type': 'target', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecd6a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870257' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1073' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2499', 'source': 'Relationship_Coordinates_185', 'type': 'target', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73d30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870258' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1074' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2557', 'source': 'Relationship_Coordinates_201', 'type': 'target', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec4580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870259' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1075' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2634', 'source': 'Relationship_Coordinates_226', 'type': 'target', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecb370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870260' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1076' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2648', 'source': 'Relationship_Coordinates_231', 'type': 'target', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f7c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155182100513555508' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1076' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2649', 'source': 'Relationship_Coordinates_231', 'type': 'target', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870261' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1077' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2292' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2666', 'source': 'Relationship_Coordinates_236', 'type': 'target', 'target': 'Boss'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e33eb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870263' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1079' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2747', 'source': 'Relationship_Coordinates_248', 'type': 'target', 'target': 'Serenity'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6f220>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870264' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1080' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1929', 'source': 'Relationship_Coordinates_251', 'type': 'target', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f7c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870265' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1081' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2736', 'source': 'Relationship_Coordinates_252', 'type': 'target', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaafd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870266' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1082' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2742', 'source': 'Relationship_Coordinates_253', 'type': 'target', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155182100513555514' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1082' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2743', 'source': 'Relationship_Coordinates_253', 'type': 'target', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e994c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157433900327240762' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1082' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2744', 'source': 'Relationship_Coordinates_253', 'type': 'target', 'target': 'Serenity'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2ca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870267' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1083' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2328', 'source': 'Relationship_Coordinates_269', 'type': 'target', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaaf70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870268' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1084' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2290' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2816', 'source': 'Relationship_Coordinates_274', 'type': 'target', 'target': 'Mrs__Money'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fb20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870269' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1085' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2842', 'source': 'Relationship_Coordinates_279', 'type': 'target', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e080a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155182100513555517' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1085' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2843', 'source': 'Relationship_Coordinates_279', 'type': 'target', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f0a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870270' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1086' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2849', 'source': 'Relationship_Coordinates_280', 'type': 'target', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ee3640>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155182100513555518' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1086' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2850', 'source': 'Relationship_Coordinates_280', 'type': 'target', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2b80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870271' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1087' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2315' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2895', 'source': 'Relationship_Coordinates_289', 'type': 'target', 'target': 'City_Officials'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126edc6a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870272' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1088' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2905', 'source': 'Relationship_Coordinates_292', 'type': 'target', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fca0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870273' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1089' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2761', 'source': 'Relationship_Coordinates_297', 'type': 'target', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eefee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870274' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1090' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3092', 'source': 'Relationship_Coordinates_298', 'type': 'target', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9bd60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870275' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1091' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2969', 'source': 'Relationship_Coordinates_302', 'type': 'target', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99f70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870276' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1092' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3921', 'source': 'Relationship_Coordinates_305', 'type': 'target', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126f01760>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870277' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1093' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2991', 'source': 'Relationship_Coordinates_307', 'type': 'target', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec4130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155182100513555525' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1093' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2992', 'source': 'Relationship_Coordinates_307', 'type': 'target', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ee3fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870278' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1094' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3425', 'source': 'Relationship_Coordinates_334', 'type': 'target', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126edc820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870279' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1095' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2830', 'source': 'Relationship_Coordinates_336', 'type': 'target', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9be80>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870280' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1096' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3136', 'source': 'Relationship_Coordinates_343', 'type': 'target', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ef4c10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155182100513555528' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1096' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3137', 'source': 'Relationship_Coordinates_343', 'type': 'target', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ef45e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870281' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1097' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3572', 'source': 'Relationship_Coordinates_378', 'type': 'target', 'target': 'EcoVigil'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaa7f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870282' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1098' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2300' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3363', 'source': 'Relationship_Coordinates_380', 'type': 'target', 'target': 'Marlin'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaaa90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870283' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1099' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3061', 'source': 'Relationship_Coordinates_387', 'type': 'target', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ef4c10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870284' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1100' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3280', 'source': 'Relationship_Coordinates_401', 'type': 'target', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x1034ff5e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870285' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1101' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3413', 'source': 'Relationship_Coordinates_411', 'type': 'target', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870286' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1102' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3422', 'source': 'Relationship_Coordinates_413', 'type': 'target', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126edc850>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870287' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1103' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3438', 'source': 'Relationship_Coordinates_418', 'type': 'target', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eef4f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870288' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1104' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3462', 'source': 'Relationship_Coordinates_423', 'type': 'target', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec4910>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870289' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1105' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2278' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3484', 'source': 'Relationship_Coordinates_428', 'type': 'target', 'target': 'Nadia_Conti'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaaa00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870290' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1106' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3529', 'source': 'Relationship_Coordinates_437', 'type': 'target', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ee3790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870291' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1107' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3554', 'source': 'Relationship_Coordinates_445', 'type': 'target', 'target': 'EcoVigil'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eef4f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870292' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1108' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3567', 'source': 'Relationship_Coordinates_448', 'type': 'target', 'target': 'EcoVigil'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870293' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1109' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2703', 'source': 'Relationship_Coordinates_471', 'type': 'target', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaac10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870294' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1110' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3628', 'source': 'Relationship_Coordinates_473', 'type': 'target', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ee3790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870295' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1111' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3729', 'source': 'Relationship_Coordinates_492', 'type': 'target', 'target': 'Seawatch'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e968e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870296' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1112' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2306' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3733', 'source': 'Relationship_Coordinates_493', 'type': 'target', 'target': 'EcoVigil'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec4580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870297' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1113' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3789', 'source': 'Relationship_Coordinates_499', 'type': 'target', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126edcfa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870298' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1114' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3776', 'source': 'Relationship_Coordinates_503', 'type': 'target', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd1400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155182100513555546' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1114' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3777', 'source': 'Relationship_Coordinates_503', 'type': 'target', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e968e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870299' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1115' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1889', 'source': 'Relationship_Coordinates_509', 'type': 'target', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb5fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870300' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1116' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3640', 'source': 'Relationship_Coordinates_516', 'type': 'target', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870301' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1117' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3826', 'source': 'Relationship_Coordinates_518', 'type': 'target', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb2be0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870302' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1118' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3496', 'source': 'Relationship_Coordinates_548', 'type': 'target', 'target': 'Seawatch'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb5e50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870303' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1119' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3951', 'source': 'Relationship_Coordinates_550', 'type': 'target', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec4580>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870304' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1120' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2771', 'source': 'Relationship_Coordinates_555', 'type': 'target', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126edcee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870305' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1121' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2305' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3981', 'source': 'Relationship_Coordinates_556', 'type': 'target', 'target': 'Seawatch'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dd64c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870306' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1122' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4026', 'source': 'Relationship_Coordinates_565', 'type': 'target', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e087f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870307' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1123' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4056', 'source': 'Relationship_Coordinates_573', 'type': 'target', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a7c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155182100513555555' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1123' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4057', 'source': 'Relationship_Coordinates_573', 'type': 'target', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870308' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1124' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4080', 'source': 'Relationship_Coordinates_578', 'type': 'target', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf7f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870309' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1125' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3135', 'source': 'Relationship_Coordinates_609', 'type': 'target', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecbfd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870311' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1127' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4237', 'source': 'Relationship_Coordinates_616', 'type': 'target', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e7f040>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870312' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1128' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4249', 'source': 'Relationship_Coordinates_618', 'type': 'target', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecb4c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870313' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1129' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4261', 'source': 'Relationship_Coordinates_621', 'type': 'target', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf7f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870314' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1130' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4273', 'source': 'Relationship_Coordinates_623', 'type': 'target', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99970>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870315' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1131' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2312' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4300', 'source': 'Relationship_Coordinates_629', 'type': 'target', 'target': 'Knowles'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08400>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870316' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1132' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2304' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3862', 'source': 'Relationship_Operates_36', 'type': 'target', 'target': 'Horizon'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e1c8b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870317' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1133' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3085', 'source': 'Relationship_Operates_58', 'type': 'target', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8bb0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870318' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1134' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1944', 'source': 'Relationship_Operates_59', 'type': 'target', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126efb4f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870319' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1135' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2298' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1964', 'source': 'Relationship_Operates_65', 'type': 'target', 'target': 'Sailor_Shifts_Team'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99ee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870320' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1136' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2011', 'source': 'Relationship_Operates_75', 'type': 'target', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126f01340>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870322' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1138' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2314' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2122', 'source': 'Relationship_Operates_97', 'type': 'target', 'target': 'Recreational_Fishing_Boats'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e65a60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870323' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1139' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2312' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2147', 'source': 'Relationship_Operates_103', 'type': 'target', 'target': 'Knowles'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126f015b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870324' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1140' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2164', 'source': 'Relationship_Operates_109', 'type': 'target', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de8070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870325' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1141' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2359', 'source': 'Relationship_Operates_153', 'type': 'target', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126efbf70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870326' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1142' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2360', 'source': 'Relationship_Operates_154', 'type': 'target', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126f017c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870328' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1144' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2307' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4049', 'source': 'Relationship_Operates_176', 'type': 'target', 'target': 'Sentinel'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ee37c0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870329' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1145' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2560', 'source': 'Relationship_Operates_202', 'type': 'target', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cd8fd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870330' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1146' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2587', 'source': 'Relationship_Operates_210', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126efbd60>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870331' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1147' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2322' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2588', 'source': 'Relationship_Operates_211', 'type': 'target', 'target': 'Nemo_Reef'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ecb550>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870332' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1148' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2448', 'source': 'Relationship_Operates_255', 'type': 'target', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08700>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870333' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1149' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2301' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2749', 'source': 'Relationship_Operates_256', 'type': 'target', 'target': 'Serenity'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e99e50>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870334' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1150' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2319' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2802', 'source': 'Relationship_Operates_271', 'type': 'target', 'target': 'Paackland_Harbor'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126efbd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870335' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1151' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2281', 'source': 'Relationship_Operates_283', 'type': 'target', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126f017f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870336' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3071', 'source': 'Relationship_Operates_327', 'type': 'target', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26070>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870337' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1153' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2300' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3174', 'source': 'Relationship_Operates_351', 'type': 'target', 'target': 'Marlin'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96cd0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870339' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3234', 'source': 'Relationship_Operates_367', 'type': 'target', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126f01d00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870341' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1157' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3613', 'source': 'Relationship_Operates_459', 'type': 'target', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e08ac0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870342' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1158' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3618', 'source': 'Relationship_Operates_461', 'type': 'target', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126de7a90>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155182100513555590' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1158' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3619', 'source': 'Relationship_Operates_461', 'type': 'target', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e087f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870343' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1159' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3624', 'source': 'Relationship_Operates_463', 'type': 'target', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126efbd30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870344' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1160' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3312', 'source': 'Relationship_Operates_474', 'type': 'target', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126f016a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870345' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1161' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2968', 'source': 'Relationship_Operates_476', 'type': 'target', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e53820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870346' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1162' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3781', 'source': 'Relationship_Operates_505', 'type': 'target', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e96370>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870347' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1163' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3785', 'source': 'Relationship_Operates_506', 'type': 'target', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126efb3a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870348' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1164' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3205', 'source': 'Relationship_Operates_514', 'type': 'target', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e865b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870349' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1165' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3829', 'source': 'Relationship_Operates_519', 'type': 'target', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e2e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155182100513555597' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1165' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3830', 'source': 'Relationship_Operates_519', 'type': 'target', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e5a100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870350' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1166' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3836', 'source': 'Relationship_Operates_521', 'type': 'target', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126efb790>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870351' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1167' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3893', 'source': 'Relationship_Operates_538', 'type': 'target', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e26fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1155182100513555599' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1167' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3894', 'source': 'Relationship_Operates_538', 'type': 'target', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4e2e0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870352' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1168' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3916', 'source': 'Relationship_Operates_543', 'type': 'target', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x10351b490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870353' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1169' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2374', 'source': 'Relationship_Operates_546', 'type': 'target', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126efbe20>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870354' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1170' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2303' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3442', 'source': 'Relationship_Operates_566', 'type': 'target', 'target': 'Reef_Guardian'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eb5c40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870355' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1171' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4136', 'source': 'Relationship_Operates_592', 'type': 'target', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc58b0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870356' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1172' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4142', 'source': 'Relationship_Operates_593', 'type': 'target', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec4c10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870357' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1173' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4183', 'source': 'Relationship_Operates_602', 'type': 'target', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126f01610>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870358' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1174' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2298' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1987', 'source': 'Relationship_Suspicious_71', 'type': 'target', 'target': 'Sailor_Shifts_Team'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e730d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870359' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1175' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1996', 'source': 'Relationship_Suspicious_74', 'type': 'target', 'target': 'Rodriguez'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e48fa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870360' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1176' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2561', 'source': 'Relationship_Suspicious_106', 'type': 'target', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3ac10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870361' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1177' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2283' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '1986', 'source': 'Relationship_Suspicious_107', 'type': 'target', 'target': 'Rodriguez'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ee3130>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870362' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1178' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2312' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2157', 'source': 'Relationship_Suspicious_108', 'type': 'target', 'target': 'Knowles'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec4190>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870363' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1179' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2148', 'source': 'Relationship_Suspicious_110', 'type': 'target', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870364' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1180' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2170', 'source': 'Relationship_Suspicious_112', 'type': 'target', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eaa100>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870365' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1181' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2312' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2174', 'source': 'Relationship_Suspicious_113', 'type': 'target', 'target': 'Knowles'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126f019a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870366' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1182' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2311' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2217', 'source': 'Relationship_Suspicious_123', 'type': 'target', 'target': 'Remora'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e73310>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870367' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1183' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3314', 'source': 'Relationship_Suspicious_145', 'type': 'target', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ee39d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699870368' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1184' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2586', 'source': 'Relationship_Suspicious_209', 'type': 'target', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6fee0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699871532' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2348' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2603', 'source': 'Relationship_Suspicious_217', 'type': 'target', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126f0ddf0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699871533' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2349' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2285' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2609', 'source': 'Relationship_Suspicious_219', 'type': 'target', 'target': 'Clepper_Jensen'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5d30>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699871534' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2350' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3149', 'source': 'Relationship_Suspicious_293', 'type': 'target', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eefc10>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699871535' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2351' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2925', 'source': 'Relationship_Suspicious_294', 'type': 'target', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126cc5490>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699871536' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2352' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3037', 'source': 'Relationship_Suspicious_317', 'type': 'target', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126f0d970>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699871537' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2353' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2299' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3128', 'source': 'Relationship_Suspicious_341', 'type': 'target', 'target': 'Neptune'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126dc36a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699871538' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2354' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3212', 'source': 'Relationship_Suspicious_360', 'type': 'target', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126f1ad00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699871539' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2355' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3848', 'source': 'Relationship_Suspicious_368', 'type': 'target', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126eef9d0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699871540' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2356' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3408', 'source': 'Relationship_Suspicious_410', 'type': 'target', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126edcc70>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699871542' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2358' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3523', 'source': 'Relationship_Suspicious_436', 'type': 'target', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e3a820>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699871543' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2359' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2280' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3605', 'source': 'Relationship_Suspicious_457', 'type': 'target', 'target': 'Liam_Thorne'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9bfa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699871544' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2360' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3641', 'source': 'Relationship_Suspicious_470', 'type': 'target', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e4ec40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699871545' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2361' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3684', 'source': 'Relationship_Suspicious_483', 'type': 'target', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ddf0a0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699871547' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2363' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2309' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4073', 'source': 'Relationship_Suspicious_577', 'type': 'target', 'target': 'Defender'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6ff40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699871548' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2364' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2297' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3530', 'source': 'Relationship_Suspicious_600', 'type': 'target', 'target': 'V__Miesel_Shipping'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9bfa0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699871549' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2365' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2246', 'source': 'Relationship_Unfriendly_130', 'type': 'target', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec4f40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699871550' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2366' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '2643', 'source': 'Relationship_Unfriendly_229', 'type': 'target', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x12690fd00>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699871551' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2367' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2302' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3014', 'source': 'Relationship_Unfriendly_312', 'type': 'target', 'target': 'Mako'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e6ff40>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699871552' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2368' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2295' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '4034', 'source': 'Relationship_Unfriendly_567', 'type': 'target', 'target': 'Oceanus_City_Council'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126ec41f0>, keys=['r'])

EagerResult(records=[<Record r=<Relationship element_id='5:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:1152930300699871553' nodes=(<Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2369' labels=frozenset() properties={}>, <Node element_id='4:24d6b81b-a287-46ca-8ebe-dcb5619a7fcb:2296' labels=frozenset() properties={}>) type='target' properties={'is_inferred': True, 'id': '3992', 'source': 'Relationship_Unfriendly_625', 'type': 'target', 'target': 'Green_Guardians'}>>], summary=<neo4j._work.summary.ResultSummary object at 0x126e9bfa0>, keys=['r'])

In [31]:
print(f"Relationships uploaded: {success_count} successful, {error_count} failed")

Relationships uploaded: 3226 successful, 0 failed

In [ ]:
dsfsd

In [ ]:
def upload_relationships_simple(relationships_data, driver):
    """Upload relationships using simple Cypher syntax, one by one"""
    print(f"Uploading {len(relationships_data)} relationships...")
    
    success_count = 0
    error_count = 0

    for rel in relationships_data[:5]:
        try:
            rel_type = rel.get('type')
            if rel_type is None:
                source_type = rel.get('source_type')
                target_type = rel.get('target_type')
                print(source_type,target_type)
                rel_type=rels_missing_dict[source_type+"-"+target_type]
                rel['type']=rel_type

            escaped_rel_type = escape_cypher_identifier(rel_type)
            from_uid = escape_cypher_identifier(rel['source'])
            to_uid = escape_cypher_identifier(rel['target'])
            
            # Create properties dict, excluding internal fields
            properties = {}
            for key, value in rel.items():
                if key not in ['source', 'target', 'type', 'id']:
                    # Convert dict or list of dicts to JSON string
                    if isinstance(value, dict) or (isinstance(value, list) and any(isinstance(i, dict) for i in value)):
                        properties[key] = json.dumps(value)
                    else:
                        properties[key] = value
            
            # Create Cypher query using standard syntax
            query = f"""
            MATCH (a {{_uid: $from_uid}})
            MATCH (b {{_uid: $to_uid}})
            MERGE (a)-[r:{escaped_rel_type}]->(b)
            SET r += $properties
            RETURN r
            """
            
            #driver.execute_query(query, from_uid=from_uid, to_uid=to_uid, properties=properties)
            success_count += 1
            
        except Exception as e:
            rel_id = rel.get('id', f"{rel['source']}_{rel['target']}")
            print(f"Error uploading relationship {rel_id}: {e}")
            error_count += 1
    
    print(f"Relationships uploaded: {success_count} successful, {error_count} failed")

In [ ]:
for r in rels_by_type['source']:
    from_uid = escape_cypher_identifier(r['_from_uid'])
    to_uid = escape_cypher_identifier(r['_to_uid'])
    escaped_rel_type=r['type']
    properties = {}
    for key, value in r.items():
        if key not in ['source', 'target', 'type', 'id','_uid','is_inferred','_to_uid','__from_uid']:
            # Convert dict or list of dicts to JSON string
            if isinstance(value, dict) or (isinstance(value, list) and any(isinstance(i, dict) for i in value)):
                properties[key] = json.dumps(value)
            else:
                properties[key] = value
    query = f"""
        MATCH (a {{_uid: $from_uid}})
        MATCH (b {{_uid: $to_uid}})
        MERGE (a)-[r:{escaped_rel_type}]->(b)
        SET r += $properties
        RETURN r
        """

    with GraphDatabase.driver(uri, auth=(username, password)) as driver:
        driver.execute_query(query, from_uid=from_uid, to_uid=to_uid, properties=properties)

In [ ]:
rels_by_type.keys()

In [ ]:
neo4j_data = {
        'nodes': nodes_by_label,
        'relationships': rels_by_type
    }

In [ ]:
query, params = convert_nodes_fixed(neo4j_data['nodes'])

In [ ]:
params.keys()

In [ ]:
with GraphDatabase.driver(uri, auth=(username, password)) as driver:
  records, summary, keys = driver.execute_query(query, params)

In [ ]:
def convert_relationships_fixed(relationships: dict) -> (str, dict):
    """Fixed version of convert_relationships that properly escapes identifiers"""
    rel_record_list = []
    params = {}

    for rel_type, rel_records in relationships.items():
        # Escape the relationship type for safe use in Cypher
        escaped_rel_type = escape_cypher_identifier(rel_type)
        
        for record in rel_records:
            # Get the relationships _uid to distinguish it from other params
            record_key = record.get('_uid')
            # Create a safe parameter key
            safe_record_key = f"rel_{escape_cypher_identifier(record_key)}"
            params[safe_record_key] = record

            # Get the source and target node _uids (fixed field names)
            from_node_uid = record.get('_from_uid')
            to_node_uid = record.get('_to_uid')

            # Create a list of values and parameter keys which will be used to construct the relationship
            item = f"['{escaped_rel_type}', '{from_node_uid}', '{to_node_uid}', ${safe_record_key}]"
            rel_record_list.append(item)

    # Combine all the lists into a master list
    composite_rel_records_list = ",".join(rel_record_list)

    # Create a single query to process all the Relationship records
    query = f"""WITH [{composite_rel_records_list}] AS rel_data
                UNWIND rel_data AS relationship
                MATCH (n {{`_uid`:relationship[1]}})
                MATCH (n2 {{`_uid`:relationship[2]}})
                CALL apoc.create.relationship(n, relationship[0], relationship[3], n2) YIELD rel
                RETURN rel
    """

    return query, params

In [ ]:
rel_query, rel_params = convert_relationships_fixed(neo4j_data['relationships'])

In [ ]:
len(rel_params.keys())

In [ ]:
# Aggregate them into a single query and params dictionary
query += rel_query
params.update(rel_params)

In [ ]:
query

In [ ]:
with GraphDatabase.driver(uri, auth=(username, password)) as driver:
  records, summary, keys = driver.execute_query(query, params)